Repository openshift/hive, pull requests merged in 2018-11, with the labels that each got.

#62 awstagdeprovision: add support for deleting V2 LBs and LB Target groups
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm, size/L

#63 Add notes on troubleshooting uninstall.
  README.md
Labels: lgtm, size/S

#69 Stealing Joel's Pre-Install Cleanup PR
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
  pkg/install/generate.go
Labels: lgtm, size/M

#70 Update sd-dev image links to the latest images.
  README.md
  config/overlays/sd-dev/image_patch.yaml
Labels: lgtm, size/XS

#74 Lookup default AMIs.
  pkg/apis/hive/v1alpha1/machinepools.go
  pkg/controller/clusterdeployment/aws.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/convertconfig.go
  pkg/install/convertconfig_test.go
Labels: lgtm, size/L

#75 Update CRDs for new AMI/Zones machine pool params.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
Labels: lgtm, size/S

#76 Add code generation requirements to API types
  pkg/apis/hive/v1alpha1/register.go
Labels: lgtm, size/XS

#78 Add kubeconfig secret and API/console URLs to cluster deployment status.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, size/L

#81 Add clusterdeployments/status to controller RBAC
  config/rbac/rbac_role.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/S

#86 Update SD image links to latest release.
  README.md
  config/overlays/sd-dev/image_patch.yaml
Labels: lgtm, size/XS

#93 Remove extra log message warning
  cmd/manager/main.go
Labels: lgtm, size/XS

#92 cleanup configmap and secrets before install
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
Labels: lgtm, size/L

#84 Add doc describing how to do a service delivery release.
  docs/sd_release.md
Labels: lgtm, size/L

#100 Add dnszone crd creation to readme
  README.md
Labels: lgtm, size/XS

#103 Fix cdLog typos
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/XS

#101 Log errors during RHCOS AMI lookup.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/XS

#97 Fix lack of debug logging in sd-dev cluster.
  config/overlays/sd-dev/image_patch.yaml
Labels: lgtm, size/S

#113 awstagdeprovision: Ignore more errors
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm, size/XS

#98 Fix bugs resulting from use of generate name.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/generate.go
Labels: lgtm, size/S

#102 Add a buildah-build target.
  Makefile
  docs/sd_release.md
Labels: lgtm, size/S

#119 Fix go cache error during build 'go: disabling cache ...'
  build/build-image/Dockerfile
Labels: lgtm, size/XS

#118 Sync AWS credential secret keys with installer.
  config/templates/cluster-deployment.yaml
  pkg/awsclient/client.go
  pkg/install/generate.go
Labels: lgtm, size/S
