Repository openshift/hive, pull requests merged in 2018-12, with the labels that each got.

#124 Fix GenerateName Bug in Remote Machine Set Controller, and Uninstall Missing Credentials
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/install/generate.go
Labels: lgtm, size/S

#122 remove VPC endpoints
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm, size/M

#126 replace tectonicClusterID tag with openshiftClusterID
  README.md
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/generate.go
  test/integration/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, size/S

#129 Stop copying terraform binary out of installer image.
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/install/generate.go
Labels: lgtm, size/S

#131 update kubebuilder version
  build/build-image/Dockerfile
Labels: lgtm

#120 store cluster version into clusterdeployment status
  Gopkg.lock
  Gopkg.toml
  cmd/manager/main.go
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/utils/utils.go
Labels: lgtm, size/L

#128 Add validation webhooks for hive CRDs.
  Makefile
  cmd/hiveadmission/main.go
  cmd/manager/main.go
  config/default/kustomization.yaml
  config/hiveadmission/hiveadmission.yaml
  config/overlays/sd-dev/image_patch.yaml
  config/rbac/hiveadmission_rbac_role.yaml
  config/rbac/hiveadmission_rbac_role_binding.yaml
  config/samples/hiveadmission-review-failure.json
  config/samples/hiveadmission-review-success.json
  config/samples/hiveadmission-review-update-failure.json
  config/templates/hiveadmission.yaml
  pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook_test.go
Labels: lgtm, size/XL

#132 Add hiveadmission to Dockerfile.
  build/hive/Dockerfile
Labels: lgtm, size/XS

#130 Upload kubeadmin password after cluster creation.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
Labels: lgtm, size/L

#135 fix clusterversion.Status is more places
  contrib/pkg/installmanager/installmanager.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/utils/utils.go
Labels: lgtm, size/M

#134 Add support for specifying release image.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/templates/cluster-deployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/install/generate.go
Labels: lgtm, size/M

#136 Update SD image links to latest release.
  README.md
  config/overlays/sd-dev/image_patch.yaml
Labels: lgtm, size/XS

#137 Minor fix ups
  README.md
  config/overlays/sd-dev/image_patch.yaml
Labels: lgtm, size/S

#140 Fixed path for hiveadmission in dockerfile.
  build/hive/Dockerfile
Labels: lgtm, size/XS

#142 Add multistage Dockerfile
  Dockerfile
  Makefile
Labels: lgtm, size/M

#141 Fix renamed release override env var in installer.
  pkg/install/generate.go
Labels: lgtm, size/XS

#143 Set cluster api scheme in cluster api client builder.
  pkg/controller/utils/utils.go
Labels: lgtm, size/S

#145 Update CRD for changes to VPC API fields.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
Labels: lgtm, size/XS

#147 use install-config.yaml
  contrib/pkg/installmanager/installmanager.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/install/generate.go
Labels: lgtm, size/S
