Repository openshift/hive, pull requests merged in 2018-10, with the labels that each got.

#27 Avoid installing a clusterdeployment more than once
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/XS

#29 Fix deploy target in Makefile
  Dockerfile
  Makefile
  README.md
  build/hive/Dockerfile
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  config/rbac/rbac_role.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/M

#30 InstallConfig: use secret references instead of strings
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/templates/cluster-deployment.yaml
  pkg/apis/hive/v1alpha1/installconfig.go
  pkg/install/generate.go
Labels: lgtm, size/M

#31 Generate uninstall job on clusterdeployment deletion
  README.md
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/generate.go
Labels: lgtm, size/L

#32 Hive Install Manager Sidecar Container
  README.md
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  contrib/cmd/hiveutil/main.go
  contrib/pkg/installmanager/installmanager.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/generate.go
Labels: lgtm, size/XL

#33 Add unit tests for clusterdeployment controller
  Makefile
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  test/integration/clusterdeployment/clusterdeployment_controller_suite_test.go
  test/integration/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, size/XL

#35 Port support for cluster delete-after annotation.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, size/M

#36 delete load balancers by VPC association
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm, size/L

#37 Add ownerref to uploaded artifacts.
  Makefile
  README.md
  config/templates/cluster-deployment.yaml
  contrib/pkg/installmanager/installmanager.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/L

#40 Fixes for running controllers in-cluster.
  Makefile
  README.md
  config/default/clusterdeployment_crd_status_patch.yaml
  config/default/dnszone_crd_status_patch.yaml
  config/default/kustomization.yaml
  config/rbac/rbac_role.yaml
  hack/minishift-deploy.sh
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/install/generate.go
Labels: lgtm, size/M

#44 contrib/pkg/awstagdeprovision: Make awsFilter a public AWSFilter
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm

#45 contrib/pkg/awstagdeprovision: Move cobra code into the hiveutil command
  contrib/cmd/hiveutil/awstagdeprovision.go
  contrib/cmd/hiveutil/main.go
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm

#48 Add happy path test for install manager.
  Makefile
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
Labels: lgtm, size/L

#49 Kustomization Fixes and Overlay for SD Test Env
  README.md
  config/default/kustomization.yaml
  config/default/manager_image_patch.yaml
  config/manager/manager.yaml
  config/overlays/sd-dev/image_patch.yaml
  config/overlays/sd-dev/kustomization.yaml
Labels: lgtm, size/M

#42 Requeue clusterdeployment with delete-after annotation.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/S

#50 Add make deploy-sd-dev
  Makefile
  README.md
Labels: lgtm, size/S

#51 awstagdeprovision: Fix bucket name in debug output
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm, size/XS

#53 Add support for overriding the Hive/Installer image.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/templates/cluster-deployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/install/generate.go
Labels: lgtm, size/M

#47 contrib/pkg/awstagdeprovision: Allow for OR filters
  contrib/cmd/hiveutil/awstagdeprovision.go
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm, size/M

#52 contrib/pkg/awstagdeprovision: Switch to DescribeInstancesPages
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm, size/S

#54 delete PVs
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm, size/M

#57 Fix pointer logging in delete load balancers.
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm, size/XS

#60 Add instructions to install mockgen to README.
  README.md
Labels: lgtm, size/XS
