Repository openshift/hive, pull requests merged in 2018-09, with the labels that each got.

#2 Template for creating ClusterDeployments and spawning dummy jobs in the controller
  README.md
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/templates/cluster-deployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types_test.go
  pkg/apis/hive/v1alpha1/installconfig.go
  pkg/apis/hive/v1alpha1/machinepools.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/XL

#1 Add OWNERS
  OWNERS
Labels: lgtm, size/XS

#3 Generate a ConfigMap with an installer InstallConfig and mount in.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/M

#5 Use a yaml library that respects json tags.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/XS

#4 Add secret for AWS credentials.
  README.md
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/templates/cluster-deployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/L

#6 Change Hive repo to work with ci.
  Makefile
  build/build-image/Dockerfile
  build/test-image/Dockerfile
Labels: lgtm, size/M

#8 add initial hiveutil
  Makefile
  contrib/cmd/hiveutil/main.go
  contrib/pkg/aws_tag_deprovision/aws_tag_deprovision.go
Labels: lgtm, size/XXL

#10 Change Hive repo to be compatible w/ OpenShift CI.
  build/build-image/Dockerfile
  build/hive/Dockerfile
Labels: lgtm, size/S

#12 Installed status
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, size/L

#9 bring import naming verification into hiveutil
  Makefile
  build/verify-imports/import-rules.yaml
  contrib/cmd/hiveutil/main.go
  contrib/pkg/verification/imports.go
  pkg/apis/addtoscheme_hive_v1alpha1.go
Labels: size/L

#14 aws_tag_deprovision: continue on s3tag fetch
  contrib/pkg/aws_tag_deprovision/aws_tag_deprovision.go
Labels: lgtm, size/S

#11 Delete IAM resources if associated instance is not running
  contrib/pkg/aws_tag_deprovision/aws_tag_deprovision.go
Labels: lgtm, size/L

#13 Add make verify target
  Makefile
  contrib/cmd/hiveutil/main.go
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
Labels: lgtm, size/M, ¯\_(ツ)_/¯

#15 kustomize isn't liking the wildcards
  config/default/kustomization.yaml
Labels: lgtm, size/XS

#17 Mock Deprovision Support, and Add Debug Logging Flag
  Makefile
  README.md
  cmd/manager/main.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, size/L

#18 Fix test that was failing.
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, size/M

#19 Fix make verify for CI.
  Makefile
Labels: lgtm, size/XS

#20 Move make verify dependencies down to targets
  Makefile
Labels: lgtm, size/XS

#22 don't let newlines sneak into the secret
  README.md
Labels: lgtm, size/XS

#24 Change 'make fmt' to be inline with 'make verify-format'
  Makefile
Labels: lgtm, size/XS

#25 Use new installer to run cluster install job
  README.md
  config/templates/cluster-deployment.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/generate.go
Labels: lgtm, size/L

#26 Fix load balancer deletion hang
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm, size/XS

#28 awstagdeprovision: Tag 20 load balancers (max) per request
  contrib/pkg/awstagdeprovision/awstagdeprovision.go
Labels: lgtm, size/S
