Repository openshift/hive, pull requests merged in 2019-05, with the labels that each got.

#353 Fix typo and link to syncset docs in README.
  README.md
Labels: approved, lgtm, size/XS

#355 Adds patch verb for cis and hiveconfigs
  config/rbac/hive_admin_role.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#357 allow modifying certificateBundles and controlPlaneConfig.servingCertificates
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/awsclient/mock/client_generated.go
Labels: approved, lgtm, size/L

#356 don't allow updates to existing machinepool labels and taints
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
Labels: approved, lgtm, size/M

#359 Adding steps to watch cluster deployment and retrieve password for webconsole
  README.md
Labels: approved, lgtm, size/M

#360 Issue CO-380: Add hive-reader role
  config/rbac/hive_reader_role.yaml
  config/rbac/hive_reader_role_binding.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/L

#358 Additional metrics and cleanup.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/metrics/metrics.go
  pkg/controller/metrics/metrics_test.go
Labels: approved, lgtm, size/L

#362 Fix imageset job hotloop.
  pkg/awsclient/mock/client_generated.go
  pkg/imageset/generate.go
Labels: approved, lgtm, size/M

#363 hive-admin role can CRUD SelectorSyncSets
  config/rbac/hive_admin_role.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#364 Add ClusterDeprovisionRequest CRD and controller
  config/crds/hive_v1alpha1_clusterdeprovisionrequest.yaml
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role.yaml
  config/rbac/hive_frontend_role.yaml
  config/rbac/hive_reader_role.yaml
  config/rbac/manager_role.yaml
  config/samples/hive_v1alpha1_clusterdeprovisionrequest.yaml
  pkg/apis/hive/v1alpha1/clusterdeprovisionrequest_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_clusterdeprovisionrequest.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller_test.go
  pkg/controller/metrics/common.go
  pkg/install/generate.go
  pkg/install/generate_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XL

#365 Fix PreserveOnDelete clusters rapidly deleted after creation.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/S

#366 Use short patch strings in syncset patch definition.
  config/crds/hive_v1alpha1_selectorsyncset.yaml
  config/crds/hive_v1alpha1_syncset.yaml
  contrib/pkg/testresource/command.go
  pkg/apis/hive/v1alpha1/syncset_types.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller_test.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/resource/patch.go
  test/integration/resource/patch_test.go
Labels: approved, lgtm, size/M

#369 Fix manager role for clusterdeprovisionrequests
  config/rbac/manager_role.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/utils/sa.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#368 Validate SyncSet PatchType
  cmd/hiveadmission/main.go
  config/hiveadmission/selectorsyncset-webhook.yaml
  config/hiveadmission/syncset-webhook.yaml
  pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hiveadmission.go
Labels: approved, lgtm, size/XL

#370 Migrate patch type for SyncSets with patches
  pkg/controller/syncset/syncset_controller.go
Labels: approved, lgtm, size/M

#367 Fix failed jobs showing as running in metrics.
  pkg/controller/metrics/metrics.go
Labels: approved, lgtm, size/S

#372 Workaround for fixing jenkins git issue
  build/build-image/Dockerfile
Labels: approved, lgtm, size/XS

#374 Add provisioning underway seconds metrics.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/metrics/metrics.go
Labels: approved, lgtm, size/L

#371 Add a hiveutil report command for gather info on failed installs.
  contrib/cmd/hiveutil/main.go
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/report/cluster.go
  contrib/pkg/utils/client.go
Labels: approved, lgtm, size/L

#373 Add counter metrics for cluster create/delete events.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/M

#375 Cluster deprovision request - phase 2
  cmd/hiveadmission/main.go
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/hiveadmission/clusterdeployment-mutating-webhook.yaml
  config/operator/operator_role.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/mutating-webhooks/clusterdeployment_mutating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/metrics/common.go
  pkg/install/generate.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hiveadmission.go
  pkg/operator/util/admissionregistration.go
Labels: approved, lgtm, size/XL

#377 Adding error to log for unreachable cluster in machineset controller
  pkg/controller/remotemachineset/remotemachineset_controller.go
Labels: approved, lgtm, size/XS

#376 Give up on deprovisioning in deleted namespaces.
  config/rbac/manager_role.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#378 Fix missed delete cluster metrics.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/XS

#381 Fix cluster secrets in create-cluster command
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm

#380 Remove spec.state field in clusterdeployment
  cmd/hiveadmission/main.go
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/hiveadmission/clusterdeployment-mutating-webhook.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/mutating-webhooks/clusterdeployment_mutating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
Labels: approved, lgtm, size/L

#383 Add release image source to create-cluster
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm, size/M

#384 Optional DNS server for DNSZone checks
  pkg/controller/dnszone/zonereconciler.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm

#385 Deploy CRDs in the hive-operator.
  Makefile
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role.yaml
  config/rbac/hive_reader_role.yaml
  hack/update-bindata.sh
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/XXL

#386 Adds HiveConfig to saasherder template
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/S

#389 Remote ingress - include toleration to ensure ingresscontroller reload
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
Labels: approved, lgtm, size/M

#391 Drop outdated and broken ClusterImageSets.
  config/clusterimagesets/openshift-4.0-beta3.yaml
  config/clusterimagesets/openshift-4.0-beta4.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#393 Allow configuring additional certificate authorities for a Hive instance
  cmd/manager/main.go
  config/crds/hive_v1alpha1_hiveconfig.yaml
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/federation/clusterdeployment_federation_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/utils/cacrt.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/L

#388 Control plane certs - use additionalCertificates field
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
Labels: approved, lgtm, size/S

#395 added the additionalCertificateAuth to the hive-config to be deployed
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#397 Change README to use create-cluster instead of template.
  README.md
Labels: approved, lgtm, size/M

#392 Delay install retries with sleep.
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
  docs/developing.md
  pkg/install/generate.go
Labels: approved, lgtm, size/M

#399 missing parameter added to template
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#398 Fix DNSZone hotloop and stuck deletions
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/zonereconciler.go
Labels: approved, lgtm, size/M

#400 Update README and hiveutil create-cluster defaults
  README.md
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm, size/M

#396 Generate kubeconfig secret with additional CAs
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/federation/clusterdeployment_federation_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/utils/cacrt.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/L

#401 Workarounds for problems with managed DNSZone cleanup.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/M

#404 Fix leaking resources on install retries.
  contrib/pkg/installmanager/installmanager.go
Labels: approved, lgtm, size/XS

#403 wildcard ingress migration and webhook validation
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/awsclient/mock/client_generated.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L

#406 migrate saas-hive to ci-int instance
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm, size/XS

#402 Use release image from clusterdeployment when present
  pkg/awsclient/mock/client_generated.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/imageset/generate.go
  pkg/imageset/generate_test.go
Labels: approved, lgtm, size/L

#408 Add logging when we delete an install job due to generation change.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/XS

#409 Add logging for reconcile time in the cluster deprovisioning request …
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
Labels: approved, lgtm, size/XS

#394 Adding unreachable controller
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/add_unreachable.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/unreachable/unreachable_controller.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/XL
