Repository openshift/hive, pull requests merged in 2019-01, with the labels that each got.

#153 Improve process and docs for deploying in cluster.
  Makefile
  README.md
  config/hiveadmission/hiveadmission.yaml
  config/manager/manager.yaml
  config/templates/cluster-deployment.yaml
  manifests/00-namespace.yaml
Labels: lgtm, size/M

#154 Fix missing config.openshift.io type in scheme.
  pkg/controller/utils/utils.go
Labels: lgtm, size/XS

#159 Cleanup errors when admin kubeconfig doesn't yet exist.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/M

#160 Add install config version.
  pkg/install/convertconfig.go
  pkg/install/convertconfig_test.go
Labels: lgtm, size/XS

#161 Drop clusteruuid
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/install/convertconfig.go
  pkg/install/convertconfig_test.go
  pkg/install/generate.go
Labels: lgtm, size/L

#162 Update SD image links to latest release.
  README.md
  config/overlays/sd-dev/image_patch.yaml
Labels: lgtm, size/XS

#156 Script to install federation
  Makefile
  README.md
  hack/federation/deploy_federation.yaml
  hack/federation/federatedirectives/clusterroles.rbac.authorization.k8s.io.yaml
  hack/federation/federatedirectives/configmaps.yaml
  hack/federation/federatedirectives/deployments.apps.yaml
  hack/federation/federatedirectives/ingresses.extensions.yaml
  hack/federation/federatedirectives/jobs.batch.yaml
  hack/federation/federatedirectives/namespaces.yaml
  hack/federation/federatedirectives/replicasets.apps.yaml
  hack/federation/federatedirectives/secrets.yaml
  hack/federation/federatedirectives/serviceaccounts.yaml
  hack/federation/federatedirectives/services.yaml
  hack/install-federation.sh
Labels: lgtm, size/XL

#165 Federation controller
  Dockerfile.fedcli
  README.md
  cmd/manager/main.go
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  hack/federation/cluster-registry-crd.yaml
  hack/federation/deploy_federation.yaml
  hack/install-federation.sh
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/add_federation.go
  pkg/controller/federation/clusterdeployment_federation_controller.go
  pkg/federation/config.go
  pkg/federation/generate.go
Labels: lgtm, size/XL

#164 Separate ClusterDeployment.Machines into ControlPlane and Compute.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/templates/cluster-deployment.yaml
  contrib/pkg/installmanager/installmanager_test.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/install/convertconfig.go
  pkg/install/convertconfig_test.go
Labels: lgtm, size/L

#166 Fix deprovision only working on us-east-1.
  pkg/install/generate.go
Labels: lgtm, size/XS

#167 Upload Cluster ID before provisioning any cloud resources
  Makefile
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/install/generate.go
Labels: lgtm, size/L

#168 don't assume clusterdeploymentname == clustername
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
Labels: lgtm, size/M

#169 SD release 20190116
  README.md
  config/overlays/sd-dev/image_patch.yaml
  docs/sd_release.md
Labels: lgtm, size/S

#172 Fix installer release image override var name.
  pkg/install/generate.go
Labels: lgtm, size/XS

#174 Add operator federation example
  README.md
  contrib/federation_example/00_namespace.yaml
  contrib/federation_example/00_namespace_placement.yaml
  contrib/federation_example/cluster-role-binding-placement.yaml
  contrib/federation_example/cluster-role-binding-template.yaml
  contrib/federation_example/cluster-role-placement.yaml
  contrib/federation_example/cluster-role-template.yaml
  contrib/federation_example/deployment-placement.yaml
  contrib/federation_example/deployment-template.yaml
  hack/install-federation.sh
Labels: lgtm, size/L

#173 Preserve on delete
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, size/M

#175 Bump github.com/openshift/api
  Gopkg.lock
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  vendor/github.com/openshift/api/config/v1/register.go
  vendor/github.com/openshift/api/config/v1/types.go
  vendor/github.com/openshift/api/config/v1/types_authentication.go
  vendor/github.com/openshift/api/config/v1/types_build.go
  vendor/github.com/openshift/api/config/v1/types_cluster_operator.go
  vendor/github.com/openshift/api/config/v1/types_cluster_version.go
  vendor/github.com/openshift/api/config/v1/types_dns.go
  vendor/github.com/openshift/api/config/v1/types_idp.go
  vendor/github.com/openshift/api/config/v1/types_image.go
  vendor/github.com/openshift/api/config/v1/types_infrastructure.go
  vendor/github.com/openshift/api/config/v1/types_network.go
  vendor/github.com/openshift/api/config/v1/types_oauth.go
  vendor/github.com/openshift/api/config/v1/types_project.go
  vendor/github.com/openshift/api/config/v1/types_proxy.go
  vendor/github.com/openshift/api/config/v1/types_swagger_doc_generated.go
  vendor/github.com/openshift/api/config/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/config/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1/register.go
  vendor/github.com/openshift/api/operator/v1/types.go
  vendor/github.com/openshift/api/operator/v1/types_kubeapiserver.go
  vendor/github.com/openshift/api/operator/v1/types_kubecontrollermanager.go
  vendor/github.com/openshift/api/operator/v1/types_openshiftapiserver.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/operator/v1/zz_generated.swagger_doc_generated.go
  vendor/github.com/openshift/api/operator/v1alpha1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/XXL

#178 Fix networking in cluster deployment template.
  config/templates/cluster-deployment.yaml
Labels: lgtm, size/XS

#183 Change Makefile to run buildah as a user if on Fedora.
  Makefile
Labels: lgtm, size/S

#186 Remove AMIs from API.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/apis/hive/v1alpha1/machinepools.go
  pkg/controller/clusterdeployment/aws.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/install/convertconfig_test.go
Labels: lgtm, size/L

#187 Fix another spec modification.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: lgtm, size/XS

#189 Update deprovision vendored code for dhcp-options fix.
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go
Labels: lgtm, size/S

#190 Allow specifying a Hive image when deploying
  .gitignore
  Makefile
  config/overlays/.gitignore
  config/overlays/template/image_patch.yaml
  config/overlays/template/kustomization.yaml
Labels: lgtm, size/M

#193 Allow editing PreserveOnDelete.
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
Labels: lgtm, size/M

#192 Web console url
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/utils/utils.go
  vendor/github.com/openshift/api/route/v1/doc.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/legacy.go
  vendor/github.com/openshift/api/route/v1/register.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
Labels: lgtm, size/XXL

#185 WIP:web-console url bug
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/utils/utils.go
  vendor/github.com/openshift/api/route/v1/doc.go
  vendor/github.com/openshift/api/route/v1/generated.pb.go
  vendor/github.com/openshift/api/route/v1/legacy.go
  vendor/github.com/openshift/api/route/v1/register.go
  vendor/github.com/openshift/api/route/v1/types.go
  vendor/github.com/openshift/api/route/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/route/v1/zz_generated.swagger_doc_generated.go
Labels: do-not-merge/work-in-progress, ok-to-test, size/XXL

#194 Add annotation to try install only one time
  config/templates/cluster-deployment.yaml
  pkg/install/generate.go
Labels: lgtm, size/S

#196 Add warning to README.MD for DNS base domain.
  README.md
Labels: lgtm, size/XS

#197 Fix bugs uncovered when rolling out to opshive
  README.md
  config/overlays/sd-dev/image_patch.yaml
  pkg/controller/clusterdeployment/aws.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, size/M

#195 Update SD image links to latest release.
  README.md
  config/overlays/sd-dev/image_patch.yaml
Labels: size/XS

#199 adding https prefix to web console url
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: lgtm, ok-to-test, size/XS

#191 Add e2e test that installs hive and creates a cluster
  Makefile
  contrib/cmd/waitforjob/main.go
  hack/e2e-test.sh
Labels: lgtm, size/L

#180 Consider multiple machinepools within clusterdeployment for syncing.
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
Labels: lgtm, size/L
