Repository openshift/hive, pull requests merged in 2019-03, with the labels that each got.

#237 bump github.com/openshift/installer 02-28-2019
  Gopkg.lock
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  vendor/github.com/openshift/installer/pkg/asset/installconfig/aws/aws.go
  vendor/github.com/openshift/installer/pkg/asset/installconfig/aws/permissions.go
  vendor/github.com/openshift/installer/pkg/asset/machines/aws/machines.go
  vendor/github.com/openshift/installer/pkg/asset/machines/aws/machinesets.go
  vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go
  vendor/github.com/openshift/installer/pkg/types/openstack/platform.go
  vendor/github.com/openshift/installer/pkg/version/version.go
Labels: approved, lgtm, size/M

#235 Move tests that run test kube to integration
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/zonereconciler_test.go
  test/integration/api/clusterdeployment_types_test.go
  test/integration/api/dnszone_types_test.go
  test/integration/api/v1alpha1_suite_test.go
  test/integration/dnszone/dnszone_controller_suite_test.go
  test/integration/dnszone/dnszone_controller_test.go
  test/integration/dnszone/test_helpers.go
Labels: approved, lgtm, size/L

#233 Improve debug logging for e2e uninstall
  config/templates/cluster-deployment.yaml
  contrib/cmd/waitforjob/main.go
  hack/e2e-test.sh
  pkg/install/generate.go
Labels: approved, lgtm, size/M

#208 Remove non-worker pool when generating install config for installer.
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/install/convertconfig.go
  pkg/install/convertconfig_test.go
  pkg/install/generate.go
Labels: approved, lgtm, size/L

#236 Add syncset types.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/crds/hive_v1alpha1_selectorsyncset.yaml
  config/crds/hive_v1alpha1_syncset.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/syncset_types.go
Labels: approved, lgtm, size/XL

#240 remove generate as a dependency of docker-build
  Makefile
Labels: approved, lgtm, size/XS

#244 Add SyncIdentityProvider and SelectorSyncIdentityProvider CRDs.
  config/crds/hive_v1alpha1_selectorsyncidentityprovider.yaml
  config/crds/hive_v1alpha1_syncidentityprovider.yaml
  config/manifests/01_clusterdeployment_crd.yaml
  pkg/apis/hive/v1alpha1/identityprovider_types.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XXL

#245 vendor: Update the installer to get additional AWS deletion
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/installer/pkg/asset/installconfig/aws/permissions.go
  vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go
  vendor/github.com/openshift/installer/pkg/rhcos/ami.go
  vendor/github.com/openshift/installer/pkg/rhcos/qemu.go
Labels: approved, lgtm, size/L

#218 automatically-updating-install-job
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/generate.go
Labels: approved, lgtm, ok-to-test, size/L

#242 build_deploy.sh and pr_check.sh for AppSRE CI/CD
  build_deploy.sh
  pr_check.sh
Labels: approved, lgtm, size/M

#241 Cluster image set
  cmd/hiveadmission/main.go
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/crds/hive_v1alpha1_clusterimageset.yaml
  config/manifests/01_clusterdeployment_crd.yaml
  config/manifests/01_rbac_role.yaml
  config/rbac/rbac_role.yaml
  config/samples/hive_v1alpha1_clusterimageset.yaml
  contrib/cmd/hiveutil/main.go
  hack/boilerplate.go.txt
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/clusterimageset_types.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterimageset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterimageset_validating_admission_hook_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/dnszone/zonereconciler.go
  pkg/controller/images/controller_images.go
  pkg/controller/utils/conditions.go
  pkg/controller/utils/jobs.go
  pkg/imageset/generate.go
  pkg/imageset/generate_test.go
  pkg/imageset/updateinstaller.go
  pkg/imageset/updateinstaller_test.go
  pkg/install/generate.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/XXL

#246 Use ClusterImageSets in clusterdeployment template and in e2e
  Makefile
  config/hiveadmission/clusterimageset-webhook.yaml
  config/kustomization.yaml
  config/manifests/01_clusterimageset_crd.yaml
  config/templates/cluster-deployment.yaml
  hack/e2e-test.sh
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hiveadmission.go
Labels: approved, lgtm, size/L

#243 Remove HiveConfig image and use operator deployment image instead.
  config/crds/hive_v1alpha1_hiveconfig.yaml
  config/kustomization.yaml
  config/manifests/01_hiveconfig_crd.yaml
  config/manifests/03_hiveconfig_cr.yaml
  overlays/template/image_patch.yaml
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
Labels: approved, lgtm, size/L

#239 Override PreserveOnDelete if cd is not installed
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/generate.go
  pkg/install/generate_test.go
Labels: approved, lgtm, ok-to-test, size/M

#238 Updates for OLM packaging and deployment issues.
  Makefile
  README.md
  cmd/operator/main.go
  config/hiveadmission/apiservice.yaml
  config/hiveadmission/daemonset.yaml
  config/hiveadmission/hiveadmission_rbac_role.yaml
  config/hiveadmission/hiveadmission_rbac_role_binding.yaml
  config/hiveadmission/service-account.yaml
  config/hiveadmission/service.yaml
  config/kustomization.yaml
  config/manager/deployment.yaml
  config/manifests/01_clusterdeployment_crd.yaml
  config/manifests/01_dnszone_crd.yaml
  config/manifests/01_hiveadmission_rbac_role.yaml
  config/manifests/01_hiveconfig_crd.yaml
  config/manifests/01_operator_role_binding.yaml
  config/manifests/01_rbac_role.yaml
  config/namespace.yaml
  config/operator/01_clusterimageset_crd.yaml
  config/operator/operator_deployment.yaml
  config/operator/operator_role.yaml
  config/operator/operator_role_binding.yaml
  config/rbac/hiveadmission_rbac_role.yaml
  config/rbac/hiveadmission_rbac_role_binding.yaml
  config/templates/hive-csv-template.yaml
  hack/e2e-test.sh
  hack/generate-operator-bundle.py
  overlays/template/image_patch.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive_controller.go
Labels: approved, lgtm, size/XXL

#249 Add patch resource helper function
  contrib/cmd/hiveutil/main.go
  contrib/pkg/testresource/command.go
  pkg/resource/apply.go
  pkg/resource/factory.go
  pkg/resource/helper.go
  pkg/resource/patch.go
Labels: approved, lgtm, size/XL

#250 Generate new OLM bundles and document testing.
  build/olm-registry/Dockerfile
  bundle/0.1.494-3f73a592/hive-operator.v0.1.494-3f73a592.clusterserviceversion.yaml
  bundle/0.1.494-3f73a592/hive_v1alpha1_clusterdeployment.yaml
  bundle/0.1.494-3f73a592/hive_v1alpha1_clusterimageset.yaml
  bundle/0.1.494-3f73a592/hive_v1alpha1_dnszone.yaml
  bundle/0.1.494-3f73a592/hive_v1alpha1_hiveconfig.yaml
  bundle/0.1.494-3f73a592/hive_v1alpha1_selectorsyncidentityprovider.yaml
  bundle/0.1.494-3f73a592/hive_v1alpha1_selectorsyncset.yaml
  bundle/0.1.494-3f73a592/hive_v1alpha1_syncidentityprovider.yaml
  bundle/0.1.494-3f73a592/hive_v1alpha1_syncset.yaml
  bundle/0.1.5-4b53b492/hive-operator.v0.1.5-4b53b492.clusterserviceversion.yaml
  bundle/hive.package.yaml
  config/hiveadmission/hiveadmission_rbac_role.yaml
  docs/olm.md
  hack/generate-operator-bundle.py
  hack/olm-registry/catalog-source.yaml
  hack/olm-registry/hive-subscription.yaml
  hack/olm-registry/operator-group.yaml
Labels: approved, lgtm, size/XXL

#251 Add integration tests for apply/patch
  Makefile
  pkg/resource/apply.go
  pkg/resource/patch.go
  test/integration/clusterdeployment/clusterdeployment_controller_test.go
  test/integration/resource/apply_test.go
  test/integration/resource/patch_test.go
  test/integration/resource/resource_suite_test.go
Labels: approved, lgtm, size/L

#252 Remove generation of package bundle from OLM script.
  README.md
  bundle/0.1.5-4b53b492/hive-operator.v0.1.5-4b53b492.clusterserviceversion.yaml
  bundle/0.1.505-c57bd047/hive-operator.v0.1.505-c57bd047.clusterserviceversion.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_clusterdeployment.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_clusterimageset.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_dnszone.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_hiveconfig.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_selectorsyncidentityprovider.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_selectorsyncset.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_syncidentityprovider.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_syncset.yaml
  bundle/hive.package.yaml
  docs/olm.md
  hack/generate-operator-bundle.py
  hack/olm-registry-deploy.sh
  hack/olm-registry/catalog-source.yaml
  hack/olm-registry/hive-subscription.yaml
  hack/olm-registry/olm-artifacts-template.yaml
  hack/olm-registry/operator-group.yaml
Labels: approved, lgtm, size/L

#255 resources: add separate Info function
  contrib/pkg/testresource/command.go
  pkg/operator/assets/bindata.go
  pkg/resource/apply.go
  pkg/resource/info.go
  test/integration/resource/apply_test.go
Labels: approved, lgtm, size/L

#257 Create operator registry container in AppSRE CI/CD
  build_deploy.sh
Labels: approved, lgtm, size/M

#254 SyncSet api updates
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/crds/hive_v1alpha1_selectorsyncset.yaml
  config/crds/hive_v1alpha1_syncset.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/syncset_types.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XL

#258 fix bug in message formatting
  build_deploy.sh
Labels: approved, lgtm, size/XS

#261 Remove hiveadmission daemonset node selector.
  config/hiveadmission/daemonset.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#263 Adds IMAGE_TAG
  README.md
  build_deploy.sh
  hack/olm-registry-deploy.sh
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/M

#264 Fix a typo and relocate the AppSRE CI/CD scripts
  hack/app_sre_build_deploy.sh
  hack/app_sre_pr_check.sh
Labels: approved, lgtm, size/XS

#248 remoteingress controller
  Gopkg.lock
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/operator/operator_role.yaml
  config/rbac/rbac_role.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/controller/add_remoteingress.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XL

#265 Add hive-frontend role
  bundle/0.1.505-c57bd047/hive-operator.v0.1.505-c57bd047.clusterserviceversion.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_clusterdeployment.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_clusterimageset.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_dnszone.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_hiveconfig.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_selectorsyncidentityprovider.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_selectorsyncset.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_syncidentityprovider.yaml
  bundle/0.1.505-c57bd047/hive_v1alpha1_syncset.yaml
  bundle/hive.package.yaml
  config/kustomization.yaml
  config/rbac/hive_frontend_role.yaml
  config/rbac/hive_frontend_role_binding.yaml
  hack/generate-operator-bundle.py
Labels: approved, lgtm, size/XXL

#267 Add pods/log permission to hive-frontend role.
  config/rbac/hive_frontend_role.yaml
Labels: approved, lgtm, size/XS

#268 Remove cleanup of DeploymentConfig and legacy Services in operator
  config/operator/operator_role.yaml
  pkg/operator/hive/hive_controller.go
Labels: approved, lgtm, ok-to-test, size/M

#270 Fix defaults for olm template
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#272 Ensure release image from ClusterImageSet is set for install job
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/install/generate.go
Labels: approved, lgtm, size/L

#271 Check in generated files so we can be vendored
  .gitignore
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#273 Increase timeout for CI install job
  contrib/cmd/waitforjob/main.go
Labels: approved, lgtm, size/XS

#260 Serving Certificate API changes for ClusterDeployments
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#275 push prod image catalog
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm, size/L

#274 Add test to verify generated files
  Makefile
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  hack/verify-generated.sh
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#277 improve appsre cd pipeline
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm, size/S

#279 Replacing hiveadmission daemonset to deployment
  config/hiveadmission/deployment.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
Labels: approved, lgtm, ok-to-test, size/M

#280 Place `genclient:nonNamespaced` before `genclient`
  pkg/apis/hive/v1alpha1/clusterimageset_types.go
Labels: approved, lgtm, size/XS

#282 Add initial support for publishing prometheus metrics
  cmd/manager/main.go
  pkg/controller/add_metrics.go
  pkg/controller/metrics/metrics.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/L

#283 Fix IAM user leak on deprovision.
  pkg/install/generate.go
Labels: approved, lgtm, size/XS

#281 HiveAdmission Fixes
  cmd/operator/main.go
  config/hiveadmission/clusterimageset-webhook.yaml
  config/operator/operator_role.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
  pkg/operator/util/admissionregistration.go
  pkg/resource/apply.go
Labels: approved, lgtm, size/L

#276 Add syncidentityprovider controller.
  .gitignore
  config/rbac/rbac_role.yaml
  pkg/apis/hive/v1alpha1/syncidentityprovider_types.go
  pkg/controller/add_syncidentityprovider.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller_test.go
Labels: approved, lgtm, size/XL

#284 add Type info for the IngressController objects
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
Labels: approved, lgtm, size/S

#269 Restart Hive Admission when certs expire
  config/crds/hive_v1alpha1_hiveconfig.yaml
  config/operator/operator_role.yaml
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
Labels: approved, lgtm, size/L

#285 hack/e2e-test: Add "hive-" prefix to cluster name
  hack/e2e-test.sh
Labels: approved, lgtm, size/XS

#288 Replace incorrect use of dockercfg pull secrets with dockerconfigjson.
  config/clusterimagesets/openshift-4.0.0-0.8.yaml
  config/templates/cluster-deployment-customimageset.yaml
  config/templates/cluster-deployment.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/imageset/generate.go
  pkg/install/generate.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
  test/integration/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L

#289 DNSZone controller enhancements
  config/crds/hive_v1alpha1_dnszone.yaml
  pkg/apis/hive/v1alpha1/dnszone_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/awsclient/client.go
  pkg/awsclient/mock/client_generated.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/test_helpers.go
  pkg/controller/dnszone/zonereconciler.go
  pkg/controller/dnszone/zonereconciler_test.go
  test/integration/dnszone/dnszone_controller_suite_test.go
  test/integration/dnszone/dnszone_controller_test.go
  test/integration/dnszone/test_helpers.go
Labels: approved, lgtm, size/XXL

#290 Remove logging of full machineset in remotemachineset controller.
  pkg/controller/remotemachineset/remotemachineset_controller.go
Labels: approved, lgtm, size/S

#286 Initial syncset controller.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/rbac/rbac_role.yaml
  pkg/apis/hive/v1alpha1/syncset_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_syncset.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/controller/utils/conditions.go
Labels: approved, lgtm, size/XL

#287 Prometheus metrics
  pkg/controller/metrics/metrics.go
  pkg/install/generate.go
Labels: approved, lgtm, ok-to-test, size/M
