Repository openshift/hive, pull requests merged in 2019-07, with the labels that each got.

#471 Switch to golang 1.12
  Dockerfile
  build/build-image/Dockerfile
  docs/developing.md
Labels: approved, lgtm, size/XS

#472 Add missing metrics for syncsetinstance controller.
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
Labels: approved, lgtm, size/S

#474 Add leader election for both operator and controllers.
  cmd/manager/main.go
  cmd/operator/main.go
  config/rbac/manager_role.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#475 Add an installlog entry for the standard API timeout.
  config/configmaps/install-log-regexes-configmap.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#476 Log waiting for install job deletion and remove unnecessary nil check.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/XS

#478 controller: do not create service account for deprovision
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
Labels: approved, lgtm, size/XS

#481 Added steps to enable debug and more small enhancements
  docs/developing.md
  docs/install.md
Labels: approved, lgtm, size/L

#473 SyncSet: Add SecretReference to (Selector)SyncSet crd.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/crds/hive_v1alpha1_selectorsyncset.yaml
  config/crds/hive_v1alpha1_syncset.yaml
  config/crds/hive_v1alpha1_syncsetinstance.yaml
  pkg/apis/hive/v1alpha1/syncset_types.go
  pkg/apis/hive/v1alpha1/syncsetinstance_types.go
  pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XXL

#467 Adding GlobalPullSecret to Hive config
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/crds/hive_v1alpha1_hiveconfig.yaml
  contrib/pkg/createcluster/create.go
  docs/FAQs.md
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/constants/constants_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/controller/utils/secrets.go
  pkg/controller/utils/secrets_test.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
  pkg/imageset/generate.go
  pkg/install/convertconfig_test.go
  pkg/install/generate.go
  pkg/install/generate_test.go
  pkg/installmanager/installmanager_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/XL

#483 Adding documentation for global pull secret
  docs/using-hive.md
Labels: approved, lgtm, size/S

#480 Add Velero Backup When ClusterDeployment Changes
  cmd/manager/main.go
  config/rbac/manager_role.yaml
  pkg/controller/add_velerobackup.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/test/clusterdeployment/clusterdeployment.go
  pkg/controller/utils/constants.go
  pkg/controller/utils/utils.go
  pkg/controller/velerobackup/clusterdeployment.go
  pkg/controller/velerobackup/clusterdeployment_test.go
  pkg/controller/velerobackup/velerobackup_controller.go
  pkg/controller/velerobackup/velerobackup_controller_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XL

#486 Support empty global pull secret instead of absent.
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/XS

#485 Add templated globalPullSecrets
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS
