Repository openshift/hive, pull requests merged in 2019-04, with the labels that each got.

#294 Deploy external-dns with hive
  cmd/hiveadmission/main.go
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/crds/hive_v1alpha1_dnsendpoint.yaml
  config/crds/hive_v1alpha1_dnszone.yaml
  config/crds/hive_v1alpha1_hiveconfig.yaml
  config/external-dns/deployment.yaml
  config/external-dns/rbac_role.yaml
  config/external-dns/rbac_role_binding.yaml
  config/external-dns/service_account.yaml
  config/kustomization.yaml
  hack/generate-operator-bundle.py
  hack/update-bindata.sh
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/dnsendpoint_types.go
  pkg/apis/hive/v1alpha1/dnszone_types.go
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/externaldns.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
Labels: approved, lgtm, size/XXL

#296 Add beta-3 ImageSet
  config/clusterimagesets/openshift-4.0-beta3.yaml
  config/clusterimagesets/openshift-4.0.0-0.8.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#297 Use remote machinesets for AMI lookup.
  cmd/manager/main.go
  pkg/controller/clusterdeployment/aws.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
Labels: approved, lgtm, size/L

#295 Apply syncset patches.
  config/crds/hive_v1alpha1_selectorsyncset.yaml
  config/crds/hive_v1alpha1_syncset.yaml
  pkg/apis/hive/v1alpha1/syncset_types.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
Labels: approved, lgtm, size/XL

#298 Implement SyncSet sync mode
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/apis/hive/v1alpha1/syncset_types.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/controller/utils/utils.go
  pkg/resource/info.go
Labels: approved, lgtm, size/L

#301 Add frontend role RBAC for HiveConfig to view top level DNS zones.
  config/rbac/hive_frontend_role.yaml
Labels: approved, lgtm, size/XS

#299 Generate install-config in hiveutil install wrapper.
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/dnszone/zonereconciler.go
  pkg/controller/utils/utils.go
  pkg/install/generate.go
Labels: approved, lgtm, size/L

#302 Remove and cleanup beta2 ClusterImageSet.
  config/clusterimagesets/openshift-4.0-beta2.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#306 Add infra ID and cluster name printer columns.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
Labels: approved, lgtm, size/XS

#308 Remove cluster status resync interval.
  pkg/controller/clusterversion/clusterversion_controller.go
Labels: approved, lgtm, size/XS

#305 Deliver a hive-admin role via the operator.
  config/rbac/hive_admin_role.yaml
  config/rbac/hive_admin_role_binding.yaml
  hack/update-bindata.sh
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/XL

#310 Add control plane certificates controller
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/add_controlplanecerts.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/utils/conditions.go
  pkg/controller/utils/jobs.go
  pkg/controller/utils/rawext.go
  pkg/operator/hive/externaldns.go
  pkg/operator/hive/hive.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
  pkg/operator/util/apply.go
  pkg/resource/apply.go
  pkg/resource/cient.go
  pkg/resource/helper.go
Labels: approved, lgtm, size/XXL

#307 Install Pod Restart Metric + Status
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/rbac/rbac_role.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/install/generate.go
  pkg/operator/assets/bindata.go
  test/integration/clusterdeployment/clusterdeployment_controller_suite_test.go
  test/integration/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L

#303 add support for ingress objects referencing certificates
  config/rbac/rbac_role.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XL

#309 Re-add service for controller metric scraping.
  config/manager/service.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#311 Add metrics for total uninstalling clusters in various severities
  pkg/controller/metrics/metrics.go
  pkg/controller/metrics/metrics_test.go
Labels: approved, lgtm, size/L

#312 Add metrics for total clusters with conditions.
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/metrics/metrics.go
  pkg/controller/metrics/metrics_test.go
Labels: approved, lgtm, size/M

#314 Do not report restarts metric for install jobs with 0.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/M

#313 ResourceHelper improvements
  contrib/pkg/testresource/command.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/operator/hive/externaldns.go
  pkg/operator/hive/hive.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
  pkg/operator/util/apply.go
  pkg/resource/apply.go
  pkg/resource/factory_discovery.go
  pkg/resource/helper.go
  pkg/resource/info.go
  pkg/resource/kubeconfig_factory.go
  pkg/resource/patch.go
  pkg/resource/restconfig_factory.go
  pkg/resource/serializer.go
  test/integration/resource/apply_test.go
Labels: approved, lgtm, size/XL

#315 Add metrics for AWS API client calls.
  pkg/awsclient/client.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
Labels: approved, lgtm, size/M

#317 Disable federation controller
  pkg/controller/add_federation.go
Labels: approved, lgtm, size/S

#316 Add ClusterRole RBAC for operator to create hive-admin.
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#318 Syncset patch string
  config/crds/hive_v1alpha1_selectorsyncset.yaml
  config/crds/hive_v1alpha1_syncset.yaml
  pkg/apis/hive/v1alpha1/syncset_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller_test.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
Labels: approved, lgtm, size/M

#304 deprovision job duration metrics
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/install/generate.go
Labels: approved, lgtm, ok-to-test, size/S

#319 save installer output to configmap
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
Labels: approved, lgtm, size/L

#322 Hiveutil create-cluster command to create a clusterdeployment
  contrib/cmd/hiveutil/main.go
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm, size/XL

#323 Fix hive-admin RBAC not working due to singular types.
  config/rbac/hive_admin_role.yaml
  config/rbac/hive_frontend_role.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#324 remove sensitive lines from saved log
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
Labels: approved, lgtm, size/M

#326 clean up output to stdout before printing
  contrib/pkg/installmanager/installmanager.go
Labels: approved, lgtm, size/M

#325 Add cluster type concept and use it to partition metrics.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/templates/cluster-deployment-customimageset.yaml
  config/templates/cluster-deployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/metrics/metrics.go
  pkg/controller/metrics/metrics_test.go
  pkg/install/generate.go
Labels: approved, lgtm, size/XL

#327 Bump memory due to crashes in stage.
  config/manager/deployment.yaml
  pkg/operator/assets/bindata.go
Labels: approved, size/XS

#329 force requeue after fixing status fields and adding finalizer
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L

#333 Log elapsed time for cluster deployment reconcile.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/S

#334 Add beta4 ClusterImageSet.
  config/clusterimagesets/openshift-4.0-beta4.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#321 Provision Job duration metric
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, ok-to-test, size/S

#338 Remove object info logging.
  pkg/resource/info.go
Labels: approved, lgtm, size/XS

#335 install job kickstart duration metrics
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, ok-to-test, size/S

#337 Fix plural rbac for operator for hive CRDs.
  config/operator/operator_role.yaml
Labels: approved, lgtm, size/XS

#330 Fixing "make test"
  contrib/pkg/createcluster/create.go
  pkg/operator/util/apply.go
  pkg/resource/serializer.go
Labels: approved, lgtm, ok-to-test, size/S

#332 Adding "make clean" target to remove built artifacts
  Makefile
Labels: approved, lgtm, ok-to-test, size/XS

#340 Attempted fix for long (5-20m) delays creating install jobs.
  config/manager/deployment.yaml
  config/operator/operator_deployment.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#336 Add logging for when reconciliation loops start and finish.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
Labels: approved, lgtm, size/M

#341 Updating the Readme, removing the hack/minishift-deploy.sh
  README.md
  hack/minishift-deploy.sh
Labels: approved, lgtm, ok-to-test, size/M

#339 Document syncset.
  docs/syncidentityprovider.md
  docs/syncset.md
Labels: approved, lgtm, size/L

#343 Fix SyncSet controller hotloop.
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
Labels: approved, lgtm, size/M

#344 Remove generation from container build process.
  Dockerfile
  Makefile
  build/build-image/Dockerfile
Labels: approved, size/S

#331 Formatting changes from "make fmt" on go version 1.11.6
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/federation/clusterdeployment_federation_controller.go
  pkg/controller/federation/clusterdeployment_federation_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/imageset/updateinstaller_test.go
  pkg/install/convertconfig_test.go
Labels: ok-to-test, size/M

#348 Add named port
  config/manager/service.yaml
  pkg/operator/assets/bindata.go
Labels: approved, size/XS

#349 Drop from 100 to 5 for concurrent goroutines.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/federation/clusterdeployment_federation_controller.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/M

#342 Updating the deprovisioning steps
  README.md
Labels: approved, lgtm, ok-to-test, size/S

#347 Use `+genclient` for the configuration object
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
Labels: approved, lgtm, size/XS

#350 Using dep for gomock and mockgen
  Gopkg.lock
  Gopkg.toml
  Makefile
  README.md
  build/build-image/Dockerfile
  docs/developing.md
Labels: approved, lgtm, size/L

#351 avoid needlessly making a non-nil map
  pkg/awsclient/mock/client_generated.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
Labels: approved, lgtm, size/M

#352 Add some imageset resolution metrics
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/metrics/metrics.go
  pkg/imageset/generate.go
  pkg/install/generate.go
Labels: approved, lgtm, size/M

#345 WIP:imageset job metrics
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/metrics/metrics.go
  pkg/imageset/generate.go
  pkg/install/generate.go
Labels: do-not-merge/work-in-progress, needs-ok-to-test, size/L

#354 Skip reconciles if cluster is deleted.
  pkg/awsclient/mock/client_generated.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncset/syncset_controller.go
Labels: approved, lgtm, size/M
