Repository openshift/hive, pull requests merged in 2019-09, with the labels that each got.

#515 Improve wording around Hive's config management in docs
  README.md
  docs/FAQs.md
  docs/architecture.md
  docs/using-hive.md
Labels: approved, lgtm, size/S

#523 Update using hive examples for grabbing secrets.
  docs/using-hive.md
Labels: approved, lgtm, size/XS

#521 remove deletion of legacy hiveadmission daemonset
  pkg/operator/hive/hive_controller.go
Labels: approved, lgtm, size/M

#522 Local e2e example and instructions
  Makefile
  docs/developing.md
  hack/e2e-test.sh
  hack/local-e2e-test.sh
Labels: approved, lgtm, size/L

#520 Remove SyncSetStatus and SelectorSyncSetStatus from clusterdeployment
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XL

#525 Fix crash on nil remote MachineSet ProviderSpec.
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
Labels: approved, lgtm, size/M

#524 Refactor AWS APIs to separate package, remove OpenStack and Libvirt.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  contrib/pkg/createcluster/create.go
  pkg/apis/hive/v1alpha1/aws/doc.go
  pkg/apis/hive/v1alpha1/aws/machinepool.go
  pkg/apis/hive/v1alpha1/aws/platform.go
  pkg/apis/hive/v1alpha1/aws/zz_generated.deepcopy.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/machinepools.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/install/convertconfig_test.go
  pkg/install/generate_test.go
  pkg/operator/assets/bindata.go
  test/e2e/postinstall/machinesets/infra_test.go
Labels: approved, lgtm, size/XL

#514 Moving the installation of golangci-lint to Dockerfile
  build/build-image/Dockerfile
Labels: approved, lgtm, size/XS

#530 docs: fix typo in SelectorSyncIdentityProvider definition
  docs/syncidentityprovider.md
Labels: approved, lgtm, size/XS

#528 Removing downloading of golangci-lint in Makefile
  Makefile
Labels: approved, lgtm, size/S

#526 allow for restoring clusterdeployment and clusterprovision
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  hack/duplicate_cd.sh
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterprovision_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterprovision_validating_admission_hook_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/clusterstate/clusterstate_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/metrics/metrics.go
  pkg/controller/metrics/metrics_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/controller/unreachable/unreachable_controller.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/install/generate.go
  pkg/install/generate_test.go
  pkg/installmanager/installmanager.go
  pkg/operator/assets/bindata.go
  test/e2e/common/clusterdeployment.go
Labels: approved, lgtm, size/L

#512 Manually manage controller RBAC.
  Makefile
  config/kustomization.yaml
  config/rbac/hive_controllers_role.yaml
  config/rbac/hive_controllers_role_binding.yaml
  hack/generate-operator-bundle.py
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/velerobackup/velerobackup_controller.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XL

#531 Do not use DNS zone if not owned by clusterdeployment
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L

#491 SyncSetInstance SecretReference sync
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/resource/apply.go
Labels: approved, lgtm, size/XL

#527 fix install job creation race
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller_test.go
  pkg/controller/clusterprovision/jobexpectations.go
Labels: approved, lgtm, size/L

#533 create dummy clusterprovision for legacy clusterdeployment
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L

#532 Set installed field in cd status when cluster installed
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/S

#536 vendor: Bump installer to destroy untagged subnets
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/installer/pkg/asset/installconfig/aws/permissions.go
  vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go
  vendor/github.com/openshift/installer/pkg/types/aws/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/aws/platform.go
  vendor/github.com/openshift/installer/pkg/types/azure/platform.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
Labels: approved, lgtm, size/L

#534 Revert "create dummy clusterprovision for legacy clusterdeployment"
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L

#541 Add note on minishift admissions-webhook.
  docs/install.md
Labels: approved, lgtm, size/XS

#540 Reject authorization.openshift.io SyncSet resources with upstream equivalents.
  pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook_test.go
Labels: approved, lgtm, size/L

#539 Change Hive DR to use checkpoint object
  config/crds/hive_v1alpha1_checkpoint.yaml
  pkg/apis/hive/v1alpha1/checkpoint_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/utils/constants.go
  pkg/controller/utils/utils.go
  pkg/controller/velerobackup/helpers_test.go
  pkg/controller/velerobackup/hiveobject.go
  pkg/controller/velerobackup/hiveobject_test.go
  pkg/controller/velerobackup/velerobackup_controller.go
  pkg/controller/velerobackup/velerobackup_controller_test.go
  pkg/operator/assets/bindata.go
  pkg/test/checkpoint/checkpoint.go
  pkg/test/clusterdeployment/clusterdeployment.go
  pkg/test/dnszone/dnszone.go
  pkg/test/generic/generic.go
  pkg/test/syncset/syncset.go
Labels: approved, lgtm, size/XXL

#535 create dummy clusterprovision for legacy clusterdeployment
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L

#544 Updating diagnosing-syncset-problems and adding an exampple of syncset
  docs/syncset.md
Labels: approved, lgtm, size/M

#542 Modifying some debug messages to info in dnszone controller
  pkg/controller/dnszone/zonereconciler.go
Labels: approved, lgtm, size/XS

#547 Extend default lease duration, renew deadline and retry period for op…
  cmd/manager/main.go
  cmd/operator/main.go
Labels: approved, lgtm, size/M

#549 Lower lease duration, renew deadline and retry period to double the d…
  cmd/manager/main.go
  cmd/operator/main.go
Labels: approved, lgtm, size/S

#548 Installmanager ssh private key permissions fix.
  pkg/installmanager/installmanager.go
Labels: approved, lgtm, size/S

#551 Adding check for unreachable condition
  pkg/controller/clusterstate/clusterstate_controller.go
Labels: approved, lgtm, size/XS

#550 update syncset to use secretReferennce
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
Labels: approved, lgtm, size/L

#555 Temporarily disable the golangci-lint target due to CI issues.
  Makefile
Labels: approved, lgtm, size/XS

#559 Adding shortname for syncsetinstance
  config/crds/hive_v1alpha1_selectorsyncset.yaml
  config/crds/hive_v1alpha1_syncset.yaml
  config/crds/hive_v1alpha1_syncsetinstance.yaml
  pkg/apis/hive/v1alpha1/syncset_types.go
  pkg/apis/hive/v1alpha1/syncsetinstance_types.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#557 Grab some additional yaml artifacts after e2e tests.
  hack/e2e-test.sh
Labels: approved, lgtm, size/XS

#554 Remove secret from clusteringress syncset
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
Labels: approved, lgtm, size/M

#562 add missing conversion for non-aws machine pool platforms
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/apis/hive/v1alpha1/machinepools.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/install/convertconfig.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#563 fix error message for deprovisioning unsupported platform
  pkg/install/generate.go
Labels: approved, lgtm, size/XS

#545 Adding SyncSetFailureCondition to cluster deployment
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
Labels: approved, lgtm, size/L

#564 Add hiveutil create-cluster docs for Azure and GCP.
  docs/using-hive.md
Labels: approved, lgtm, size/M

#561 handle nil worker machine platform in remotemachineset controller
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
Labels: approved, lgtm, size/S

#565 Fixing golangci-lint cache permission issue
  Makefile
Labels: approved, lgtm, size/XS

#569 Bump to Info loglevel for DNS resolve checks.
  pkg/controller/dnszone/zonereconciler.go
Labels: approved, size/S

#570 remove TODO comment made obsolete by re-renabling golangci-lint
  Makefile
Labels: approved, lgtm, size/XS

#566 Add rate limiting to Velero backup controller
  config/crds/hive_v1alpha1_hiveconfig.yaml
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/velerobackup/helpers_test.go
  pkg/controller/velerobackup/velerobackup_controller.go
  pkg/controller/velerobackup/velerobackup_controller_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/L
