Repository openshift/hive, pull requests merged in 2019-02, with the labels that each got.

#202 additional safeguard for PreserveOnDelete
  pkg/install/generate.go
  pkg/install/generate_test.go
Labels: lgtm, size/M

#206 Update kubebuilder to 1.0.8 in builder image
  build/build-image/Dockerfile
Labels: lgtm, size/XS

#215 Fix layout for kustomize 2.0.0
  Makefile
  config/kustomization.yaml
  docs/sd_release.md
  hack/e2e-test.sh
  hack/minishift-deploy.sh
  overlays/.gitignore
  overlays/sd-dev/image_patch.yaml
  overlays/sd-dev/kustomization.yaml
  overlays/template/image_patch.yaml
  overlays/template/kustomization.yaml
Labels: lgtm, size/M

#212 Federation controller: handle label sync
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/crds/hive_v1alpha1_dnszone.yaml
  hack/install-federation.sh
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/federation/clusterdeployment_federation_controller.go
  pkg/controller/federation/clusterdeployment_federation_controller_test.go
Labels: lgtm, size/XL

#219 Change kubebuilder dep to one that respects +optional comment tags.
  Gopkg.lock
  Gopkg.toml
  vendor/sigs.k8s.io/controller-tools/pkg/internal/codegen/parse/crd.go
Labels: lgtm, size/S

#223 Add retry logic to e2e-test.sh
  hack/e2e-test.sh
Labels: lgtm, size/L

#229 Match OpenshiftSDN -> OpenShiftSDN network type change.
  config/templates/cluster-deployment.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/install/convertconfig_test.go
Labels: lgtm, size/XS

#225 Support legacy federated cluster names
  pkg/controller/federation/clusterdeployment_federation_controller.go
  pkg/controller/federation/clusterdeployment_federation_controller_test.go
Labels: lgtm, size/M

#224 Add controller to update clusterversion status
  pkg/controller/add_clusterversion.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/utils/utils.go
Labels: lgtm, size/L

#230 Short name and custom printer columns for the ClusterDeployment CRD
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  hack/e2e-test.sh
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
Labels: lgtm, size/M

#217 Cleanup use of mismatched images and clarify docs.
  README.md
  config/templates/cluster-deployment.yaml
  docs/sd_release.md
  hack/e2e-test.sh
Labels: lgtm, size/L

#207 Add MachinePool labels and taints.
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/apis/hive/v1alpha1/machinepools.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
Labels: lgtm, size/M

#232 Fix Dockerfile
  Dockerfile
Labels: lgtm, size/XS
