Repository openshift/hive, pull requests merged in 2019-06, with the labels that each got.

#411 Use oc instead of kubectl in Makefile apply commands.
  Makefile
  README.md
  docs/developing.md
  hack/e2e-test.sh
Labels: approved, lgtm, size/M

#412 Monitor install logs for errors.
  config/configmaps/install-log-regexes-configmap.yaml
  config/rbac/manager_role.yaml
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
  hack/update-bindata.sh
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/add_installlogmonitor.go
  pkg/controller/installlogmonitor/installlogmonitor_controller.go
  pkg/controller/installlogmonitor/installlogmonitor_controller_test.go
  pkg/controller/installlogmonitor/installlogregex.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/XL

#413 Validate cluster deployment name
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
Labels: approved, lgtm, size/M

#410 scaffolding for saving log tarball on failures
  config/templates/cluster-deployment.yaml
  contrib/pkg/createcluster/create.go
  contrib/pkg/installmanager/installmanager.go
  contrib/pkg/installmanager/installmanager_test.go
  pkg/awsclient/mock/client_generated.go
  pkg/install/generate.go
Labels: approved, lgtm, size/XL

#416 Write sleep seconds file when we fail to generate assets.
  contrib/pkg/installmanager/installmanager.go
  pkg/controller/installlogmonitor/installlogmonitor_controller.go
Labels: approved, lgtm, size/XS

#417 save job spec hashes for install jobs
  pkg/awsclient/mock/client_generated.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L

#414 Post-Deploy e2e tests
  Makefile
  hack/e2e-test.sh
  test/e2e/common/apiservice.go
  test/e2e/common/client.go
  test/e2e/common/deployment.go
  test/e2e/common/diff.go
  test/e2e/common/service.go
  test/e2e/postdeploy/admission/admission_test.go
  test/e2e/postdeploy/hivecontroller/manager_test.go
  test/e2e/postdeploy/operator/operator_test.go
Labels: approved, lgtm, size/XL

#419 Fix the YAMLLoadWarning in generate-operator-bundle.py
  hack/generate-operator-bundle.py
Labels: approved, lgtm, size/S

#418 Cleanup deleted SyncSet resources
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  pkg/apis/hive/v1alpha1/syncset_types.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#421 Install manager logging & safer binary copy.
  contrib/pkg/installmanager/installmanager.go
  pkg/awsclient/mock/client_generated.go
  pkg/install/generate.go
Labels: approved, lgtm, size/M

#424 Don't update cd when unreachable cond is absent in reachable cluster
  pkg/controller/unreachable/unreachable_controller.go
Labels: approved, lgtm, size/XS

#420 CO-447 Move contrib/pkg/installmanager/ to pkg/installmanager
  contrib/cmd/hiveutil/main.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: approved, lgtm, size/XS

#425 Attempt at fixing stale deprovision underway metrics.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/metrics/metrics.go
Labels: approved, lgtm, size/M

#423 remove recent command line params for passing private ssh info
  pkg/install/generate.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: approved, lgtm, size/M

#429 add new custom base image
  Dockerfile
  Dockerfile.hivebase
Labels: approved, lgtm, size/XS

#428 Add hiveutil create-cluster --delete-after.
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm, size/S

#431 Reduce configmap reconcile rate and logging.
  pkg/controller/installlogmonitor/installlogmonitor_controller.go
Labels: approved, lgtm, size/M

#430 Client Metrics
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/installlogmonitor/installlogmonitor_controller.go
  pkg/controller/metrics/clientwrapper.go
  pkg/controller/metrics/clientwrapper_test.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/unreachable/unreachable_controller.go
Labels: approved, lgtm, size/L

#422 Cleanup NS records created for managed domains
  config/external-dns/deployment.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#427 Update clusterdeployment controller to handle deleted resources
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L

#433 Less logging
  config/hiveadmission/deployment.yaml
  config/manager/deployment.yaml
  config/operator/operator_deployment.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#438 Skip reconciles for unreachable clusters.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/M

#439 Revert ClusterDeployment fixup on clusterdeployment controller
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/S

#441 Allow cluster deprovision to proceed even if dnszone has not gone away
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/XS

#434 Take control of hive-frontend role and service account.
  config/operator/operator_role.yaml
  config/rbac/hive_frontend_serviceaccount.yaml
  hack/generate-operator-bundle.py
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#436 Dns condition
  config/crds/hive_v1alpha1_hiveconfig.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#435 Ignore resource deletion forbidden when cleaning up syncset resources.
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
Labels: approved, lgtm, size/M

#443 Adding LalatenduMohanty to owners
  OWNERS
Labels: approved, lgtm, size/XS

#442 CO-455 Send install job duration metric only for the first time install
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/M

#444 Remove duplicate syncset status entries
  pkg/controller/syncset/syncset_controller.go
Labels: approved, lgtm, size/S

#446 Add controller reconcile time metrics for all controllers.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/installlogmonitor/installlogmonitor_controller.go
  pkg/controller/metrics/metrics.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/unreachable/unreachable_controller.go
Labels: approved, lgtm, size/L

#447 Reduce metrics and resource apply logging.
  config/hiveadmission/deployment.yaml
  pkg/controller/metrics/metrics.go
  pkg/operator/assets/bindata.go
  pkg/resource/helper.go
  pkg/resource/kubeconfig_factory.go
  pkg/resource/patch.go
  pkg/resource/restconfig_factory.go
Labels: approved, lgtm, size/L

#448 Trivial changes to make code more readable
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/M

#437 SyncSetInstance API and controller
  config/crds/hive_v1alpha1_syncsetinstance.yaml
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role.yaml
  config/rbac/hive_reader_role.yaml
  config/rbac/manager_role.yaml
  config/samples/hive_v1alpha1_syncsetinstance.yaml
  pkg/apis/hive/v1alpha1/syncsetinstance_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_syncsetinstance.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XXL

#449 Expanding the introduction and adding a FAQ doc
  README.md
  docs/FAQs.md
Labels: approved, lgtm, size/S

#450 Make logging from CD consistent with other controllers
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/XS

#445 Remote client metrics
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/installlogmonitor/installlogmonitor_controller.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/controller/unreachable/unreachable_controller.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/controller/utils/clientwrapper.go
  pkg/controller/utils/clientwrapper_test.go
  pkg/controller/utils/utils.go
  pkg/resource/helper.go
  pkg/resource/kubeconfig_factory.go
  pkg/resource/restconfig_factory.go
Labels: approved, lgtm, size/L

#451 CO-458 Stop Deploying openshift-v4.0-latest in Hive operator
  config/clusterimagesets/openshift-4.0-latest.yaml
  hack/update-bindata.sh
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#453 Fix validation check on machine pool mutation
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
Labels: approved, lgtm, size/XS

#452 Add permissions to allow debug of admission
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#454 E2E MachineSet post-install test
  Makefile
  contrib/pkg/createcluster/create.go
  hack/e2e-test.sh
  test/e2e/common/clusterdeployment.go
  test/e2e/common/machine.go
  test/e2e/common/machineset.go
  test/e2e/common/node.go
  test/e2e/postinstall/machinesets/infra_test.go
Labels: approved, lgtm, size/L

#456 Removing deadcode from controllers
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
Labels: approved, lgtm, size/M

#458 Use kustomize edit to set image in make deploy
  Makefile
  overlays/template/image_patch.yaml
  overlays/template/kustomization.yaml
Labels: approved, lgtm, size/M

#459 Remove e2e test timeout
  Makefile
Labels: approved, lgtm, size/XS

#457 Use hiveutil create-cluster in e2e test
  contrib/cmd/hiveutil/main.go
  contrib/pkg/createcluster/create.go
  contrib/pkg/deprovision/awstagdeprovision.go
  hack/e2e-test.sh
Labels: approved, lgtm, size/M

#462 Remove legacy controller gen of install config.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/generate.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: approved, lgtm, size/L

#464 Vendor Heptio Velero
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/heptio/velero/LICENSE
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/backup.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/backup_storage_location.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/constants.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/delete_backup_request.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/doc.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/download_request.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/labels_annotations.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/pod_volume_backup.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/pod_volume_restore.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/register.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/restic_repository.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/restore.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/schedule.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/server_status_request.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/volume_snapshot_location.go
  vendor/github.com/heptio/velero/pkg/apis/velero/v1/zz_generated.deepcopy.go
  vendor/github.com/heptio/velero/site/_includes/contributors.html
Labels: approved, lgtm, size/XXL

#466 ClusterRole hive-admin can edit selectorsyncidentityproviders CRs
  config/rbac/hive_admin_role.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#463 Add regex for no matching route53 zone found.
  config/configmaps/install-log-regexes-configmap.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#455 Adding golangci-lint to Makefile
  Makefile
  golangci.yml
Labels: approved, lgtm, size/M

#460 Fixing ineffectual assignment to errors
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/resource/apply.go
Labels: approved, lgtm, size/S

#461 Documentation update.
  README.md
  docs/FAQs.md
  docs/architecture.md
  docs/developing.md
  docs/hive-architecture.drawio
  docs/hive-architecture.png
  docs/install.md
  docs/troubleshooting.md
  docs/using-hive.md
Labels: approved, lgtm, size/XL

#469 Simplifying a conditional loop in cluster deployment controller
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/S

#465 Regenerate deprovision jobs when spec changes.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller_test.go
  pkg/controller/utils/jobs.go
  pkg/install/generate.go
Labels: approved, lgtm, size/L
