Repository openshift/hive, pull requests merged in 2019-11, with the labels that each got.

#643 docs: Corrected aws environment var.
  docs/developing.md
Labels: approved, lgtm, ok-to-test, size/XS

#651 docs: Added syncset and seletorsyncset to FAQ.
  docs/FAQs.md
Labels: approved, lgtm, ok-to-test, size/S

#650 docs: added a note for the creation of secret for AWS
  docs/using-hive.md
Labels: approved, lgtm, ok-to-test, size/XS

#618 controllers: set .spec.installed last
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/L

#665 Previous cluster ID and infra ID must not be set for pre-installed cluster
  hack/duplicate_cd.sh
Labels: approved, lgtm, size/XS

#667 docs: hiveadmission-dev-cert.sh request cfssl and cfssljson.
  docs/developing.md
  hack/hiveadmission-dev-cert.sh
Labels: approved, lgtm, ok-to-test, size/M

#660 Add InstallConfigSecret for v1 API.
  config/crds/hive_v1_clusterdeployment.yaml
  contrib/pkg/createcluster/aws.go
  contrib/pkg/createcluster/azure.go
  contrib/pkg/createcluster/create.go
  contrib/pkg/createcluster/gcp.go
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/install/convertconfig.go
  pkg/install/convertconfig_test.go
  pkg/install/generate.go
  pkg/install/generate_test.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XXL

#662 move cluster metadata from status to spec in clusterdeployment
  config/crds/hive_v1_clusterdeployment.yaml
  contrib/pkg/report/provisioning.go
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/clusterstate/clusterstate_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/controller/unreachable/unreachable_controller.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/operator/assets/bindata.go
Labels: approved, size/XL

#664 allow user to add manifests to be installed
  config/crds/hive_v1_clusterdeployment.yaml
  config/samples/manifests/sample-manifest.yaml
  contrib/pkg/createcluster/create.go
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/install/generate.go
  pkg/installmanager/installmanager.go
  pkg/operator/assets/bindata.go
Labels: approved, size/L

#671 fix integration test still using removed fields in clusterdpeloyment
  test/integration/api/clusterdeployment_types_test.go
Labels: approved, lgtm, size/XS

#670 bump default instance size (match v1 branch)
  contrib/pkg/createcluster/aws.go
Labels: approved, lgtm, size/XS

#672 Add missing nil check for ClusterMetadata.
  pkg/controller/clusterprovision/clusterprovision_controller.go
Labels: approved, lgtm, size/XS

#663 add webhook validation for GCP to ensure the instance types are provided
  contrib/pkg/createcluster/gcp.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
Labels: approved, lgtm, size/L

#669 types: change names of references to include the resource type
  config/crds/hive_v1_clusterdeployment.yaml
  contrib/pkg/createcluster/aws.go
  contrib/pkg/createcluster/azure.go
  contrib/pkg/createcluster/create.go
  contrib/pkg/createcluster/gcp.go
  pkg/apis/hive/v1/aws/platform.go
  pkg/apis/hive/v1/aws/zz_generated.deepcopy.go
  pkg/apis/hive/v1/azure/platform.go
  pkg/apis/hive/v1/azure/zz_generated.deepcopy.go
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/gcp/platform.go
  pkg/apis/hive/v1/gcp/zz_generated.deepcopy.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/install/generate.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XL

#673 update status conditions on Spec instead of Status
  pkg/controller/clusterprovision/clusterprovision_controller.go
Labels: approved, lgtm, size/XS

#674 Add "Ref" to the name of every reference field
  config/crds/hive_v1_clusterdeployment.yaml
  config/crds/hive_v1_clusterdeprovisionrequest.yaml
  config/crds/hive_v1_clusterprovision.yaml
  config/crds/hive_v1_dnszone.yaml
  config/crds/hive_v1_hiveconfig.yaml
  config/crds/hive_v1_syncsetinstance.yaml
  contrib/pkg/adm/managedns/enable.go
  contrib/pkg/createcluster/aws.go
  contrib/pkg/createcluster/azure.go
  contrib/pkg/createcluster/create.go
  contrib/pkg/createcluster/gcp.go
  contrib/pkg/report/provisioning.go
  pkg/apis/hive/v1/aws/platform.go
  pkg/apis/hive/v1/aws/zz_generated.deepcopy.go
  pkg/apis/hive/v1/azure/platform.go
  pkg/apis/hive/v1/azure/zz_generated.deepcopy.go
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/clusterdeprovisionrequest_types.go
  pkg/apis/hive/v1/clusterprovision_types.go
  pkg/apis/hive/v1/dnszone_types.go
  pkg/apis/hive/v1/gcp/platform.go
  pkg/apis/hive/v1/gcp/zz_generated.deepcopy.go
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/apis/hive/v1/syncsetinstance_types.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/clusterprovision_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterprovision_validating_admission_hook_test.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller_test.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller_test.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/clusterstate/clusterstate_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/test_helpers.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/controller/unreachable/unreachable_controller.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/install/generate.go
  pkg/install/generate_test.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/externaldns.go
  pkg/operator/hive/hive.go
  test/e2e/common/clusterdeployment.go
Labels: approved, lgtm, size/XL

#675 save infra ID in Spec instead of Status
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
Labels: approved, lgtm, size/XS

#676 add Ref to responses in validation failures
  pkg/apis/hive/v1/validating-webhooks/clusterprovision_validating_admission_hook.go
Labels: approved, lgtm, size/XS

#678 Rebuild bindata with Ref name changes.
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#679 Fix kubectl display of InfraID for new location.
  config/crds/hive_v1_clusterdeployment.yaml
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#680 Change the file name to v1
  pkg/apis/addtoscheme_hive_v1.go
Labels: approved, lgtm, size/XS

#682 make Provisioning and InstallConfigSecretRef.Name required
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
Labels: approved, lgtm, size/M

#661 Added ssh-public-key secret creation
  docs/using-hive.md
Labels: approved, lgtm, size/XS

#683 update e2e tests for v1 API changes
  test/e2e/common/clusterdeployment.go
  test/e2e/postdeploy/operator/operator_test.go
  test/e2e/postinstall/machinesets/infra_test.go
Labels: approved, lgtm, size/S

#684 docs: updated e2e test steps.
  docs/developing.md
Labels: approved, lgtm, ok-to-test, size/S

#686 don't create empty secret for ssh-private-key
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm, size/XS

#659 support for gcp dnsendpoints
  config/crds/hive_v1alpha1_hiveconfig.yaml
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/dnsendpoint/dnsendpoint_controller.go
  pkg/controller/dnsendpoint/nameserver/aws.go
  pkg/controller/dnsendpoint/nameserver/aws_test.go
  pkg/controller/dnsendpoint/nameserver/domain.go
  pkg/controller/dnsendpoint/nameserver/gcp.go
  pkg/controller/dnsendpoint/nameserver/gcp_live_test.go
  pkg/controller/dnsendpoint/nameserver/gcp_test.go
  pkg/gcpclient/client.go
  pkg/gcpclient/mock/client_generated.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/XL

#690 don't add a nil secret to list of objects to generate
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm, size/XS

#688 Fix missing details in Azure install-config and CD.Spec.
  contrib/pkg/createcluster/azure.go
Labels: approved, lgtm, size/S

#697 Add hiveutil create-cluster support for adopting clusters.
  contrib/pkg/createcluster/create.go
  docs/developing.md
  hack/create-kind-cluster.sh
Labels: approved, lgtm, size/L

#696 Updated makefile by adding .PHONY for make target
  Makefile
Labels: approved, lgtm, ok-to-test, size/XS

#695 Prevent running a ClusterDeprovision job if owning cluster is not del…
  pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
Labels: approved, lgtm, size/L

#699 Update SelectorSyncSet label selector doc.
  docs/syncset.md
Labels: approved, lgtm, size/XS

#700 dnsendpoint: fix dotting for gcp
  pkg/controller/dnsendpoint/nameserver/gcp.go
  pkg/controller/dnsendpoint/nameserver/gcp_live_test.go
Labels: approved, lgtm, size/M

#691 move machine pool to separate crd
  cmd/hiveadmission/main.go
  config/crds/hive_v1_clusterdeployment.yaml
  config/crds/hive_v1_machinepool.yaml
  config/hiveadmission/machinepool-webhook.yaml
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role.yaml
  config/rbac/hive_controllers_role.yaml
  config/rbac/hive_frontend_role.yaml
  config/rbac/hive_reader_role.yaml
  contrib/pkg/createcluster/aws.go
  contrib/pkg/createcluster/azure.go
  contrib/pkg/createcluster/create.go
  contrib/pkg/createcluster/gcp.go
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/machinepool_types.go
  pkg/apis/hive/v1/machinepools.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hiveadmission.go
  test/e2e/common/machinepool.go
  test/e2e/postinstall/machinesets/infra_test.go
  test/integration/api/clusterdeployment_types_test.go
Labels: approved, lgtm, size/XXL

#702 merge master into v1
  Makefile
  docs/syncset.md
  pkg/controller/dnsendpoint/nameserver/gcp.go
  pkg/controller/dnsendpoint/nameserver/gcp_live_test.go
Labels: approved, lgtm, size/M

#703 v1 default deploy image
  Makefile
Labels: approved, lgtm, size/XS

#701 dnsendpoint: do not reconcile until initial scrape of root domain
  pkg/controller/dnsendpoint/dnsendpoint_controller.go
  pkg/controller/dnsendpoint/dnsendpoint_controller_test.go
  pkg/controller/dnsendpoint/nameserverscraper.go
  pkg/controller/dnsendpoint/nameserverscraper_test.go
Labels: approved, lgtm, size/M

#704 merge master into v1
  pkg/controller/dnsendpoint/dnsendpoint_controller.go
  pkg/controller/dnsendpoint/dnsendpoint_controller_test.go
  pkg/controller/dnsendpoint/nameserverscraper.go
  pkg/controller/dnsendpoint/nameserverscraper_test.go
Labels: approved, lgtm, size/M

#705 docs: modify CRD to CR
  docs/using-hive.md
Labels: approved, lgtm, ok-to-test, size/XS

#698 Add a gcp actuator to the dnszone controller
  config/crds/hive_v1alpha1_dnszone.yaml
  contrib/pkg/createcluster/gcp.go
  pkg/apis/hive/v1alpha1/dnszone_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/dnsendpoint/nameserver/aws.go
  pkg/controller/dnsendpoint/nameserver/domain.go
  pkg/controller/dnsendpoint/nameserver/gcp.go
  pkg/controller/dnsendpoint/nameserver/gcp_live_test.go
  pkg/controller/dnszone/awsactuator.go
  pkg/controller/dnszone/awsactuator_test.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/dnszone_controller_test.go
  pkg/controller/dnszone/gcpactuator.go
  pkg/controller/dnszone/gcpactuator_test.go
  pkg/controller/dnszone/test_helpers.go
  pkg/controller/utils/domain.go
  pkg/gcpclient/client.go
  pkg/gcpclient/mock/client_generated.go
  pkg/install/generate.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XXL

#708 do not allow more than one compute machine pool on GCP
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
Labels: approved, lgtm, size/L

#709 Document deploying a temp prometheus to view hive metrics.
  config/prometheus/prometheus-configmap.yaml
  config/prometheus/prometheus-deployment.yaml
  docs/developing.md
Labels: approved, lgtm, size/M

#694 machineset controller for gcp (using syncsets)
  Gopkg.lock
  Makefile
  pkg/controller/add_syncmachineset.go
  pkg/controller/syncmachineset/actuator.go
  pkg/controller/syncmachineset/gcpactuator.go
  pkg/controller/syncmachineset/gcpactuator_test.go
  pkg/controller/syncmachineset/mock/actuator_generated.go
  pkg/controller/syncmachineset/syncmachineset_controller.go
  pkg/controller/syncmachineset/syncmachineset_controller_test.go
  pkg/gcpclient/client.go
  pkg/gcpclient/mock/client_generated.go
  vendor/github.com/openshift/cluster-api-provider-gcp/LICENSE
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/doc.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderstatus_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/register.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/installer/pkg/asset/machines/gcp/machines.go
  vendor/github.com/openshift/installer/pkg/asset/machines/gcp/machinesets.go
  vendor/github.com/openshift/installer/pkg/asset/machines/gcp/zones.go
Labels: approved, lgtm, size/XXL

#711 add hiveadmission certs to git ignore
  .gitignore
Labels: approved, lgtm, size/XS

#713 V1 DNS Field Updates
  config/crds/hive_v1_dnszone.yaml
  config/crds/hive_v1_hiveconfig.yaml
  pkg/apis/hive/v1/dnszone_types.go
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/dnszone/awsactuator.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/test_helpers.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#710 enable managedDNS for GCP
  contrib/pkg/adm/managedns/enable.go
  contrib/pkg/createcluster/gcp.go
  contrib/pkg/utils/gcp/gcp.go
  docs/using-hive.md
  hack/e2e-test.sh
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/dnsendpoint/nameserver/gcp.go
Labels: approved, lgtm, size/L

#712 e2e: use namespace instead of project
  hack/e2e-test.sh
Labels: approved, lgtm, size/S

#715 add hive-frontend Group to ClusterRoleBinding
  config/rbac/hive_frontend_role_binding.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#716 hive-frontend ClusterRoleBinding fix
  config/rbac/hive_frontend_role_binding.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#717 merge master into v1
  .gitignore
  Gopkg.lock
  Makefile
  config/crds/hive_v1_dnszone.yaml
  config/rbac/hive_frontend_role_binding.yaml
  contrib/pkg/adm/managedns/enable.go
  contrib/pkg/createcluster/gcp.go
  contrib/pkg/utils/gcp/gcp.go
  docs/using-hive.md
  hack/e2e-test.sh
  pkg/apis/hive/v1/dnszone_types.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/add_syncmachineset.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/dnsendpoint/nameserver/aws.go
  pkg/controller/dnsendpoint/nameserver/domain.go
  pkg/controller/dnsendpoint/nameserver/gcp.go
  pkg/controller/dnsendpoint/nameserver/gcp_live_test.go
  pkg/controller/dnszone/awsactuator.go
  pkg/controller/dnszone/awsactuator_test.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/dnszone_controller_test.go
  pkg/controller/dnszone/gcpactuator.go
  pkg/controller/dnszone/gcpactuator_test.go
  pkg/controller/dnszone/test_helpers.go
  pkg/controller/syncmachineset/actuator.go
  pkg/controller/syncmachineset/gcpactuator.go
  pkg/controller/syncmachineset/gcpactuator_test.go
  pkg/controller/syncmachineset/mock/actuator_generated.go
  pkg/controller/syncmachineset/syncmachineset_controller.go
  pkg/controller/syncmachineset/syncmachineset_controller_test.go
  pkg/controller/utils/domain.go
  pkg/gcpclient/client.go
  pkg/gcpclient/mock/client_generated.go
  pkg/install/generate.go
  pkg/operator/assets/bindata.go
  vendor/github.com/openshift/cluster-api-provider-gcp/LICENSE
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/doc.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderconfig_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/gcpmachineproviderstatus_types.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/register.go
  vendor/github.com/openshift/cluster-api-provider-gcp/pkg/apis/gcpprovider/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/installer/pkg/asset/machines/gcp/machines.go
  vendor/github.com/openshift/installer/pkg/asset/machines/gcp/machinesets.go
  vendor/github.com/openshift/installer/pkg/asset/machines/gcp/zones.go
Labels: approved, lgtm, size/XXL

#719 fix hive-frontend ClusterRoleBinding
  config/rbac/hive_frontend_role_binding.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#718 clear finalizer on machinepool when clusterdeployment deleted
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
Labels: approved, lgtm, size/L
