Repository openshift/hive, pull requests merged in 2019-12, with the labels that each got.

#721 Add basic support for bare metal cluster provisioning.
  config/crds/hive_v1_clusterdeployment.yaml
  pkg/apis/hive/v1/baremetal/machinepool.go
  pkg/apis/hive/v1/baremetal/platform.go
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/imageset/generate.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#722 Add scripting and notes from first scale test.
  hack/scaletest/README.md
  hack/scaletest/syncset-template.yaml
  hack/scaletest/test_setup.sh
Labels: approved, lgtm, size/L

#724 Add docs for managedDomains behavior.
  config/crds/hive_v1alpha1_hiveconfig.yaml
  docs/using-hive.md
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#730 Fix secretReference kind validation.
  pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook_test.go
  pkg/controller/syncmachineset/syncmachineset_controller_test.go
Labels: approved, lgtm, size/L

#729 fix ClusterDeployment column in cluster provision
  config/crds/hive_v1_clusterprovision.yaml
  pkg/apis/hive/v1/clusterprovision_types.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#681 Requeue successful ssi for resync.
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
Labels: approved, lgtm, size/M

#728 fix machinepool validator so that validation is not skipped
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
Labels: approved, lgtm, size/XS

#558 Remove ApplyOnce PatchApplyMode.
  config/crds/hive_v1_selectorsyncset.yaml
  config/crds/hive_v1_syncset.yaml
  docs/syncset.md
  pkg/apis/hive/v1/syncset_types.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#727 move gcp machineset functionality to remotemachinesets controller
  pkg/controller/add_syncmachineset.go
  pkg/controller/remotemachineset/actuator.go
  pkg/controller/remotemachineset/awsactuator.go
  pkg/controller/remotemachineset/awsactuator_test.go
  pkg/controller/remotemachineset/gcpactuator.go
  pkg/controller/remotemachineset/gcpactuator_test.go
  pkg/controller/remotemachineset/mock/actuator_generated.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/syncmachineset/gcpactuator_test.go
  pkg/controller/syncmachineset/syncmachineset_controller.go
  pkg/controller/syncmachineset/syncmachineset_controller_test.go
  test/e2e/postinstall/machinesets/infra_test.go
Labels: approved, lgtm, size/XXL

#726 Add documentation for secretReferences
  docs/syncset.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#734 merge master into v1
  config/crds/hive_v1_hiveconfig.yaml
  config/rbac/hive_frontend_role_binding.yaml
  docs/using-hive.md
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook_test.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#706 types: remove dnsendpoint resource
  config/crds/hive_v1_dnsendpoint.yaml
  config/rbac/hive_admin_role.yaml
  config/rbac/hive_controllers_role.yaml
  config/rbac/hive_reader_role.yaml
  pkg/apis/hive/v1/dnsendpoint_types.go
  pkg/apis/hive/v1/dnszone_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/dnsendpoint/dnsendpoint_controller.go
  pkg/controller/dnsendpoint/dnsendpoint_controller_test.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/dnszone_controller_test.go
  pkg/controller/dnszone/test_helpers.go
  pkg/controller/utils/conditions.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/XL

#733 installmanager: fix interactions with installer logs
  pkg/installmanager/installmanager.go
Labels: approved, lgtm, size/L

#735 allow machine pools to be auto-scaled
  Gopkg.lock
  config/crds/hive_v1_machinepool.yaml
  pkg/apis/hive/v1/machinepool_types.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/utils/conditions.go
  pkg/controller/utils/utils.go
  pkg/operator/assets/bindata.go
  test/e2e/common/client.go
  test/e2e/postinstall/machinesets/infra_test.go
  vendor/github.com/openshift/cluster-autoscaler-operator/LICENSE
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1/clusterautoscaler_types.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1/doc.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1/register.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1/zz_generated.defaults.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1/zz_generated.openapi.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1beta1/doc.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1beta1/machineautoscaler_types.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1beta1/register.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1beta1/zz_generated.defaults.go
  vendor/github.com/openshift/cluster-autoscaler-operator/pkg/apis/autoscaling/v1beta1/zz_generated.openapi.go
  vendor/github.com/openshift/cluster-network-operator/pkg/apis/networkoperator/v1/doc.go
  vendor/github.com/openshift/cluster-network-operator/pkg/apis/networkoperator/v1/networkconfig_types.go
  vendor/github.com/openshift/cluster-network-operator/pkg/apis/networkoperator/v1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#737 build: include mockgen in build image
  build/build-image/Dockerfile
Labels: approved, lgtm, size/XS

#720 Add SyncSet metrics.
  Makefile
  config/crds/hive_v1alpha1_syncsetinstance.yaml
  pkg/apis/hive/v1alpha1/syncsetinstance_types.go
  pkg/controller/metrics/metrics.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/L

#736 makefile: do not install mockgen automatically
  Makefile
  docs/developing.md
  hack/make
Labels: approved, lgtm, size/M

#741 Restore adding apply error message to syncsetinstance status condition.
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
Labels: approved, lgtm, size/M

#723 Allow bare metal validation to pass and begin execution.
  Dockerfile
  Dockerfile.dev
  config/crds/hive_v1_clusterdeployment.yaml
  config/crds/hive_v1_machinepool.yaml
  pkg/apis/hive/v1/baremetal/machinepools.go
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/machinepool_types.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#739 Disable deprovision for baremetal clusters.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/M

#743 Remove variable cache dir from applyTempFileMatcher.
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
Labels: approved, lgtm, size/S

#747 add field to HiveConfig for setting log level
  config/crds/hive_v1_hiveconfig.yaml
  config/manager/deployment.yaml
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/S

#744 types: add /scale subresource for MachinePools
  config/crds/hive_v1_machinepool.yaml
  pkg/apis/hive/v1/machinepool_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#738 types: move provision images
  config/crds/hive_v1_clusterdeployment.yaml
  contrib/pkg/createcluster/create.go
  contrib/pkg/report/provisioning.go
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/generate.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#748 add user-agent to aws and gcp requests
  pkg/awsclient/client.go
  pkg/gcpclient/client.go
Labels: approved, lgtm, size/S

#746 extra installer environment variables
  config/crds/hive_v1_clusterdeployment.yaml
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/install/generate.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#754 api url override
  config/crds/hive_v1_clusterdeployment.yaml
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/clusterstate/clusterstate_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/controller/unreachable/unreachable_controller.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/controller/utils/cacrt.go
  pkg/controller/utils/utils.go
  pkg/operator/assets/bindata.go
  pkg/remoteclient/mock/remoteclient_generated.go
  pkg/remoteclient/remoteclient.go
  pkg/remoteclient/remoteclient_test.go
  pkg/remoteclient/testdata/kubeconfig.sample
  test/e2e/common/clusterdeployment.go
Labels: approved, lgtm, size/XXL

#745 remove gcp project_id from clusterdeployment
  config/crds/hive_v1_clusterdeployment.yaml
  config/crds/hive_v1_clusterdeprovision.yaml
  contrib/pkg/createcluster/create.go
  contrib/pkg/createcluster/gcp.go
  contrib/pkg/deprovision/gcp.go
  docs/using-hive.md
  hack/e2e-test.sh
  pkg/apis/hive/v1/clusterdeprovision_types.go
  pkg/apis/hive/v1/gcp/platform.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/dnsendpoint/nameserver/gcp.go
  pkg/controller/dnsendpoint/nameserver/gcp_live_test.go
  pkg/gcpclient/client.go
  pkg/install/generate.go
  pkg/installmanager/installmanager.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#757 dnszone: info level for log when deleting non-empty hosted zone
  pkg/controller/dnsendpoint/nameserver/gcp.go
  pkg/controller/dnszone/awsactuator.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/gcpactuator.go
  pkg/gcpclient/client.go
Labels: approved, lgtm, size/M

#756 install: use merged pull secret in install-config
  contrib/pkg/createcluster/create.go
  pkg/install/generate.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
  pkg/installmanager/testdata/install-config-with-existing-pull-secret.yaml
  pkg/installmanager/testdata/install-config-with-pull-secret.yaml
  pkg/installmanager/testdata/install-config.yaml
  pkg/installmanager/testdata/pull-secret.json
Labels: approved, lgtm, size/L

#752 Fix baremetal provisioning when run on OpenShift.
  Dockerfile
  Dockerfile.dev
  pkg/install/generate.go
  pkg/installmanager/installmanager.go
Labels: approved, lgtm, size/M

#759 Tweaks to docs from trying to compile a fresh checkout
  docs/developing.md
Labels: approved, lgtm, size/XS

#760 Add controller and operator health check
  Gopkg.lock
  cmd/manager/main.go
  cmd/operator/main.go
  config/manager/deployment.yaml
  config/operator/operator_deployment.yaml
  pkg/operator/assets/bindata.go
  vendor/github.com/docker/distribution/LICENSE
  vendor/github.com/docker/distribution/context/context.go
  vendor/github.com/docker/distribution/context/doc.go
  vendor/github.com/docker/distribution/context/http.go
  vendor/github.com/docker/distribution/context/logger.go
  vendor/github.com/docker/distribution/context/trace.go
  vendor/github.com/docker/distribution/context/util.go
  vendor/github.com/docker/distribution/context/version.go
  vendor/github.com/docker/distribution/registry/api/errcode/errors.go
  vendor/github.com/docker/distribution/registry/api/errcode/handler.go
  vendor/github.com/docker/distribution/registry/api/errcode/register.go
  vendor/github.com/docker/distribution/uuid/uuid.go
  vendor/github.com/docker/go-healthcheck/LICENSE
  vendor/github.com/docker/go-healthcheck/doc.go
  vendor/github.com/docker/go-healthcheck/health.go
  vendor/github.com/gorilla/mux/AUTHORS
  vendor/github.com/gorilla/mux/LICENSE
  vendor/github.com/gorilla/mux/context.go
  vendor/github.com/gorilla/mux/doc.go
  vendor/github.com/gorilla/mux/middleware.go
  vendor/github.com/gorilla/mux/mux.go
  vendor/github.com/gorilla/mux/regexp.go
  vendor/github.com/gorilla/mux/route.go
  vendor/github.com/gorilla/mux/test_helpers.go
Labels: approved, lgtm, size/XXL

#761 generate clientset
  Gopkg.lock
  Gopkg.toml
  pkg/apis/apis.go
  pkg/client/clientset-generated/clientset/clientset.go
  pkg/client/clientset-generated/clientset/doc.go
  pkg/client/clientset-generated/clientset/fake/clientset_generated.go
  pkg/client/clientset-generated/clientset/fake/doc.go
  pkg/client/clientset-generated/clientset/fake/register.go
  pkg/client/clientset-generated/clientset/scheme/doc.go
  pkg/client/clientset-generated/clientset/scheme/register.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/checkpoint.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/clusterdeployment.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/clusterdeprovision.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/clusterimageset.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/clusterprovision.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/clusterstate.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/dnszone.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/doc.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/doc.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_checkpoint.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_clusterdeployment.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_clusterdeprovision.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_clusterimageset.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_clusterprovision.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_clusterstate.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_dnszone.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_hive_client.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_hiveconfig.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_machinepool.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_syncidentityprovider.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_syncset.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_syncsetinstance.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/generated_expansion.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/hive_client.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/hiveconfig.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/machinepool.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/syncidentityprovider.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/syncset.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/syncsetinstance.go
  vendor/k8s.io/client-go/discovery/fake/discovery.go
  vendor/k8s.io/code-generator/cmd/client-gen/args/args.go
  vendor/k8s.io/code-generator/cmd/client-gen/args/gvpackages.go
  vendor/k8s.io/code-generator/cmd/client-gen/args/gvtype.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/client_generator.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/fake/fake_client_generator.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/fake/generator_fake_for_clientset.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/fake/generator_fake_for_group.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/fake/generator_fake_for_type.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_clientset.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_expansion.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_group.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/generator_for_type.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/scheme/generator_for_scheme.go
  vendor/k8s.io/code-generator/cmd/client-gen/generators/util/tags.go
  vendor/k8s.io/code-generator/cmd/client-gen/main.go
  vendor/k8s.io/code-generator/cmd/client-gen/path/path.go
  vendor/k8s.io/code-generator/cmd/client-gen/types/helpers.go
  vendor/k8s.io/code-generator/cmd/client-gen/types/types.go
  vendor/k8s.io/code-generator/pkg/namer/tag-override.go
Labels: approved, lgtm, size/XXL

#762 New command to retrieve kubeadmin's password
  docs/using-hive.md
Labels: approved, lgtm, ok-to-test, size/XS

#758 Multi cloud dns management
  Gopkg.lock
  config/crds/hive_v1_hiveconfig.yaml
  contrib/pkg/adm/managedns/enable.go
  pkg/apis/hive/v1/dnszone_types.go
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/dnsendpoint/dnsendpoint_controller.go
  pkg/controller/dnsendpoint/dnsendpoint_controller_test.go
  pkg/controller/dnsendpoint/nameserver/gcp.go
  pkg/controller/dnsendpoint/nameserver/gcp_live_test.go
  pkg/gcpclient/client.go
  pkg/gcpclient/mock/client_generated.go
  pkg/manageddns/manageddns.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
  pkg/operator/hive/manageddns.go
  test/e2e/postdeploy/operator/operator_test.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/github.com/stretchr/testify/suite/suite.go
Labels: approved, lgtm, size/XXL
