Repository openshift/hive, pull requests merged in 2019-10, with the labels that each got.

#572 Update docs on using manageDNS with missing steps.
  docs/using-hive.md
Labels: approved, lgtm, size/M

#567 e2e tests for azure and gcp
  config/manager/deployment.yaml
  contrib/pkg/createcluster/azure.go
  contrib/pkg/createcluster/gcp.go
  hack/e2e-test.sh
  pkg/operator/assets/bindata.go
  test/e2e/postinstall/machinesets/infra_test.go
Labels: approved, lgtm, size/L

#574 accept a namespace to logextractor
  hack/logextractor.sh
Labels: approved, lgtm, size/M

#575 remove logging of install-config.yaml
  pkg/installmanager/installmanager.go
Labels: approved, lgtm, size/XS

#568 Add ability to stop sync to target clusters
  docs/annotations.md
  pkg/constants/constants.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
Labels: approved, lgtm, ok-to-test, size/M

#573 Add support for install retry cleanup of A records in managed DNSZones.
  pkg/awsclient/client.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/utils/sa.go
  pkg/controller/utils/utils.go
  pkg/installmanager/dnscleanup.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: approved, lgtm, size/L

#577 installmanager: wait-for install-complete after failed install
  pkg/installmanager/installmanager.go
Labels: approved, lgtm, size/M

#576 installmanager: gather logs reporting success with empty private ssh key file
  pkg/installmanager/installmanager.go
Labels: approved, lgtm, size/XS

#578 remove unnecessary warning about dnszone not getting deleted
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/M

#579 do not emit error on failure creating duplicate deprovision request
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/S

#580 installmanager: fix check for whether bootstrap is complete
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: approved, lgtm, size/M

#581 store e2e must-gather logs
  hack/e2e-test.sh
Labels: approved, lgtm, size/XS

#587 remove unnecessary warning about dnszone not getting deleted
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/M

#586 add validation for cert bundles in clusterdeployment
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
Labels: approved, lgtm, size/L

#588 controller: reduce severity of log for missing cert bundle secret
  pkg/controller/remoteingress/remoteingress_controller.go
Labels: approved, lgtm, size/XS

#571 Modifying admission validator names to make the plural names of CRDs to work
  config/hiveadmission/clusterdeployment-webhook.yaml
  config/hiveadmission/clusterimageset-webhook.yaml
  config/hiveadmission/dnszones-webhook.yaml
  config/hiveadmission/selectorsyncset-webhook.yaml
  config/hiveadmission/syncset-webhook.yaml
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterimageset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterimageset_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterprovision_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#590 Adding azure and gcp to the supported cloud platforms in readme
  README.md
Labels: approved, lgtm, size/XS

#591 controller: stop cd reconcile on missing clusterimageset
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/M

#593 Removing outdated ValidatingWebhookConfigurations
  pkg/operator/hive/hiveadmission.go
Labels: approved, lgtm, size/S

#582 webhook for clusterprovision validator
  config/hiveadmission/clusterprovision-webhook.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hiveadmission.go
Labels: approved, lgtm, size/L

#594 use info level for update conflicts
  Gopkg.lock
  kubeconfig
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/zonereconciler.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/unreachable/unreachable_controller.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
  pkg/controller/velerobackup/velerobackup_controller.go
  vendor/github.com/sirupsen/logrus/alt_exit.go
  vendor/github.com/sirupsen/logrus/entry.go
  vendor/github.com/sirupsen/logrus/exported.go
  vendor/github.com/sirupsen/logrus/json_formatter.go
  vendor/github.com/sirupsen/logrus/logger.go
  vendor/github.com/sirupsen/logrus/logrus.go
  vendor/github.com/sirupsen/logrus/terminal_check_bsd.go
  vendor/github.com/sirupsen/logrus/terminal_check_no_terminal.go
  vendor/github.com/sirupsen/logrus/terminal_check_notappengine.go
  vendor/github.com/sirupsen/logrus/terminal_check_solaris.go
  vendor/github.com/sirupsen/logrus/terminal_check_unix.go
  vendor/github.com/sirupsen/logrus/terminal_check_windows.go
  vendor/github.com/sirupsen/logrus/terminal_notwindows.go
  vendor/github.com/sirupsen/logrus/terminal_windows.go
  vendor/github.com/sirupsen/logrus/text_formatter.go
Labels: approved, lgtm, size/XL

#602 docs: operator is managing CRs but not CRDs.
  docs/architecture.md
Labels: approved, lgtm, ok-to-test, size/XS

#603 Update install log regexes configmap
  config/configmaps/install-log-regexes-configmap.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#608 go lang in pre-reqs
  docs/install.md
Labels: approved, lgtm, needs-ok-to-test, size/XS

#607 Remove sd_release.md
  docs/sd_release.md
Labels: approved, lgtm, size/L

#600 docs: updated some commands in syncset
  docs/syncset.md
Labels: approved, lgtm, ok-to-test, size/S

#612 Skip minor OpenShift specific assets when running on vanilla Kube.
  Makefile
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role_binding.yaml
  config/rbac/hive_reader_role_binding.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#583 controller: no error message on creation when already exists
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/dnszone/zonereconciler.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
Labels: approved, lgtm, size/S

#604 controllers: dummy provision for clusterdeployment with installed timestamp
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/M

#610 Add PersistentVolume in using hive section
  docs/using-hive.md
Labels: approved, lgtm, ok-to-test, size/XS

#614 controllers: improve variables and comments around updatePullSecretInfo
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/S

#615 controllers: do not compare hashes for merged pull secret
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/utils/secrets.go
  pkg/controller/utils/secrets_test.go
Labels: approved, lgtm, size/M

#597 controllers: simplify conds changed check in controlplanecerts
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
Labels: approved, lgtm, size/S

#624 Fix bootstrap log gathering on 4.2 by using openshift-install gather …
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: approved, lgtm, size/L

#611 docs: consolidate using hive
  docs/using-hive.md
Labels: approved, lgtm, ok-to-test, size/S

#621 Add cluster platform label to ClusterDeployment
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/M

#616 controllers: remove code for deleting legacy install jobs
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/generate.go
Labels: approved, lgtm, size/M

#617 controllers: remove code to set spec installed when legacy status installed set
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/S

#619 controllers: log NotFound errors at info level
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
Labels: approved, lgtm, size/M

#625 Add variant of kubefed's create-clusters.sh script.
  hack/create-clusters.sh
Labels: approved, lgtm, size/L

#627 docs: Delete support clouds section
  docs/architecture.md
Labels: approved, lgtm, ok-to-test, size/XS

#630 controllers: reduce level of some warnings in syncsetinstance controller
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
Labels: approved, lgtm, size/S

#633 docs: remove reference to hive image for clusterdeployment
  docs/using-hive.md
Labels: approved, lgtm, size/XS

#636 Adding a log when we change the platform label
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/XS

#637 Adding staebler to the Owners file
  OWNERS
Labels: approved, lgtm, size/XS

#629 controllers: remove dead code in syncsetinstance controller
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
Labels: approved, lgtm, size/XS

#632 Add ClusterImageSet example
  docs/using-hive.md
Labels: approved, lgtm, ok-to-test, size/S

#613 Manage DNS E2E
  contrib/cmd/hiveutil/main.go
  contrib/pkg/adm/adm.go
  contrib/pkg/adm/managedns/enable.go
  contrib/pkg/adm/managedns/managedns.go
  contrib/pkg/createcluster/aws.go
  contrib/pkg/createcluster/create.go
  contrib/pkg/utils/aws/aws.go
  hack/e2e-test.sh
Labels: approved, lgtm, size/L

#620 controllers: ensure all status update of clusterdeployment have valid clusterversion
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/utils/clientwrapper.go
  pkg/controller/utils/utils.go
Labels: approved, lgtm, size/M

#606 Cleanup syncset secretreference secrets when ResourceApplyMode==Sync
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
Labels: approved, lgtm, size/L

#639 Fix error in operator logs watching DeploymentConfigs.
  config/operator/operator_role.yaml
Labels: approved, lgtm, size/XS

#641 remove stray kubeconfig from testing
  kubeconfig
Labels: approved, lgtm, size/S

#647 controllers: ensure valid cd status for imageset jobs
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/S

#645 fix resync
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
Labels: approved, lgtm, size/XS
