Repository openshift/hive, pull requests merged in 2019-08, with the labels that each got.

#484 Add velero backup option to HiveConfig
  Makefile
  config/crds/hive_v1alpha1_hiveconfig.yaml
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/add_velerobackup.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/L

#487 Changing retry log to warning for ingress certficate bundle
  pkg/controller/remoteingress/remoteingress_controller.go
Labels: approved, lgtm, size/XS

#488 Fix long delays to install after generating global pull secret.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/XS

#479 Gather Cluster Logs on Install Failure
  Dockerfile
  Dockerfile.dev
  Makefile
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/crds/hive_v1alpha1_hiveconfig.yaml
  config/rbac/manager_role.yaml
  contrib/pkg/createcluster/create.go
  docs/developing.md
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/metrics/metrics.go
  pkg/imageset/generate.go
  pkg/imageset/updateinstaller.go
  pkg/imageset/updateinstaller_test.go
  pkg/install/generate.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/XL

#492 Temporary syncsetinstance hot loop fix.
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
Labels: approved, lgtm, size/S

#493 Use latest hive image for processing image resolution job.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/imageset/generate.go
Labels: approved, lgtm, size/S

#495 set OPENSHIFT_INSTALL_INVOKER when launching install
  pkg/install/generate.go
Labels: approved, lgtm, size/XS

#494 Making pull secret file and environment variable optional for hiveutil
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm, size/M

#498 Fixing deadcode as per golangci lint issues
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/dnszone/test_helpers.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller_test.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/controller/utils/utils.go
  pkg/imageset/generate_test.go
  pkg/install/convertconfig_test.go
  pkg/installmanager/installmanager_test.go
  pkg/operator/util/apply.go
Labels: approved, lgtm, size/L

#500 Run generate bydefult before verify
  Makefile
Labels: approved, lgtm, size/XS

#499 Add script to extract cluster logs from PVC after failures.
  docs/troubleshooting.md
  docs/using-hive.md
  hack/logextractor.sh
Labels: approved, lgtm, size/M

#497 Fixing spelling mistakes as part for golangci lint fixes
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/crds/hive_v1alpha1_selectorsyncset.yaml
  config/crds/hive_v1alpha1_syncset.yaml
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/dnszone_types.go
  pkg/apis/hive/v1alpha1/machinepools.go
  pkg/apis/hive/v1alpha1/syncset_types.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterimageset_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook_test.go
  pkg/controller/metrics/metrics.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/controller/velerobackup/clusterdeployment_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#502 semver complains if the prerelease first char is a 0
  hack/app_sre_create_image_catalog.sh
  hack/generate-operator-bundle.py
Labels: approved, lgtm, size/XS

#501 Certificate utility
  contrib/cmd/hiveutil/main.go
  contrib/pkg/certificate/command.go
  contrib/pkg/certificate/create.go
  contrib/pkg/certificate/hook.go
  contrib/pkg/createcluster/create.go
  docs/developing.md
  hack/set-additional-ca.sh
  pkg/awsclient/client.go
  pkg/awsclient/mock/client_generated.go
Labels: approved, lgtm, size/L

#503 Force reloading of APIServer on certs change
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
Labels: approved, lgtm, size/M

#505 cert util: change copied cert from cert.pem to fullchain.pem
  contrib/pkg/certificate/create.go
Labels: approved, lgtm, size/XS

#506 hive-frontend add events to role
  config/rbac/hive_frontend_role.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#507 Fix typo in operator role for syncset admission controller
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#508 Use Infof instead of Info when formatting needed
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
Labels: approved, lgtm, size/XS

#509 wrapping around event handler that adds logging
  pkg/controller/utils/loggingeventhandler.go
Labels: approved, lgtm, size/L

#496 Adding quick start documentation
  README.md
  docs/developing.md
  docs/quick_start.md
Labels: approved, lgtm, size/M

#504 Report target clusteroperator status
  config/crds/hive_v1alpha1_clusterstate.yaml
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role.yaml
  config/rbac/hive_frontend_role.yaml
  config/rbac/hive_reader_role.yaml
  config/rbac/manager_role.yaml
  pkg/apis/hive/v1alpha1/clusterstate_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_clusterstate.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/clusterstate/clusterstate_controller_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XXL

#490 Use the updated global pull secret from hive config
  cmd/manager/main.go
  cmd/operator/main.go
  pkg/constants/constants.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/installlogmonitor/installlogmonitor_controller.go
  pkg/controller/installlogmonitor/installlogmonitor_controller_test.go
  pkg/operator/hive/hive.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
Labels: approved, lgtm, size/L

#511 unit test improvments for TestMergePullSecrets
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/S

#489 Create Velero backup object on syncset change
  .gitignore
  config/rbac/manager_role.yaml
  pkg/controller/test/clusterdeployment/clusterdeployment.go
  pkg/controller/velerobackup/clusterdeployment.go
  pkg/controller/velerobackup/clusterdeployment_test.go
  pkg/controller/velerobackup/helpers_test.go
  pkg/controller/velerobackup/hiveobject.go
  pkg/controller/velerobackup/hiveobject_test.go
  pkg/controller/velerobackup/velerobackup_controller.go
  pkg/controller/velerobackup/velerobackup_controller_test.go
  pkg/operator/assets/bindata.go
  pkg/test/clusterdeployment/clusterdeployment.go
  pkg/test/generic/generic.go
  pkg/test/syncset/syncset.go
Labels: approved, lgtm, size/XXL

#510 Update makefile to run golangci lint bydefault
  Makefile
  golangci.yml
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterimageset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/dnszone_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/selector_syncset_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/syncset_validating_admission_hook.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/controller/utils/secrets_test.go
  pkg/controller/velerobackup/helpers_test.go
  pkg/controller/velerobackup/velerobackup_controller_test.go
  pkg/operator/hive/hive_controller.go
Labels: approved, lgtm, size/L

#482 ClusterProvision
  cmd/hiveadmission/main.go
  config/configmaps/install-log-regexes-configmap.yaml
  config/crds/hive_v1alpha1_clusterdeployment.yaml
  config/crds/hive_v1alpha1_clusterimageset.yaml
  config/crds/hive_v1alpha1_clusterprovision.yaml
  config/operator/01_clusterimageset_crd.yaml
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role.yaml
  config/rbac/hive_frontend_role.yaml
  config/rbac/hive_reader_role.yaml
  config/rbac/manager_role.yaml
  config/samples/hive_v1alpha1_clusterimageset.yaml
  config/templates/cluster-deployment-customimageset.yaml
  config/templates/cluster-deployment.yaml
  contrib/cmd/waitforjob/main.go
  contrib/pkg/createcluster/create.go
  docs/using-hive.md
  hack/e2e-test.sh
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/clusterimageset_types.go
  pkg/apis/hive/v1alpha1/clusterprovision_types.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterprovision_validating_admission_hook.go
  pkg/apis/hive/v1alpha1/validating-webhooks/clusterprovision_validating_admission_hook_test.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/add_clusterprovision.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller.go
  pkg/controller/clusterdeprovisionrequest/clusterdeprovisionrequest_controller_test.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller_test.go
  pkg/controller/clusterprovision/installlogmonitor.go
  pkg/controller/clusterprovision/installlogmonitor_test.go
  pkg/controller/clusterprovision/installlogregex.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/images/controller_images.go
  pkg/controller/installlogmonitor/installlogmonitor_controller.go
  pkg/controller/installlogmonitor/installlogmonitor_controller_test.go
  pkg/controller/installlogmonitor/installlogregex.go
  pkg/controller/metrics/metrics.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/controller/utils/conditions.go
  pkg/controller/utils/sa.go
  pkg/controller/utils/sa_test.go
  pkg/imageset/generate.go
  pkg/imageset/generate_test.go
  pkg/install/convertconfig_test.go
  pkg/install/generate.go
  pkg/install/generate_test.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
Labels: approved, lgtm, size/XXL

#517 vendor updated installer
  Gopkg.lock
  Gopkg.toml
  vendor/github.com/openshift/installer/pkg/asset/machines/aws/machinesets.go
  vendor/github.com/openshift/installer/pkg/destroy/aws/aws.go
  vendor/github.com/openshift/installer/pkg/types/aws/platform.go
  vendor/github.com/openshift/installer/pkg/types/azure/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/doc.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/machinepool.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/metadata.go
  vendor/github.com/openshift/installer/pkg/types/baremetal/platform.go
  vendor/github.com/openshift/installer/pkg/types/clustermetadata.go
  vendor/github.com/openshift/installer/pkg/types/gcp/clouduid.go
  vendor/github.com/openshift/installer/pkg/types/gcp/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/gcp/metadata.go
  vendor/github.com/openshift/installer/pkg/types/installconfig.go
  vendor/github.com/openshift/installer/pkg/types/machinepools.go
  vendor/github.com/openshift/installer/pkg/types/openstack/platform.go
Labels: approved, lgtm, size/L

#516 Add ssh-agent to hive container for log gathering.
  Dockerfile
  Dockerfile.dev
Labels: approved, lgtm, size/S

#518 fix clusterprovision creation race
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeployment/provisionexpectations.go
  pkg/controller/utils/expectations.go
  pkg/controller/utils/expectations_test.go
Labels: approved, lgtm, size/L

#519 remove migration of wildcard ingress domains
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L
