Repository openshift/hive, pull requests merged in 2020-12, with the labels that each got.

#1215 Update scaletest readme with notes on HiveConfig and fake applies.
  hack/scaletest/README.md
Labels: approved, lgtm

#1191 Add dev prometheus config for scraping multiple pods.
  config/prometheus/prometheus-configmap.yaml
  config/prometheus/prometheus-deployment-with-pvc.yaml
  config/prometheus/prometheus-deployment.yaml
Labels: approved, lgtm

#1217 Improve ClusterClaim Wait Experience
  config/crds/hive.openshift.io_clusterclaims.yaml
  pkg/apis/hive/v1/clusterclaim_types.go
  pkg/controller/clusterclaim/clusterclaim_controller.go
  pkg/controller/clusterclaim/clusterclaim_controller_test.go
  pkg/controller/utils/conditions.go
Labels: approved, lgtm

#1210 Implement horizontal scaling of clustersync
  Makefile
  config/clustersync/service.yaml
  config/clustersync/statefulset.yaml
  config/controllers/hive_controllers_role.yaml
  config/crds/hive.openshift.io_hiveconfigs.yaml
  config/operator/operator_role.yaml
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/clustersync/clustersync_controller_test.go
  pkg/controller/metrics/metrics.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/utils/clusterdeployment.go
  pkg/controller/utils/clusterdeployment_test.go
  pkg/controller/utils/statefulset.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/clustersync.go
  pkg/operator/hive/controllersconfig.go
  pkg/operator/hive/hive.go
  pkg/operator/hive/hive_controller.go
  pkg/test/statefulset/statefulset.go
Labels: approved, lgtm

#1219 clusterpool: ensure clusterdeployments namespace has same rbac as cluster-pool-admin
  config/controllers/hive_controllers_role.yaml
  config/rbac/hive_clusterpool_admin.yaml
  docs/clusterpools.md
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/controller/clusterpool/clusterpool_controller_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm

#1186 vsphere creds checking
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/constants/constants.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/metrics/provision_underway_collector.go
  pkg/controller/utils/credentials.go
Labels: approved, lgtm

#1221 Add FAILED_PROVISION_CONFIG param to hivconfig template.
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#1223 clusterpool: allow setting max size and max concurrent actions
  config/crds/hive.openshift.io_clusterpools.yaml
  pkg/apis/hive/v1/clusterpool_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/controller/clusterpool/clusterpool_controller_test.go
  pkg/controller/utils/conditions.go
  pkg/test/clusterpool/clusterpool.go
Labels: approved, lgtm

#1224 Add ClusterPool.Spec.HibernateAfter.
  config/crds/hive.openshift.io_clusterpools.yaml
  contrib/pkg/clusterpool/clusterpool.go
  pkg/apis/hive/v1/clusterpool_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterpool/clusterpool_controller.go
Labels: approved, lgtm

#1189 Store install logs in s3 compatible storage
  config/crds/hive.openshift.io_hiveconfigs.yaml
  docs/troubleshooting.md
  hack/logextractor.sh
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/awsclient/client.go
  pkg/awsclient/mock/client_generated.go
  pkg/constants/constants.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/install/generate.go
  pkg/install/generate_test.go
  pkg/installmanager/helper_test.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
  pkg/installmanager/loguploaderactuator.go
  pkg/installmanager/s3loguploaderactuator.go
  pkg/installmanager/s3loguploaderactuator_test.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm

#1226 Add note for Office Hours
  README.md
Labels: approved, lgtm

#1225 OpenStackClusterDeprovision: fix optional certficate field marshalling
  pkg/apis/hive/v1/clusterdeprovision_types.go
Labels: approved, lgtm

#885 docs: proposal for inter-cluster moves
  docs/move_clusters.md
Labels: approved, lgtm, lifecycle/rotten, size/M

#1214 initial support for installconfigtemplate in clusterpool
  config/crds/hive.openshift.io_clusterpools.yaml
  docs/clusterpools.md
  pkg/apis/hive/v1/clusterpool_types.go
  pkg/clusterresource/builder.go
  pkg/clusterresource/builder_test.go
  pkg/clusterresource/installconfigtemplate.go
  pkg/clusterresource/installconfigtemplate_test.go
  pkg/controller/clusterpool/clusterpool_controller.go
Labels: approved, lgtm, needs-ok-to-test

#1230 Omit clusterpool's installConfigSecretTemplateRef field when empty
  pkg/apis/hive/v1/clusterpool_types.go
Labels: approved, lgtm

#1232 Change hive-clustersync sts labels to match others
  config/clustersync/service.yaml
  config/clustersync/statefulset.yaml
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm

#1233 Add documentation for time-based scaling of clusterpool
  docs/clusterpools.md
Labels: approved, lgtm

#1231 [DOC] Replace SyncsetInstance with ClusterSync in troubleshooting
  docs/syncset.md
Labels: approved, lgtm

#1229 clusterpool: include deleting claimed clusters for max concurrent
  config/crds/hive.openshift.io_clusterpools.yaml
  pkg/apis/hive/v1/clusterpool_types.go
  pkg/constants/constants.go
  pkg/controller/clusterclaim/clusterclaim_controller.go
  pkg/controller/clusterclaim/clusterclaim_controller_test.go
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/controller/clusterpool/clusterpool_controller_test.go
  pkg/controller/clusterpoolnamespace/clusterpoolnamespace_controller.go
  pkg/controller/clusterpoolnamespace/clusterpoolnamespace_controller_test.go
  pkg/controller/utils/clusterclaim.go
Labels: approved, lgtm
