Repository openshift/hive, pull requests merged in 2020-08, with the labels that each got.

#1064 use full GCP machineset names in OpenShift 4.4.7
  pkg/controller/remotemachineset/gcpactuator.go
  pkg/controller/remotemachineset/gcpactuator_test.go
Labels: approved, lgtm

#1074 fix bug in hack/generate-operator-bundle-operatorhub.py
  hack/generate-operator-bundle-operatorhub.py
Labels: approved, lgtm

#1065 assign clusters to clusterclaims
  cmd/manager/main.go
  config/crds/hive.openshift.io_clusterclaims.yaml
  config/crds/hive.openshift.io_clusterdeployments.yaml
  pkg/apis/hive/v1/clusterclaim_types.go
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/hive/v1/clusterclaim.go
  pkg/client/clientset/versioned/typed/hive/v1/fake/fake_clusterclaim.go
  pkg/client/clientset/versioned/typed/hive/v1/fake/fake_hive_client.go
  pkg/client/clientset/versioned/typed/hive/v1/generated_expansion.go
  pkg/client/clientset/versioned/typed/hive/v1/hive_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/hive/v1/clusterclaim.go
  pkg/client/informers/externalversions/hive/v1/interface.go
  pkg/client/listers/hive/v1/clusterclaim.go
  pkg/client/listers/hive/v1/expansion_generated.go
  pkg/controller/clusterclaim/clusterclaim_controller.go
  pkg/controller/clusterclaim/clusterclaim_controller_test.go
  pkg/controller/clusterpool/clusterdeploymentexpectations.go
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/controller/clusterpool/clusterpool_controller_test.go
  pkg/controller/utils/conditions.go
  pkg/test/clusterclaim/clusterclaim.go
  pkg/test/clusterdeployment/clusterdeployment.go
  pkg/test/clusterpool/clusterpool.go
Labels: approved, lgtm

#1062 Fix insufficient credentials condition on ClusterDeployment
  pkg/controller/dnszone/awsactuator.go
  pkg/controller/dnszone/awsactuator_test.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/dnszone_controller_test.go
Labels: approved, lgtm

#1075 add deleteProtection parameter to hiveconfig in olm template
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#1077 hiveutil: print validation error for create-cluster
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm

#1072 Add memory request to provisioning pod.
  pkg/install/generate.go
  pkg/install/generate_test.go
Labels: approved, lgtm

#1070 Scale testing improvements
  cmd/manager/main.go
  config/controllers/service.yaml
  config/hiveadmission/deployment.yaml
  config/hiveadmission/service.yaml
  config/prometheus/prometheus-deployment-with-pvc.yaml
  contrib/pkg/createcluster/create.go
  docs/developing.md
  hack/create-kind-podman-cluster.sh
  hack/scaletest/README.md
  hack/scaletest/setup-selectorsyncsets.sh
  hack/scaletest/syncset-template.yaml
  hack/scaletest/test_setup.sh
  pkg/clusterresource/builder.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm

#1068 create RBAC for accessing claimed cluster
  config/crds/hive.openshift.io_clusterclaims.yaml
  pkg/apis/hive/v1/clusterclaim_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterclaim/clusterclaim_controller.go
  pkg/controller/clusterclaim/clusterclaim_controller_test.go
  pkg/installmanager/installmanager.go
  pkg/operator/hive/hiveapi.go
  pkg/resource/delete.go
  pkg/test/clusterclaim/clusterclaim.go
Labels: approved, lgtm

#1069 hibernate clusters created for ClusterPool
  pkg/controller/clusterclaim/clusterclaim_controller.go
  pkg/controller/clusterclaim/clusterclaim_controller_test.go
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/controller/clusterpool/clusterpool_controller_test.go
  pkg/test/clusterdeployment/clusterdeployment.go
Labels: approved, lgtm

#1080 use image pull policy IfNotPresent for OpenShift images
  pkg/imageset/generate.go
  pkg/install/generate.go
Labels: approved, lgtm

#1046 Add option for machinepool to create Spot MachineSets
  config/crds/hive.openshift.io_machinepools.yaml
  pkg/apis/hive/v1/aws/machinepool.go
  pkg/apis/hive/v1/aws/zz_generated.deepcopy.go
  pkg/controller/remotemachineset/awsactuator.go
Labels: approved, lgtm, ok-to-test

#1078 validation: base domain that is a managed domain
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
Labels: approved, lgtm

#1079 clear ClusterImageSetNotFound condition when imageset exists
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm

#1082 Hibernation: set condition when failing to stop/start
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/hibernation/hibernation_controller_test.go
Labels: approved, lgtm

#1087 test/integration/resource: fix dropped test errors
  test/integration/resource/apply_test.go
  test/integration/resource/createonly_test.go
  test/integration/resource/createupdate_test.go
Labels: approved, lgtm, ok-to-test

#1086 Add velero namespace config variable
  config/crds/hive.openshift.io_hiveconfigs.yaml
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/constants/constants.go
  pkg/controller/velerobackup/helpers_test.go
  pkg/controller/velerobackup/velerobackup_controller.go
  pkg/controller/velerobackup/velerobackup_controller_test.go
  pkg/operator/hive/hive.go
  pkg/test/manager/manager.go
  pkg/test/manager/mock/manager_generated.go
Labels: approved, lgtm

#1085 Add buildconfig manifests and instructions
  config/buildconfig/hive-buildconfig.yaml
  config/buildconfig/hive-imagestream.yaml
  config/buildconfig/imagestream-rbac.yaml
  docs/buildconfig.md
Labels: approved, lgtm

#1063 Detect install pod stuck in pending phase
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/clusterprovision_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller_test.go
Labels: approved, lgtm

#1088 expose hiveAPIEnabled in hiveconfig template
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, do-not-merge/hold, lgtm

#1095 Revert "expose hiveAPIEnabled in hiveconfig template"
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#1094 test/e2e/destroycluster: fix dropped errors
  test/e2e/destroycluster/destroy_test.go
Labels: approved, lgtm, ok-to-test

#1097 Fix metrics crash on new InstallLaunchError condition.
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/controller/metrics/metrics.go
  pkg/controller/metrics/metrics_test.go
Labels: approved, lgtm

#1098 pick one DNS cleanup codepath and use it everywhere
  pkg/controller/dnszone/awsactuator.go
  pkg/installmanager/dnscleanup.go
  pkg/installmanager/installmanager.go
Labels: approved, lgtm

#1101 Revert "pick one DNS cleanup codepath and use it everywhere"
  pkg/controller/dnszone/awsactuator.go
  pkg/installmanager/dnscleanup.go
  pkg/installmanager/installmanager.go
Labels: approved, lgtm

#1103 additional-trust-bundle support added to hiveutil
  contrib/pkg/createcluster/create.go
  pkg/clusterresource/builder.go
Labels: approved, lgtm, ok-to-test

#1105 Small fixes for issues found in the unreachable hotloop investigation
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/remoteclient/remoteclient.go
Labels: approved, lgtm
