Repository openshift/hive, pull requests merged in 2020-03, with the labels that each got.

#865 Remove installmanager debugging.
  pkg/installmanager/installmanager.go
Labels: approved, lgtm, size/XS

#861 add support for machinepools on azure
  Gopkg.lock
  Gopkg.toml
  pkg/azureclient/client.go
  pkg/azureclient/mock/client_generated.go
  pkg/constants/constants.go
  pkg/controller/remotemachineset/azureactuator.go
  pkg/controller/remotemachineset/azureactuator_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  test/e2e/postinstall/machinesets/infra_test.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/availabilitysets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/client.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/containerservices.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/disks.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleries.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleryimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/galleryimageversions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/images.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/loganalytics.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/models.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/operations.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/proximityplacementgroups.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/resourceskus.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/snapshots.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/usage.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/version.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineextensionimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineimages.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachineruncommands.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachines.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetextensions.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetrollingupgrades.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesets.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinescalesetvms.go
  vendor/github.com/Azure/azure-sdk-for-go/services/compute/mgmt/2018-10-01/compute/virtualmachinesizes.go
  vendor/github.com/openshift/installer/pkg/asset/machines/azure/machines.go
  vendor/github.com/openshift/installer/pkg/asset/machines/azure/machinesets.go
  vendor/github.com/openshift/installer/pkg/asset/machines/azure/zones.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/LICENSE
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderconfig_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/azuremachineproviderstatus_types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/doc.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/register.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/types.go
  vendor/sigs.k8s.io/cluster-api-provider-azure/pkg/apis/azureprovider/v1beta1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/XXL

#863 migration: make speed improvements
  contrib/pkg/v1migration/deleteobjects.go
  contrib/pkg/v1migration/discoverowned.go
  contrib/pkg/v1migration/recreateobjects.go
  contrib/pkg/v1migration/ref.go
  contrib/pkg/v1migration/restoreownerrefs.go
  contrib/pkg/v1migration/saveownerrefs.go
  contrib/pkg/v1migration/v1migration.go
  hack/v1migration/README.md
  hack/v1migration/delete.sh
  hack/v1migration/delete_hive_jobs.sh
  hack/v1migration/hivetypes.sh
  hack/v1migration/restore.sh
  hack/v1migration/save.sh
Labels: approved, lgtm, size/XL

#869 Remove support for BareMetal MachinePools.
  config/crds/hive_v1_machinepool.yaml
  pkg/apis/hive/v1/baremetal/machinepool.go
  pkg/apis/hive/v1/baremetal/machinepools.go
  pkg/apis/hive/v1/baremetal/zz_generated.deepcopy.go
  pkg/apis/hive/v1/machinepool_types.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#867 Fix for v1 migration.
  hack/v1migration/delete_hive_jobs.sh
Labels: approved, lgtm, size/XS

#873 don't run the env var, just evaluate it
  build/build-image/Dockerfile
Labels: approved, lgtm, size/XS

#872 migration: add certificaterequests to owner refs to save
  contrib/pkg/v1migration/saveownerrefs.go
Labels: approved, lgtm, size/XS

#843 ensure hive puts a domain into the apiserver object
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
Labels: approved, lgtm, size/L

#871 Add install failure debugging annotations.
  pkg/constants/constants.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: approved, lgtm, size/M

#874 validation: allow 0 for aws machinepool iops and size
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
Labels: approved, lgtm, size/S

#782 GCP Multi-MachinePool support with single character leases.
  cmd/manager/main.go
  config/crds/hive_v1_machinepoolnamelease.yaml
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role.yaml
  config/rbac/hive_controllers_role.yaml
  pkg/apis/hive/v1/machinepoolnamelease_types.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_hive_client.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_machinepoolnamelease.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/generated_expansion.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/hive_client.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/machinepoolnamelease.go
  pkg/constants/constants.go
  pkg/controller/remotemachineset/actuator.go
  pkg/controller/remotemachineset/awsactuator.go
  pkg/controller/remotemachineset/awsactuator_test.go
  pkg/controller/remotemachineset/azureactuator.go
  pkg/controller/remotemachineset/azureactuator_test.go
  pkg/controller/remotemachineset/gcpactuator.go
  pkg/controller/remotemachineset/gcpactuator_test.go
  pkg/controller/remotemachineset/leaseexceptions.go
  pkg/controller/remotemachineset/mock/actuator_generated.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/operator/assets/bindata.go
  test/e2e/common/machinepoolnamelease.go
  test/e2e/postinstall/machinesets/infra_test.go
Labels: approved, lgtm, size/XXL

#877 Add HiveConfig.Spec.DeprovisionsDisabled.
  config/crds/hive_v1_hiveconfig.yaml
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#870 Add note about ssh key format to docs.
  docs/using-hive.md
Labels: approved, lgtm, size/XS

#876 migration: remove initial fetch from delete process
  contrib/pkg/v1migration/deleteobjects.go
  hack/v1migration/delete.sh
Labels: approved, lgtm, size/M

#879 migration: process for fixing bad restores mid-migration
  contrib/pkg/v1migration/saveownerrefs.go
  hack/v1migration/README.md
  hack/v1migration/delete_in_namespace.sh
  hack/v1migration/hive_owner_refs_in_namespace.sh
  hack/v1migration/hive_resources_in_namespace.sh
  hack/v1migration/hivetypes.sh
  hack/v1migration/save.sh
  hack/v1migration/validate.sh
  pkg/hive/apiserver/registry/clusterdeployment/proxy.go
Labels: approved, lgtm, size/L

#866 Set region label on Clusterdeployment CR
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/M

#882 update cleanupLogOutput to handle malformed data from libvirt and ssh
  config/configmaps/install-log-regexes-configmap.yaml
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#883 Fix crash when using more than 35 GCP MachinePools.
  docs/using-hive.md
  pkg/apis/hive/v1/machinepool_types.go
  pkg/controller/remotemachineset/gcpactuator.go
  pkg/controller/remotemachineset/gcpactuator_test.go
  pkg/controller/remotemachineset/leaseexceptions.go
Labels: approved, lgtm, size/L

#888 apiserver: omit empty serviceNetwork and machineNetwork from installconfig
  pkg/hive/apiserver/registry/util/convert.go
Labels: approved, lgtm

#887 OLM artifacts: switch managed dns config to an array
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#890 OLM artifacts: use empty array for MANAGED_DOMAINS default
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm

#891 modify openshift detection logic
  pkg/operator/hive/hive.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
  pkg/operator/hive/hiveapi.go
Labels: approved, lgtm

#892 add config setting for cli image
  config/crds/hive_v1_hiveconfig.yaml
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm

#895 Improved clearing of provision/deprovision underway metrics.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/metrics/metrics.go
Labels: approved, lgtm

#880 Refactor hiveutil create-cluster code into a package.
  config/templates/cluster-deployment-customimageset.yaml
  config/templates/cluster-deployment.yaml
  contrib/pkg/createcluster/create.go
  pkg/clusterresource/aws.go
  pkg/clusterresource/azure.go
  pkg/clusterresource/builder.go
  pkg/clusterresource/builder_test.go
  pkg/clusterresource/gcp.go
  pkg/constants/constants.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
  pkg/install/generate.go
Labels: approved, lgtm, size/XXL

#898 Fix case on bare metal platform to match openshift-install.
  config/crds/hive_v1_clusterdeployment.yaml
  docs/using-hive.md
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/operator/assets/bindata.go
Labels: approved

#899 operator bundle 1.0.0
  bundle/1.0.0/hive-operator.v1.0.0.clusterserviceversion.yaml
  bundle/1.0.0/hive_v1_checkpoint.yaml
  bundle/1.0.0/hive_v1_clusterdeployment.yaml
  bundle/1.0.0/hive_v1_clusterdeprovision.yaml
  bundle/1.0.0/hive_v1_clusterimageset.yaml
  bundle/1.0.0/hive_v1_clusterprovision.yaml
  bundle/1.0.0/hive_v1_clusterstate.yaml
  bundle/1.0.0/hive_v1_dnszone.yaml
  bundle/1.0.0/hive_v1_hiveconfig.yaml
  bundle/1.0.0/hive_v1_machinepool.yaml
  bundle/1.0.0/hive_v1_machinepoolnamelease.yaml
  bundle/1.0.0/hive_v1_selectorsyncidentityprovider.yaml
  bundle/1.0.0/hive_v1_selectorsyncset.yaml
  bundle/1.0.0/hive_v1_syncidentityprovider.yaml
  bundle/1.0.0/hive_v1_syncset.yaml
  bundle/1.0.0/hive_v1_syncsetinstance.yaml
  bundle/hive-package.yaml
  version.txt
Labels: approved, lgtm

#901 admission: use kube decoder instead of go json unmarshal
  cmd/hiveadmission/main.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/clusterimageset_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterimageset_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/clusterprovision_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/clusterprovision_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/decoder_test.go
  pkg/apis/hive/v1/validating-webhooks/dnszone_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/dnszone_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook_test.go
Labels: approved, lgtm

#900 Dynamically apply all hive CRDs from the operator.
  pkg/operator/hive/hive.go
Labels: approved, lgtm

#894 Validate SyncSet ResourceApplyMode
  config/crds/hive_v1_selectorsyncset.yaml
  config/crds/hive_v1_syncset.yaml
  pkg/apis/hive/v1/syncset_types.go
  pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook_test.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm

#903 Modified the Deployment version in e2e test postinstall file
  test/e2e/postinstall/machinesets/infra_test.go
Labels: approved, lgtm

#904 Update ResourceApplyMode for remoteingress
  config/crds/hive_v1_syncsetinstance.yaml
  pkg/apis/hive/v1/syncsetinstance_types.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/hive/apis/hive/syncset_types.go
  pkg/hive/apis/hive/syncsetinstance_types.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm

#896 imageset: do not use oc adm to get installer and cli images
  Gopkg.lock
  config/crds/hive_v1_hiveconfig.yaml
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/images/controller_images.go
  pkg/imageset/generate.go
  pkg/imageset/generate_test.go
  pkg/imageset/updateinstaller.go
  pkg/imageset/updateinstaller_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
  vendor/github.com/openshift/api/image/docker10/doc.go
  vendor/github.com/openshift/api/image/docker10/dockertypes.go
  vendor/github.com/openshift/api/image/docker10/register.go
  vendor/github.com/openshift/api/image/docker10/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/doc.go
  vendor/github.com/openshift/api/image/dockerpre012/dockertypes.go
  vendor/github.com/openshift/api/image/dockerpre012/register.go
  vendor/github.com/openshift/api/image/dockerpre012/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/consts.go
  vendor/github.com/openshift/api/image/v1/doc.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/legacy.go
  vendor/github.com/openshift/api/image/v1/register.go
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm

#905 rename bundle package filename per operatorhub team request
  bundle/hive.package.yaml
Labels: approved, lgtm

#908 cherry-pick #896 to OCM 4.4.0
  Gopkg.lock
  config/crds/hive_v1_hiveconfig.yaml
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/images/controller_images.go
  pkg/imageset/generate.go
  pkg/imageset/generate_test.go
  pkg/imageset/updateinstaller.go
  pkg/imageset/updateinstaller_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
  vendor/github.com/openshift/api/image/docker10/doc.go
  vendor/github.com/openshift/api/image/docker10/dockertypes.go
  vendor/github.com/openshift/api/image/docker10/register.go
  vendor/github.com/openshift/api/image/docker10/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/deepcopy.go
  vendor/github.com/openshift/api/image/dockerpre012/doc.go
  vendor/github.com/openshift/api/image/dockerpre012/dockertypes.go
  vendor/github.com/openshift/api/image/dockerpre012/register.go
  vendor/github.com/openshift/api/image/dockerpre012/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/consts.go
  vendor/github.com/openshift/api/image/v1/doc.go
  vendor/github.com/openshift/api/image/v1/generated.pb.go
  vendor/github.com/openshift/api/image/v1/legacy.go
  vendor/github.com/openshift/api/image/v1/register.go
  vendor/github.com/openshift/api/image/v1/types.go
  vendor/github.com/openshift/api/image/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/api/image/v1/zz_generated.swagger_doc_generated.go
Labels: approved, lgtm
