Repository openshift/hive, pull requests merged in 2020-01, with the labels that each got.

#749 types: remove DefaultMachinePlatform
  config/crds/hive_v1_clusterdeployment.yaml
  pkg/apis/hive/v1/aws/platform.go
  pkg/apis/hive/v1/aws/zz_generated.deepcopy.go
  pkg/apis/hive/v1/azure/platform.go
  pkg/apis/hive/v1/azure/zz_generated.deepcopy.go
  pkg/apis/hive/v1/gcp/platform.go
  pkg/apis/hive/v1/gcp/zz_generated.deepcopy.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#751 make logger field names consistent in dnszone aws actuator
  pkg/controller/dnszone/awsactuator.go
Labels: approved, lgtm, size/S

#764 add selector types to generated client
  pkg/apis/hive/v1/syncidentityprovider_types.go
  pkg/apis/hive/v1/syncset_types.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_hive_client.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_selectorsyncidentityprovider.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/fake/fake_selectorsyncset.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/generated_expansion.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/hive_client.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/selectorsyncidentityprovider.go
  pkg/client/clientset-generated/clientset/typed/hive/v1/selectorsyncset.go
Labels: approved, lgtm, size/XL

#769 apiserver: updating existing object when converting
  pkg/hive/apis/hive/hiveconversion/conversion.go
  pkg/hive/apiserver/registry/checkpoint/proxy.go
  pkg/hive/apiserver/registry/clusterdeployment/proxy.go
  pkg/hive/apiserver/registry/clusterdeprovisionrequest/proxy.go
  pkg/hive/apiserver/registry/clusterimageset/proxy.go
  pkg/hive/apiserver/registry/clusterprovision/proxy.go
  pkg/hive/apiserver/registry/clusterstate/proxy.go
  pkg/hive/apiserver/registry/dnszone/proxy.go
  pkg/hive/apiserver/registry/hiveconfig/proxy.go
  pkg/hive/apiserver/registry/selectorsyncidentityprovider/proxy.go
  pkg/hive/apiserver/registry/selectorsyncset/proxy.go
  pkg/hive/apiserver/registry/syncidentityprovider/proxy.go
  pkg/hive/apiserver/registry/syncset/proxy.go
  pkg/hive/apiserver/registry/syncsetinstance/proxy.go
  pkg/hive/apiserver/registry/util/convert.go
Labels: approved, lgtm, size/XXL

#750 validation: reject machinepool with pool name of master
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
Labels: approved, lgtm, size/S

#773 apiserver: block v1alpha1 hiveconfig updates when multiple managed domains
  pkg/hive/apis/hive/hiveconversion/conversion.go
Labels: approved, lgtm, size/S

#778 Update Sync resourceApplyMode description.
  docs/syncset.md
Labels: approved, lgtm, size/XS

#767 Add configurable syncset reapply interval.
  config/crds/hive_v1_hiveconfig.yaml
  docs/syncset.md
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#777 Extract URLs from kubeconfig for adopted clusters without a provision.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/M

#784 Add --create-sample-syncsets to hiveutil create-cluster
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm, size/M

#787 Add cd name to sample syncsets.
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm, size/XS

#788 Add maintenanceMode support in HiveConfig.
  config/crds/hive_v1alpha1_hiveconfig.yaml
  pkg/apis/hive/v1alpha1/hiveconfig_types.go
  pkg/apis/hive/v1alpha1/zz_generated.deepcopy.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
Labels: approved, lgtm, size/M

#783 Remove use of ObjectReference type in Hive v1 API
  config/crds/hive_v1_checkpoint.yaml
  config/crds/hive_v1_selectorsyncset.yaml
  config/crds/hive_v1_syncset.yaml
  config/crds/hive_v1_syncsetinstance.yaml
  pkg/apis/hive/v1/checkpoint_types.go
  pkg/apis/hive/v1/syncset_types.go
  pkg/apis/hive/v1/syncsetinstance_types.go
  pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/selector_syncset_validating_admission_hook_test.go
  pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/syncset_validating_admission_hook_test.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
  pkg/controller/syncsetinstance/syncsetinstance_controller_test.go
  pkg/controller/velerobackup/helpers_test.go
  pkg/controller/velerobackup/velerobackup_controller.go
  pkg/controller/velerobackup/velerobackup_controller_test.go
  pkg/hive/apis/hive/hiveconversion/conversion.go
  pkg/operator/assets/bindata.go
  pkg/test/checkpoint/checkpoint.go
Labels: approved, lgtm, size/XXL

#755 delete imageset job when completed
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/L

#776 migration tooling
  config/apiserver/apiserver.template.yaml
  contrib/cmd/hiveutil/main.go
  contrib/pkg/utils/client.go
  contrib/pkg/v1migration/deleteobjects.go
  contrib/pkg/v1migration/recreateobjects.go
  contrib/pkg/v1migration/ref.go
  contrib/pkg/v1migration/restoreownerrefs.go
  contrib/pkg/v1migration/saveownerrefs.go
  contrib/pkg/v1migration/v1migration.go
  hack/deploy-apiserver.sh
  hack/v1migration/README.md
  hack/v1migration/delete.sh
  hack/v1migration/restore.sh
  hack/v1migration/scaledown.sh
  hack/v1migration/scaleup.sh
  hack/v1migration/verify_scaledown.sh
Labels: approved, lgtm, size/XL

#779 Add labels used for ownership reconciliation
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1alpha1/clusterdeployment_types.go
  pkg/constants/constants.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller_test.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/clusterstate/clusterstate_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller_test.go
  pkg/controller/utils/utils.go
  pkg/hive/apis/hive/clusterdeployment_types.go
  pkg/imageset/generate.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: approved, lgtm, size/L

#792 Add an install log scan regex for AWS NAT gateway limit exceeded errors.
  config/configmaps/install-log-regexes-configmap.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#785 allow hive operator to deploy/tear down the v1alpha1 aggregated api
  .gitignore
  config/apiserver/apiserver.template.yaml
  config/apiserver/apiservice.yaml
  config/apiserver/deployment.yaml
  config/apiserver/hiveapi-cluster-role-binding.yaml
  config/apiserver/service-account.yaml
  config/apiserver/service.yaml
  config/crds/hive_v1_hiveconfig.yaml
  config/kustomization.yaml
  hack/deploy-apiserver.sh
  hack/hiveapi-dev-cert.sh
  hack/make-apiserver-certs.sh
  hack/update-bindata.sh
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
  pkg/operator/hive/hiveapi.go
Labels: approved, lgtm, size/XL

#791 tooling for restoring hive config as a separate migration action
  config/apiserver/apiserver.template.yaml
  contrib/pkg/v1migration/recreateobjects.go
  hack/deploy-apiserver.sh
  hack/v1migration/README.md
  hack/v1migration/delete.sh
  hack/v1migration/deploy_apiserver.sh
  hack/v1migration/restore.sh
  hack/v1migration/restore_hiveconfig.sh
  hack/v1migration/scaledown.sh
  hack/v1migration/verify_apiserver.sh
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L
