Repository openshift/hive, pull requests merged in 2020-02, with the labels that each got.

#790 apiserver: watch support
  config/apiserver/deployment.yaml
  pkg/hive/apiserver/registry/checkpoint/proxy.go
  pkg/hive/apiserver/registry/clusterdeployment/proxy.go
  pkg/hive/apiserver/registry/clusterdeployment/watch.go
  pkg/hive/apiserver/registry/clusterdeprovisionrequest/proxy.go
  pkg/hive/apiserver/registry/clusterimageset/proxy.go
  pkg/hive/apiserver/registry/clusterprovision/proxy.go
  pkg/hive/apiserver/registry/clusterstate/proxy.go
  pkg/hive/apiserver/registry/dnszone/proxy.go
  pkg/hive/apiserver/registry/hiveconfig/proxy.go
  pkg/hive/apiserver/registry/selectorsyncidentityprovider/proxy.go
  pkg/hive/apiserver/registry/selectorsyncset/proxy.go
  pkg/hive/apiserver/registry/syncidentityprovider/proxy.go
  pkg/hive/apiserver/registry/syncset/proxy.go
  pkg/hive/apiserver/registry/syncsetinstance/proxy.go
  pkg/hive/apiserver/registry/watch.go
  pkg/hive/apiserver/registry/wrapper.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XL

#794 Add labels for syncsetinstance
  Gopkg.lock
  pkg/constants/constants.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncset/syncset_controller.go
  pkg/controller/syncset/syncset_controller_test.go
  pkg/controller/utils/utils.go
  pkg/installmanager/installmanager.go
  vendor/k8s.io/kubernetes/pkg/util/labels/doc.go
  vendor/k8s.io/kubernetes/pkg/util/labels/labels.go
Labels: approved, lgtm, size/L

#795 Formalize addition of ssh known hosts in install manager.
  config/crds/hive_v1_clusterdeployment.yaml
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#796 apiserver: update migration README with certs step
  hack/make-apiserver-certs.sh
  hack/v1migration/README.md
Labels: approved, lgtm, size/M

#800 controllers: remoteingress spelling error
  pkg/controller/remoteingress/remoteingress_controller.go
Labels: approved, lgtm, size/XS

#797 apiserver: clusterdeployment resource version amalgamation
  pkg/hive/apiserver/registry/clusterdeployment/proxy.go
  pkg/hive/apiserver/registry/clusterdeployment/watch.go
  pkg/hive/apiserver/registry/util/convert.go
Labels: approved, lgtm, size/L

#802 add type info for syncsets and selectorsyncsets
  contrib/pkg/createcluster/create.go
Labels: approved, lgtm, size/XS

#803 migration: restore status on re-create
  contrib/pkg/v1migration/recreateobjects.go
Labels: approved, lgtm, size/XS

#806 build: include mockgen in build image
  build/build-image/Dockerfile
Labels: approved, lgtm, size/XS

#812 controllers: add doc.go
  pkg/controller/doc.go
Labels: approved, lgtm, size/XS

#811 Remove install of libvirt deps temporarily.
  Dockerfile
Labels: approved, lgtm, size/XS

#814 update olm template for v1
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/S

#813 migration: do not mutate object when doing a dry run delete
  contrib/pkg/v1migration/deleteobjects.go
Labels: approved, lgtm, size/M

#815 Hiveapi fixes
  config/apiserver/deployment.yaml
  config/apiserver/hiveapi-cluster-role-binding.yaml
  config/apiserver/service.yaml
  pkg/operator/hive/hiveapi.go
Labels: approved, lgtm, size/S

#816 Master hiveapi rbac
  config/apiserver/deployment.yaml
  config/apiserver/hiveapi-cluster-role-binding.yaml
  config/apiserver/service.yaml
  pkg/operator/hive/hiveapi.go
Labels: size/S

#818 Fix missing bindata in rushed merges yesterday.
  config/apiserver/hiveapi-cluster-role-binding.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/S

#822 migration: support oc 3.11
  hack/v1migration/delete.sh
Labels: approved, lgtm, size/S

#819 Separate cluster ssh key from libvirt connection ssh key.
  config/crds/hive_v1_clusterdeployment.yaml
  pkg/apis/hive/v1/baremetal/doc.go
  pkg/apis/hive/v1/baremetal/platform.go
  pkg/apis/hive/v1/baremetal/zz_generated.deepcopy.go
  pkg/constants/constants.go
  pkg/install/generate.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/L

#799 controllers: return when syncsetinstance controller cannot build restconfig
  pkg/controller/syncsetinstance/syncsetinstance_controller.go
Labels: approved, lgtm, size/XS

#820 Switch to FROM centos:7 and restore libvirt dependencies.
  Dockerfile
Labels: approved, lgtm, size/XS

#824 V1 merge
  contrib/pkg/v1migration/deleteobjects.go
Labels: approved, lgtm, size/M

#825 apiserver: fix rbac and port used
  config/apiserver/deployment.yaml
  config/apiserver/hiveapi-cluster-role-binding.yaml
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hiveapi.go
Labels: approved, lgtm, size/M

#826 Remove now obsolete toleration edit in remoteingress controller.
  pkg/controller/remoteingress/remoteingress_controller.go
Labels: approved, lgtm, size/S

#831 Stable: Remove now obsolete toleration edit in remoteingress controller.
  pkg/controller/remoteingress/remoteingress_controller.go
Labels: approved, lgtm, size/S

#832 sync stable order with master when using cherry-pick
  hack/app_sre_build_deploy.sh
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm, size/S

#830 restart pods with injected certs when the certs rotate
  Gopkg.lock
  cmd/hive-apiserver/main.go
  cmd/hiveadmission/main.go
  pkg/certs/certs.go
  vendor/github.com/blang/semver/LICENSE
  vendor/github.com/blang/semver/json.go
  vendor/github.com/blang/semver/range.go
  vendor/github.com/blang/semver/semver.go
  vendor/github.com/blang/semver/sort.go
  vendor/github.com/blang/semver/sql.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/k8s.io/component-base/metrics/counter.go
  vendor/k8s.io/component-base/metrics/gauge.go
  vendor/k8s.io/component-base/metrics/histogram.go
  vendor/k8s.io/component-base/metrics/legacyregistry/registry.go
  vendor/k8s.io/component-base/metrics/metric.go
  vendor/k8s.io/component-base/metrics/opts.go
  vendor/k8s.io/component-base/metrics/processstarttime.go
  vendor/k8s.io/component-base/metrics/registry.go
  vendor/k8s.io/component-base/metrics/summary.go
  vendor/k8s.io/component-base/metrics/version_parser.go
  vendor/k8s.io/component-base/metrics/wrappers.go
Labels: approved, lgtm, size/XXL

#838 Fix missing ClusterImageSet condition.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
Labels: approved, lgtm, size/S

#840 installmanager: remove manual adding to /etc/passwd
  Dockerfile
  Dockerfile.dev
  build/hive/Dockerfile
  pkg/installmanager/installmanager.go
Labels: approved, lgtm, size/M

#823 docs: update using-hive.md for v1, add hiveutil doc
  README.md
  docs/hiveutil.md
  docs/using-hive.md
Labels: approved, lgtm, size/L

#839 Add documentation on bare metal provisioning with Hive.
  docs/hive-baremetal-hypervisor-per-cluster.png
  docs/hive-baremetal-shared-hypervisor.png
  docs/using-hive.md
Labels: approved, lgtm, size/L

#809 Migrate hive objects to have expected v1 labels
  contrib/cmd/hiveutil/main.go
  contrib/pkg/labelobjects/labelobjects.go
  contrib/pkg/labelobjects/labelobjects_test.go
  pkg/constants/constants.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/utils/utils.go
  pkg/controller/velerobackup/velerobackup_controller.go
  pkg/controller/velerobackup/velerobackup_controller_test.go
  pkg/test/generic/generic.go
  pkg/test/job/job.go
  pkg/test/persistentvolumeclaim/persistentvolumeclaim.go
  pkg/test/secret/secret.go
Labels: approved, lgtm, size/XXL

#837 hack: script for extracting the kubeconfig for a clusterdeployment
  docs/using-hive.md
  hack/get-kubeconfig.sh
Labels: approved, lgtm, size/M

#844 migration: changes to support hive-int
  contrib/pkg/v1migration/deleteobjects.go
  contrib/pkg/v1migration/restoreownerrefs.go
  contrib/pkg/v1migration/saveownerrefs.go
  hack/v1migration/README.md
  hack/v1migration/delete.sh
  hack/v1migration/remove_hiveadmission.sh
  hack/v1migration/scaledown.sh
  hack/v1migration/scaleup.sh
  hack/v1migration/verify_scaledown.sh
Labels: approved, lgtm, size/L

#781 handle changing managed domains in hiveConfig
  Gopkg.lock
  config/crds/hive_v1_hiveconfig.yaml
  contrib/pkg/adm/managedns/enable.go
  contrib/pkg/createcluster/create.go
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/constants/constants.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/hive/hiveadmission.go
  pkg/operator/hive/manageddns.go
Labels: approved, lgtm, size/L

#846 Fix globalPullSecretRef mistake from v1 refactor in docs.
  docs/using-hive.md
Labels: approved, lgtm, size/XS

#849 set the correct field name when adding additional CAs
  hack/set-additional-ca.sh
Labels: approved, lgtm, size/XS

#852 migration: fix dnsendpoints not being skipped during owner ref restore
  contrib/pkg/v1migration/restoreownerrefs.go
Labels: approved, lgtm, size/XS

#853 validation: reject changes to MachinePool platform fields
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook.go
  pkg/apis/hive/v1/validating-webhooks/machinepool_validating_admission_hook_test.go
Labels: approved, lgtm, size/S

#855 Fix incorrect hiveconfig v1 field names in olm template.
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, size/XS

#856 Readd v1alpha1 ClusterDeprovisionRequest to rbac for hive-frontend.
  config/rbac/hive_frontend_role.yaml
  pkg/operator/assets/bindata.go
Labels: size/XS

#857 Also add v1alpha1 clusterdeprovisionrequest to operator and other roles.
  config/operator/operator_role.yaml
  config/rbac/hive_admin_role.yaml
  config/rbac/hive_frontend_role.yaml
  config/rbac/hive_reader_role.yaml
  pkg/operator/assets/bindata.go
Labels: approved, size/S

#859 Bump hiveapi memory limits.
  config/apiserver/deployment.yaml
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/XS

#854 support aws china for managed dns
  config/crds/hive_v1_dnszone.yaml
  config/crds/hive_v1_hiveconfig.yaml
  pkg/apis/hive/v1/dnszone_types.go
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/awsclient/client.go
  pkg/constants/constants.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/dnsendpoint/dnsendpoint_controller.go
  pkg/controller/dnsendpoint/nameserver/aws.go
  pkg/controller/dnszone/awsactuator.go
  pkg/operator/assets/bindata.go
Labels: approved, lgtm, size/M

#858 Add additional CAs to admin kubeconfig even when status URLs set.
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/utils/cacrt.go
Labels: approved, lgtm, size/L

#860 fix a broken link
  docs/using-hive.md
Labels: approved, lgtm, ok-to-test, size/XS

#848 docs: update install pod labels in using-hive.md
  docs/using-hive.md
Labels: approved, lgtm, size/XS
