Repository openshift/hive, pull requests merged in 2020-09, with the labels that each got.

#1106 Hibernation: increase delay to check for node readiness
  pkg/controller/hibernation/hibernation_controller.go
Labels: approved, lgtm

#1111 controller: create clustersync as separate reconcile
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/clustersync/clustersync_controller_test.go
Labels: approved, lgtm

#1107 Aws dns cleanup refactor
  pkg/controller/dnszone/awsactuator.go
  pkg/controller/dnszone/awsactuator_test.go
  pkg/controller/dnszone/dnszone_controller_test.go
  pkg/installmanager/dnscleanup.go
  pkg/installmanager/installmanager.go
Labels: approved, lgtm

#1114 deploy: change production SHA retrieval to use new location
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm

#1113 Add Velero to OLM Artifact Template
  hack/olm-registry/olm-artifacts-template.yaml
Labels: approved, lgtm, tide/merge-method-squash

#1084 Implement hibernation for GCP
  pkg/controller/hibernation/gcp_actuator.go
  pkg/controller/hibernation/gcp_actuator_test.go
  pkg/gcpclient/client.go
  pkg/gcpclient/mock/client_generated.go
Labels: approved, lgtm

#1110 operator: fix cleanup of syncsetinstances
  pkg/operator/hive/hive.go
Labels: approved, lgtm

#1119 controller: fix syncset applies not going immediately after ClusterSync create
  pkg/controller/clustersync/clustersync_controller.go
Labels: approved, lgtm

#1120 pipeline: lock registry container to 4.5
  hack/app_sre_create_image_catalog.sh
Labels: approved, lgtm

#1116 CO-1114. Handle different worker-user-data secret name for 4.6
  go.mod
  go.sum
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/remotemachineset/awsactuator.go
  pkg/controller/remotemachineset/azureactuator.go
  pkg/controller/remotemachineset/constants.go
  pkg/controller/remotemachineset/gcpactuator.go
  pkg/controller/remotemachineset/openstackactuator.go
  pkg/controller/remotemachineset/ovirt.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/controller/remotemachineset/secrets.go
  pkg/controller/remotemachineset/secrets_test.go
  pkg/controller/remotemachineset/vsphereactuator.go
  vendor/github.com/blang/semver/v4/LICENSE
  vendor/github.com/blang/semver/v4/go.mod
  vendor/github.com/blang/semver/v4/json.go
  vendor/github.com/blang/semver/v4/range.go
  vendor/github.com/blang/semver/v4/semver.go
  vendor/github.com/blang/semver/v4/sort.go
  vendor/github.com/blang/semver/v4/sql.go
  vendor/modules.txt
Labels: approved, lgtm

#1112 GCP DNS cleanup after install failure
  pkg/controller/dnszone/dnszone_controller_test.go
  pkg/controller/dnszone/gcpactuator.go
  pkg/installmanager/dnscleanup.go
  pkg/installmanager/installmanager.go
  pkg/test/dnszone/dnszone.go
Labels: approved, lgtm

#1124 fix azure deprovision by implicitly setting resource group
  contrib/pkg/deprovision/azure.go
Labels: approved, lgtm

#1125 client: update generated code
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/listers/hive/v1/checkpoint.go
  pkg/client/listers/hive/v1/clusterclaim.go
  pkg/client/listers/hive/v1/clusterdeployment.go
  pkg/client/listers/hive/v1/clusterdeprovision.go
  pkg/client/listers/hive/v1/clusterimageset.go
  pkg/client/listers/hive/v1/clusterpool.go
  pkg/client/listers/hive/v1/clusterprovision.go
  pkg/client/listers/hive/v1/clusterrelocate.go
  pkg/client/listers/hive/v1/clusterstate.go
  pkg/client/listers/hive/v1/dnszone.go
  pkg/client/listers/hive/v1/hiveconfig.go
  pkg/client/listers/hive/v1/machinepool.go
  pkg/client/listers/hive/v1/machinepoolnamelease.go
  pkg/client/listers/hive/v1/selectorsyncidentityprovider.go
  pkg/client/listers/hive/v1/selectorsyncset.go
  pkg/client/listers/hive/v1/syncidentityprovider.go
  pkg/client/listers/hive/v1/syncset.go
  pkg/client/listers/hiveinternal/v1alpha1/clustersync.go
  pkg/client/listers/hiveinternal/v1alpha1/clustersynclease.go
Labels: approved, lgtm

#1115 Azure dns cleanup after install failure and retire ModifyStatus from Actuator
  pkg/azureclient/client.go
  pkg/controller/dnszone/actuator.go
  pkg/controller/dnszone/awsactuator.go
  pkg/controller/dnszone/azureactuator.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/gcpactuator.go
  pkg/installmanager/dnscleanup.go
Labels: approved, lgtm

#1118 accept gone SyncSetInstance during cleanup
  pkg/operator/hive/hive.go
Labels: approved, lgtm

#1099 Restart deprovision pods if credentials secret changes.
  contrib/pkg/deprovision/awstagdeprovision.go
  pkg/constants/constants.go
  pkg/install/generate.go
Labels: approved, lgtm

#1128 fetch vSphere image in vSphere actuator
  go.mod
  pkg/controller/remotemachineset/vsphereactuator.go
Labels: approved, lgtm

#1131 install: fix azure failed provision cleanup
  pkg/installmanager/installmanager.go
Labels: approved, lgtm

#1126 document installing a cluster with hive onto oVirt
  docs/hiveutil.md
  docs/using-hive.md
  pkg/install/generate.go
Labels: approved, lgtm

#1133 Check error creating azure client in DNS cleanup
  pkg/installmanager/dnscleanup.go
Labels: approved, lgtm, ok-to-test

#1127 Vsphere docs
  docs/hiveutil.md
  docs/using-hive.md
Labels: approved, lgtm

#1132 deprovision: kill deprovision when creds change
  contrib/pkg/deprovision/deprovision.go
  pkg/install/generate.go
Labels: approved, lgtm

#1083 Enable configuring controllers through HiveConfig
  cmd/manager/main.go
  config/controllers/deployment.yaml
  config/crds/hive.openshift.io_hiveconfigs.yaml
  go.mod
  pkg/apis/hive/v1/hiveconfig_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterclaim/clusterclaim_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/controller/clusterpoolnamespace/clusterpoolnamespace_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
  pkg/controller/clusterrelocate/clusterrelocate_controller.go
  pkg/controller/clusterstate/clusterstate_controller.go
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/dnsendpoint/dnsendpoint_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/metrics/metrics.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/unreachable/unreachable_controller.go
  pkg/controller/utils/clientwrapper.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
  pkg/controller/velerobackup/velerobackup_controller.go
  pkg/controller/velerobackup/velerobackup_controller_test.go
  pkg/operator/assets/bindata.go
  pkg/operator/hive/hive.go
  pkg/remoteclient/remoteclient.go
  pkg/remoteclient/remoteclient_test.go
  pkg/resource/helper.go
  pkg/resource/kubeconfig_factory.go
Labels: approved, lgtm

#1134 add lifetime field to clusterclaim
  config/crds/hive.openshift.io_clusterclaims.yaml
  pkg/apis/hive/v1/clusterclaim_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterclaim/clusterclaim_controller.go
  pkg/controller/clusterclaim/clusterclaim_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/utils/utils.go
  pkg/controller/utils/utils_test.go
  pkg/test/clusterclaim/clusterclaim.go
Labels: approved, lgtm

#1109 Add condition when deprovision fails cloud auth
  config/crds/hive.openshift.io_clusterdeprovisions.yaml
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/clusterdeprovision_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/awsclient/client.go
  pkg/awsclient/mock/client_generated.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeprovision/actuator.go
  pkg/controller/clusterdeprovision/awsactuator.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
  pkg/controller/clusterdeprovision/helpers_test.go
  pkg/controller/utils/conditions.go
  pkg/gcpclient/mock/client_generated.go
Labels: approved, lgtm

#1137 deprovision: skip symlinks in creds file watch
  contrib/pkg/deprovision/deprovision.go
Labels: approved, lgtm

#1091 Improve Hive leader election
  cmd/manager/main.go
  cmd/operator/main.go
  docs/developing.md
Labels: approved, lgtm

#1138 machinepool condition for unsupported spot instances
  pkg/apis/hive/v1/machinepool_types.go
  pkg/controller/remotemachineset/awsactuator.go
  pkg/controller/remotemachineset/awsactuator_test.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
Labels: approved, lgtm

#1143 dockerfiles: use go 1.15
  Dockerfile
  Dockerfile.dev
  build/build-image/Dockerfile
Labels: approved, lgtm

#1144 update library-go
  config/crds/hive.openshift.io_checkpoints.yaml
  config/crds/hive.openshift.io_clusterclaims.yaml
  config/crds/hive.openshift.io_clusterdeployments.yaml
  config/crds/hive.openshift.io_clusterdeprovisions.yaml
  config/crds/hive.openshift.io_clusterimagesets.yaml
  config/crds/hive.openshift.io_clusterpools.yaml
  config/crds/hive.openshift.io_clusterprovisions.yaml
  config/crds/hive.openshift.io_clusterrelocates.yaml
  config/crds/hive.openshift.io_clusterstates.yaml
  config/crds/hive.openshift.io_dnszones.yaml
  config/crds/hive.openshift.io_hiveconfigs.yaml
  config/crds/hive.openshift.io_machinepoolnameleases.yaml
  config/crds/hive.openshift.io_machinepools.yaml
  config/crds/hive.openshift.io_selectorsyncidentityproviders.yaml
  config/crds/hive.openshift.io_selectorsyncsets.yaml
  config/crds/hive.openshift.io_syncidentityproviders.yaml
  config/crds/hive.openshift.io_syncsets.yaml
  config/crds/hiveinternal.openshift.io_clustersyncleases.yaml
  config/crds/hiveinternal.openshift.io_clustersyncs.yaml
  docs/developing.md
  go.mod
  go.sum
  pkg/gcpclient/mock/client_generated.go
  vendor/github.com/openshift/build-machinery-go/go.mod
  vendor/github.com/openshift/build-machinery-go/make/lib/golang.mk
  vendor/github.com/openshift/build-machinery-go/make/operator.example.mk.help.log
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/controller-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/crd-schema-gen.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/operator/telepresence.mk
  vendor/github.com/openshift/build-machinery-go/make/targets/openshift/yaml-patch.mk
  vendor/github.com/openshift/build-machinery-go/scripts/run-telepresence.sh
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_in_memory.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_logging.go
  vendor/github.com/openshift/library-go/pkg/operator/events/recorder_upstream.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourcemerge/generic_config_merger.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/apiextensions.go
  vendor/github.com/openshift/library-go/pkg/operator/resource/resourceread/credentialsrequest.go
  vendor/modules.txt
Labels: approved, lgtm

#1140 requeue cd after creating clustersync
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/clustersync/clustersync_controller_test.go
Labels: approved, lgtm

#1147 CO-1187: Latest hive doesn't honor syncset-pause annotation
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/clustersync/clustersync_controller_test.go
Labels: approved, lgtm

#1122 Implement hibernate-after annotation to auto-powerdown.
  config/crds/hive.openshift.io_clusterdeployments.yaml
  contrib/pkg/createcluster/create.go
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/clusterresource/builder.go
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/hibernation/hibernation_controller_test.go
  pkg/test/clusterdeployment/clusterdeployment.go
Labels: approved, lgtm

#1142 Log first success times when we report the metrics.
  pkg/controller/clustersync/clustersync_controller.go
Labels: approved, lgtm

#1139 sort patches for identityproviders
  pkg/controller/syncidentityprovider/syncidentityprovider_controller.go
  pkg/controller/syncidentityprovider/syncidentityprovider_controller_test.go
Labels: approved, lgtm

#1149 Tag librarygo version
  go.mod
  go.sum
  vendor/modules.txt
Labels: approved, lgtm

#1151 Allow mutating ClusterDeployment.Spec.HibernateAfter.
  pkg/apis/hive/v1/validating-webhooks/clusterdeployment_validating_admission_hook.go
Labels: approved, lgtm

#1146 Add docs for OpenStack
  README.md
  docs/hiveutil.md
  docs/using-hive.md
Labels: approved, lgtm

#1156 makefile: use earlier version of controller-gen
  Makefile
  config/crds/hive.openshift.io_checkpoints.yaml
  config/crds/hive.openshift.io_clusterclaims.yaml
  config/crds/hive.openshift.io_clusterdeployments.yaml
  config/crds/hive.openshift.io_clusterdeprovisions.yaml
  config/crds/hive.openshift.io_clusterimagesets.yaml
  config/crds/hive.openshift.io_clusterpools.yaml
  config/crds/hive.openshift.io_clusterprovisions.yaml
  config/crds/hive.openshift.io_clusterrelocates.yaml
  config/crds/hive.openshift.io_clusterstates.yaml
  config/crds/hive.openshift.io_dnszones.yaml
  config/crds/hive.openshift.io_hiveconfigs.yaml
  config/crds/hive.openshift.io_machinepoolnameleases.yaml
  config/crds/hive.openshift.io_machinepools.yaml
  config/crds/hive.openshift.io_selectorsyncidentityproviders.yaml
  config/crds/hive.openshift.io_selectorsyncsets.yaml
  config/crds/hive.openshift.io_syncidentityproviders.yaml
  config/crds/hive.openshift.io_syncsets.yaml
  config/crds/hiveinternal.openshift.io_clustersyncleases.yaml
  config/crds/hiveinternal.openshift.io_clustersyncs.yaml
  pkg/gcpclient/mock/client_generated.go
Labels: approved, lgtm

#1158 types: add status sub-resource to syncsets
  config/crds/hive.openshift.io_selectorsyncsets.yaml
  config/crds/hive.openshift.io_syncsets.yaml
  pkg/apis/hive/v1/syncset_types.go
Labels: approved, lgtm

#1135 remove clusterVersionStatus field from clusterdeployment
  config/crds/hive.openshift.io_clusterdeployments.yaml
  pkg/apis/hive/v1/clusterdeployment_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/hibernation/hibernation_controller_test.go
  pkg/controller/remotemachineset/remotemachineset_controller.go
  pkg/controller/remotemachineset/remotemachineset_controller_test.go
  pkg/test/clusterdeployment/clusterdeployment.go
  test/e2e/postinstall/machinesets/infra_test.go
Labels: approved, lgtm

#1155 Add support for ClusterPool.Spec.Labels to apply to new ClusterDeploy…
  config/crds/hive.openshift.io_clusterpools.yaml
  pkg/apis/hive/v1/clusterpool_types.go
  pkg/apis/hive/v1/zz_generated.deepcopy.go
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/controller/clusterpool/clusterpool_controller_test.go
  pkg/test/clusterpool/clusterpool.go
Labels: approved, lgtm

#1157 Refine ClusterDeployment printcolumns.
  config/crds/hive.openshift.io_clusterdeployments.yaml
  hack/e2e-test.sh
  pkg/apis/hive/v1/clusterdeployment_types.go
Labels: approved, lgtm

#1153 Set clusterSync.Status.FirstSyncSetsSuccessTime and add metric
  config/crds/hiveinternal.openshift.io_clustersyncs.yaml
  pkg/apis/hiveinternal/v1alpha1/clustersync_types.go
  pkg/apis/hiveinternal/v1alpha1/zz_generated.deepcopy.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/clustersync/clustersync_controller_test.go
Labels: approved, lgtm, tide/merge-method-squash
