Repository openshift/hive, pull requests merged in 2021-05, with the labels that each got.

#1360 Sketch out ClusterInstall API contract, and a FakeClusterInstall reference implementation.
  apis/hive/v1/agent/installstrategy.go
  apis/hive/v1/agent/platform.go
  apis/hive/v1/agent/status.go
  apis/hive/v1/agent/zz_generated.deepcopy.go
  apis/hive/v1/clusterdeployment_types.go
  apis/hive/v1/clusterinstall_conditions.go
  apis/hive/v1/hiveconfig_types.go
  apis/hive/v1/zz_generated.deepcopy.go
  apis/hivecontracts/v1alpha1/clusterinstall_types.go
  apis/hivecontracts/v1alpha1/zz_generated.deepcopy.go
  apis/hiveinternal/v1alpha1/fakeclusterinstall_types.go
  apis/hiveinternal/v1alpha1/zz_generated.deepcopy.go
  cmd/manager/main.go
  config/controllers/hive_controllers_role.yaml
  config/crds/hive.openshift.io_clusterdeployments.yaml
  config/crds/hive.openshift.io_clusterpools.yaml
  config/crds/hiveinternal.openshift.io_fakeclusterinstalls.yaml
  config/crdspatch/hiveinternal.openshift.io_fakeclusterinstalls.yaml
  config/operator/operator_role.yaml
  pkg/client/clientset/versioned/typed/hiveinternal/v1alpha1/fake/fake_fakeclusterinstall.go
  pkg/client/clientset/versioned/typed/hiveinternal/v1alpha1/fake/fake_hiveinternal_client.go
  pkg/client/clientset/versioned/typed/hiveinternal/v1alpha1/fakeclusterinstall.go
  pkg/client/clientset/versioned/typed/hiveinternal/v1alpha1/generated_expansion.go
  pkg/client/clientset/versioned/typed/hiveinternal/v1alpha1/hiveinternal_client.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/informers/externalversions/hiveinternal/v1alpha1/fakeclusterinstall.go
  pkg/client/informers/externalversions/hiveinternal/v1alpha1/interface.go
  pkg/client/listers/hiveinternal/v1alpha1/expansion_generated.go
  pkg/client/listers/hiveinternal/v1alpha1/fakeclusterinstall.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeployment/clusterinstalls.go
  pkg/controller/fakeclusterinstall/fakeclusterinstall_controller.go
  pkg/controller/utils/conditions.go
  pkg/operator/assets/bindata.go
  pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go
  pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go
  vendor/github.com/openshift/hive/apis/hive/v1/agent/installstrategy.go
  vendor/github.com/openshift/hive/apis/hive/v1/agent/platform.go
  vendor/github.com/openshift/hive/apis/hive/v1/agent/status.go
  vendor/github.com/openshift/hive/apis/hive/v1/agent/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterinstall_conditions.go
  vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hivecontracts/v1alpha1/clusterinstall_types.go
  vendor/github.com/openshift/hive/apis/hivecontracts/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hiveinternal/v1alpha1/fakeclusterinstall_types.go
  vendor/github.com/openshift/hive/apis/hiveinternal/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm

#1356 Add proposal for breaking out install strategy to separate CRDs.
  docs/enhancements/cluster-install-apis.md
Labels: approved, lgtm

#1370 Remove Massive PodSpec in ClusterProvision CRD yaml
  Makefile
  config/crds/hive.openshift.io_clusterprovisions.yaml
Labels: approved, lgtm

#1375 remotemachinesets: sync ready replicas and errors to machinepool
  apis/hive/v1/machinepool_types.go
  apis/hive/v1/zz_generated.deepcopy.go
  config/crds/hive.openshift.io_machinepools.yaml
  pkg/controller/remotemachineset/remotemachineset_controller.go
  vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
Labels: approved, lgtm

#1376 Fix cluster claim for fake clusterpool
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/hibernation/hibernation_controller_test.go
Labels: approved, lgtm

#1378 Add prometheus target for hive-operator metrics
  cmd/operator/main.go
  config/operator/operator_deployment.yaml
  config/prometheus/prometheus-configmap.yaml
Labels: approved, lgtm

#1372 Set ClusterDeploymentCondition for all status
  pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterrelocate/clusterrelocate_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/utils/conditions.go
  pkg/imageset/updateinstaller.go
Labels: approved, lgtm

#1380 Fix hotloop in awsprivatelink controller in some situations
  pkg/controller/awsprivatelink/awsprivatelink_controller.go
  pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
  pkg/controller/awsprivatelink/cleanup.go
Labels: approved

#1379 Add owner ref on FakeClusterInstall.
  pkg/controller/fakeclusterinstall/fakeclusterinstall_controller.go
Labels: approved, lgtm

#1384 allow to set zero replicas also when zones are set
  pkg/validating-webhooks/hive/v1/machinepool_validating_admission_hook.go
  pkg/validating-webhooks/hive/v1/machinepool_validating_admission_hook_test.go
Labels: approved, lgtm

#1383 doc fix for install.md - format HiveConfig yaml sample
  docs/install.md
Labels: approved, lgtm, ok-to-test

#1385 Add metrics controller for hive-operator
  apis/hive/v1/hiveconfig_types.go
  pkg/constants/constants.go
  pkg/operator/add_hive.go
  pkg/operator/hive/hive_controller.go
  pkg/operator/metrics/metrics.go
  vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
Labels: approved, lgtm

#1386 Fix stuck privatelink clusters deleted prior to install.
  pkg/controller/awsprivatelink/awsprivatelink_controller.go
  pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
  pkg/controller/awsprivatelink/cleanup.go
Labels: approved, lgtm

#1388 do not include error message in status condition
  pkg/controller/dnszone/awsactuator.go
  pkg/controller/dnszone/dnszone_controller_test.go
Labels: approved, lgtm

#1387 remotemachineset: periodically reconcile MachinePools for update
  pkg/controller/remotemachineset/remotemachineset_controller.go
Labels: approved, lgtm

#1390 verify release images used for cluster deployments
  apis/hive/v1/hiveconfig_types.go
  apis/hive/v1/zz_generated.deepcopy.go
  config/crds/hive.openshift.io_hiveconfigs.yaml
  docs/releaseimageverify.md
  go.mod
  pkg/constants/constants.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/operator/hive/hive.go
  pkg/operator/hive/hiveadmission.go
  pkg/validating-webhooks/hive/v1/clusterimageset_validating_admission_hook.go
  pkg/validating-webhooks/hive/v1/clusterimageset_validating_admission_hook_test.go
  vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/library-go/pkg/manifest/OWNERS
  vendor/github.com/openshift/library-go/pkg/manifest/manifest.go
  vendor/github.com/openshift/library-go/pkg/verify/OWNERS
  vendor/github.com/openshift/library-go/pkg/verify/configmap.go
  vendor/github.com/openshift/library-go/pkg/verify/persist.go
  vendor/github.com/openshift/library-go/pkg/verify/store/configmap/configmap.go
  vendor/github.com/openshift/library-go/pkg/verify/store/parallel/parallel.go
  vendor/github.com/openshift/library-go/pkg/verify/store/serial/serial.go
  vendor/github.com/openshift/library-go/pkg/verify/store/sigstore/client.go
  vendor/github.com/openshift/library-go/pkg/verify/store/sigstore/sigstore.go
  vendor/github.com/openshift/library-go/pkg/verify/store/store.go
  vendor/github.com/openshift/library-go/pkg/verify/util/encode.go
  vendor/github.com/openshift/library-go/pkg/verify/util/util.go
  vendor/github.com/openshift/library-go/pkg/verify/verify.go
  vendor/golang.org/x/crypto/cast5/cast5.go
  vendor/golang.org/x/crypto/openpgp/armor/armor.go
  vendor/golang.org/x/crypto/openpgp/armor/encode.go
  vendor/golang.org/x/crypto/openpgp/canonical_text.go
  vendor/golang.org/x/crypto/openpgp/elgamal/elgamal.go
  vendor/golang.org/x/crypto/openpgp/errors/errors.go
  vendor/golang.org/x/crypto/openpgp/keys.go
  vendor/golang.org/x/crypto/openpgp/packet/compressed.go
  vendor/golang.org/x/crypto/openpgp/packet/config.go
  vendor/golang.org/x/crypto/openpgp/packet/encrypted_key.go
  vendor/golang.org/x/crypto/openpgp/packet/literal.go
  vendor/golang.org/x/crypto/openpgp/packet/ocfb.go
  vendor/golang.org/x/crypto/openpgp/packet/one_pass_signature.go
  vendor/golang.org/x/crypto/openpgp/packet/opaque.go
  vendor/golang.org/x/crypto/openpgp/packet/packet.go
  vendor/golang.org/x/crypto/openpgp/packet/private_key.go
  vendor/golang.org/x/crypto/openpgp/packet/public_key.go
  vendor/golang.org/x/crypto/openpgp/packet/public_key_v3.go
  vendor/golang.org/x/crypto/openpgp/packet/reader.go
  vendor/golang.org/x/crypto/openpgp/packet/signature.go
  vendor/golang.org/x/crypto/openpgp/packet/signature_v3.go
  vendor/golang.org/x/crypto/openpgp/packet/symmetric_key_encrypted.go
  vendor/golang.org/x/crypto/openpgp/packet/symmetrically_encrypted.go
  vendor/golang.org/x/crypto/openpgp/packet/userattribute.go
  vendor/golang.org/x/crypto/openpgp/packet/userid.go
  vendor/golang.org/x/crypto/openpgp/read.go
  vendor/golang.org/x/crypto/openpgp/s2k/s2k.go
  vendor/golang.org/x/crypto/openpgp/write.go
  vendor/modules.txt
Labels: approved, lgtm

#1381 Initialize all cluster deployment conditions
  pkg/controller/awsprivatelink/awsprivatelink_controller.go
  pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeployment/clusterinstalls.go
  pkg/controller/clusterrelocate/clusterrelocate_controller.go
  pkg/controller/clusterrelocate/clusterrelocate_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/controlplanecerts/controlplanecerts_controller_test.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/controller/remoteingress/remoteingress_controller_test.go
  pkg/controller/unreachable/unreachable_controller.go
  pkg/controller/unreachable/unreachable_controller_test.go
  pkg/imageset/updateinstaller.go
  pkg/imageset/updateinstaller_test.go
  pkg/remoteclient/remoteclient.go
  pkg/remoteclient/remoteclient_test.go
  pkg/test/assert/assertions.go
Labels: approved, lgtm

#1392 Lower leader election lease durations.
  cmd/manager/main.go
  cmd/operator/main.go
Labels: approved, lgtm

#1396 fix support of OpenStack autoscalling.minRep=0
  pkg/controller/remotemachineset/remotemachineset_controller.go
Labels: approved, lgtm

#1394 Metrics change to accomodate clusterdeployment conditions cleanup
  apis/hive/v1/clusterdeployment_types.go
  pkg/controller/metrics/metrics.go
  pkg/controller/metrics/metrics_test.go
  pkg/controller/utils/conditions.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
Labels: approved, lgtm

#1393 controller/dnszone: rate limit UPDATE events that are in error state
  pkg/controller/dnszone/awsactuator.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/dnszone/dnszone_controller_test.go
  pkg/controller/utils/ratelimitedeventhandler.go
  pkg/controller/utils/ratelimitedeventhandler_test.go
Labels: approved, lgtm

#1398 Sort clusterdeployment conditions
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeployment/clusterinstalls.go
  pkg/controller/metrics/metrics.go
  pkg/controller/utils/conditions.go
  pkg/controller/utils/conditions_test.go
Labels: approved, lgtm
