Repository openshift/hive, pull requests merged in 2022-06, with the labels that each got.

#1783 clustersync UT: Use assert.InDelta instead of hack
  pkg/controller/clustersync/clustersync_controller_test.go
Labels: lgtm, approved

#1785 clustersync: fix missing memcpy
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/clustersync/clustersync_controller_test.go
Labels: lgtm, approved

#1784 certificates.k8s.io/v1beta1 API deprecated in Kubernetes v1.19 and removed before v1.22
  hack/hiveadmission-dev-cert.sh
Labels: lgtm, approved, ok-to-test

#1787 e2e-pool: turn off trace
  hack/e2e-pool-test.sh
Labels: lgtm, approved

#1789 Set HOME to a writable dir for CI
  Makefile
Labels: lgtm, approved

#1788 e2e: kill the timeout subprocess on exit
  hack/e2e-common.sh
  hack/e2e-pool-test.sh
  hack/e2e-test.sh
Labels: lgtm, approved

#1792 powerstate-pause annotation: skip hibernation controller
  apis/hive/v1/clusterdeployment_types.go
  pkg/constants/constants.go
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/hibernation/hibernation_controller_test.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
Labels: lgtm, approved

#1793 Explicit permissions in operator ClusterRole
  config/operator/operator_role.yaml
  hack/app-sre/saas-template.yaml
Labels: lgtm, approved

#1796 Remove NoMatchingRoute53Zone regex
  config/configmaps/install-log-regexes-configmap.yaml
  pkg/operator/assets/bindata.go
Labels: lgtm, approved

#1797 Add SCACertPullFailed to install log regex search
  config/configmaps/install-log-regexes-configmap.yaml
  pkg/controller/clusterprovision/installlogmonitor_test.go
  pkg/operator/assets/bindata.go
Labels: lgtm, approved

#1799 e2e: increase targetNamespace timeout 30s=>3m
  hack/e2e-common.sh
Labels: lgtm, approved

#1802 Patch installconfig generated by clusterresource builder to remove AWS metadataService field.
  pkg/clusterresource/builder.go
Labels: lgtm, approved

#1800 awsactuator: remove Info level log from decodeAWSMachineProviderSpec.
  pkg/controller/machinepool/awsactuator.go
Labels: lgtm, approved

#1798 e2e: Bail early on ProvisionStopped
  hack/e2e-test.sh
Labels: lgtm, approved

#1801 Revert "Remove NoMatchingRoute53Zone regex"
  config/configmaps/install-log-regexes-configmap.yaml
  pkg/operator/assets/bindata.go
Labels: lgtm, approved

#1808 Trigger CI to update to go 1.18
  build/build-image/Dockerfile
Labels: approved

#1805 e2e-pool: hack timeout at ~2h
  hack/e2e-common.sh
Labels: lgtm, approved

#1809 Add ClusterSyncFailingSeconds metric
  apis/hive/v1/metricsconfig/durationMetrics.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/metrics/metrics.go
  pkg/controller/utils/conditions.go
  vendor/github.com/openshift/hive/apis/hive/v1/metricsconfig/durationMetrics.go
Labels: lgtm, approved

#1803 Update to go 1.18
  Dockerfile
  Dockerfile.ubi
  apis/go.mod
  docs/developing.md
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved

#1780 Ensure correct time reported for transition metrics
  pkg/controller/hibernation/hibernation_controller.go
Labels: lgtm, approved

#1810 Ensure go.mod matches apis/go.mod
  Makefile
  apis/go.mod
  apis/go.sum
  apis/vendor/github.com/go-logr/logr/logr.go
  apis/vendor/github.com/google/gofuzz/.travis.yml
  apis/vendor/github.com/google/gofuzz/CONTRIBUTING.md
  apis/vendor/github.com/google/gofuzz/README.md
  apis/vendor/github.com/google/gofuzz/bytesource/bytesource.go
  apis/vendor/github.com/google/gofuzz/fuzz.go
  apis/vendor/modules.txt
  docs/developing.md
  hack/modcheck.go
  pkg/client/clientset/versioned/clientset.go
Labels: lgtm, approved

#1812 Updates to ibmclient authenticator.
  pkg/ibmclient/client.go
Labels: lgtm, approved
