Repository openshift/hive, pull requests merged in 2024-05, with the labels that each got.

#2269 Copy nodeSelector, tolerations into Jobs
  config/controllers/deployment.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller_test.go
  pkg/controller/clusterprovision/clusterprovision_controller.go
  pkg/controller/clusterprovision/clusterprovision_controller_test.go
  pkg/controller/utils/utils.go
  pkg/imageset/generate.go
  pkg/imageset/generate_test.go
  pkg/install/generate.go
  pkg/install/generate_test.go
  pkg/operator/assets/bindata.go
Labels: lgtm, approved

#2275 Add section for CD conditions in troubleshooting
  docs/troubleshooting.md
Labels: lgtm, approved

#2276 Add alternate regex for TerraformFailedToDeleteResources
  config/configmaps/install-log-regexes-configmap.yaml
  pkg/controller/clusterprovision/installlogmonitor_test.go
  pkg/operator/assets/bindata.go
Labels: lgtm, approved, tide/merge-method-squash

#2277 Document no support of vSphere static IPs with MachinePools
  docs/using-hive.md
Labels: lgtm, approved

#2182 Enhancement for metricsConfig redesign
  docs/enhancements/metricsConfig_redesign.md
Labels: lgtm, approved

#2279 MachinePool/AWS: Match MachineSets by AZ only (not subnet)
  apis/hive/v1/aws/machinepool.go
  config/crds/hive.openshift.io_machinepools.yaml
  hack/app-sre/saas-template.yaml
  pkg/controller/machinepool/awsactuator.go
  pkg/controller/machinepool/machinepool_controller.go
  vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go
Labels: lgtm, approved

#2281 Document ClusterPool support for OpenStack
  docs/clusterpools.md
Labels: lgtm, approved

#2283 HIVE-2509: Skip Konflux builds when possible
  .tekton/hive-pull-request.yaml
  .tekton/hive-push.yaml
Labels: lgtm, approved, jira/valid-reference

#2286 HIVE-2509: Add missing backslash escaping
  .tekton/hive-pull-request.yaml
  .tekton/hive-push.yaml
Labels: lgtm, approved, jira/valid-reference

#2291 HIVE-2510: deprecated image check to 0.4
  .tekton/hive-pull-request.yaml
  .tekton/hive-push.yaml
Labels: lgtm, approved, jira/valid-reference

#2294 [mce-2.3] MachinePool/AWS: Match MachineSets by AZ only (not subnet)
  apis/hive/v1/aws/machinepool.go
  config/crds/hive.openshift.io_machinepools.yaml
  hack/app-sre/saas-template.yaml
  pkg/controller/machinepool/awsactuator.go
  pkg/controller/machinepool/machinepool_controller.go
  vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go
Labels: lgtm, approved

#2297 Update prod datasource
  hack/grafana-dashboards/grafana-dashboard-hive-slo.configmap.yaml
Labels: lgtm, approved
