Repository openshift/hive, pull requests merged in 2024-08, with the labels that each got.

#2389 Hive 2485/mce 2.6: Backport AssumeRole, credential_process, and kubeconfig exec fixes
  contrib/pkg/utils/aws/aws.go
  contrib/pkg/utils/azure/azure.go
  contrib/pkg/utils/gcp/gcp.go
  contrib/pkg/utils/generic.go
  contrib/pkg/utils/openstack/openstack.go
  contrib/pkg/utils/ovirt/ovirt.go
  contrib/pkg/utils/vsphere/vsphere.go
  docs/awsassumerolecreds.md
  pkg/awsclient/client.go
  pkg/controller/argocdregister/argocdregister_controller.go
  pkg/controller/awsprivatelink/awsprivatelink_controller.go
  pkg/controller/awsprivatelink/cleanup.go
  pkg/controller/clusterclaim/clusterclaim_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterinstalls.go
  pkg/controller/clusterdeployment/clusterprovisions.go
  pkg/controller/clusterdeprovision/awsactuator.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/hibernation/aws_actuator.go
  pkg/controller/machinepool/machinepool_controller.go
  pkg/controller/utils/secrets.go
  pkg/install/generate.go
  pkg/installmanager/aws_credentials.go
  pkg/installmanager/aws_credentials_test.go
  pkg/installmanager/installmanager.go
  pkg/remoteclient/kubeconfig.go
  pkg/remoteclient/remoteclient.go
Labels: lgtm, approved

#2378 Konflux fix backport 2.6
  .tekton/hive-mce-26-pull-request.yaml
  .tekton/hive-mce-26-push.yaml
  Dockerfile
  Makefile
Labels: lgtm, approved

#2402 Add python dep 'semver' to hack/requirements.txt
  hack/requirements.txt
Labels: lgtm, approved

#2390 Add ControllerReplica printColumn to clustersync
  apis/hiveinternal/v1alpha1/clustersync_types.go
  config/crds/hiveinternal.openshift.io_clustersyncs.yaml
  hack/app-sre/saas-template.yaml
  vendor/github.com/openshift/hive/apis/hiveinternal/v1alpha1/clustersync_types.go
Labels: lgtm, approved

#2398 HIVE-2584: drop unused Fedora-dev
  build/fedora-dev/Dockerfile.dev
  build/fedora-dev/Dockerfile.devbase
Labels: lgtm, approved, jira/valid-reference

#2403 OCPBUGS-38009: Add pre-4.16 SG filters
  pkg/controller/machinepool/awsactuator.go
  pkg/controller/machinepool/awsactuator_test.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2395 Build faster and leaner: podman-dev-build uses local go cache
  Makefile
Labels: lgtm, approved

#2274 MachinePools/OpenStack: Fix nil pointer exception
  pkg/controller/machinepool/openstackactuator.go
Labels: lgtm, approved

#2412 MachinePool failure domain logging
  pkg/controller/machinepool/machinepool_controller.go
Labels: lgtm, approved

#2417 ClusterPool: Label owned ClusterDeployments
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/controller/clusterpool/clusterpool_controller_test.go
Labels: lgtm, approved

#2418 Document ClusterPool troubleshooting
  docs/clusterpools.md
  docs/troubleshooting.md
Labels: lgtm, approved

#2421 Fix MachinePool poll interval for sharded controller
  pkg/controller/machinepool/machinepool_controller.go
  pkg/operator/hive/hive.go
  pkg/operator/hive/sharded_controllers.go
Labels: lgtm, approved

#2423 e2e: Capture logs from statefulsets (clustersync, machinepool)
  hack/e2e-common.sh
Labels: lgtm, approved

#2416 fieldManager: "hive-$controllername"
  contrib/pkg/adm/managedns/enable.go
  contrib/pkg/awsprivatelink/awsprivatelink.go
  contrib/pkg/clusterpool/clusterclaim.go
  contrib/pkg/clusterpool/clusterpool.go
  contrib/pkg/createcluster/create.go
  contrib/pkg/deprovision/awstagdeprovision.go
  contrib/pkg/deprovision/azure.go
  contrib/pkg/deprovision/gcp.go
  contrib/pkg/deprovision/ibmcloud.go
  contrib/pkg/deprovision/openstack.go
  contrib/pkg/deprovision/ovirt.go
  contrib/pkg/deprovision/vsphere.go
  contrib/pkg/report/deprovisioning.go
  contrib/pkg/report/provisioning.go
  contrib/pkg/utils/client.go
  contrib/pkg/utils/generic.go
  docs/syncset.md
  pkg/controller/clusterrelocate/clusterrelocate_controller.go
  pkg/controller/clusterrelocate/clusterrelocate_controller_test.go
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/utils/clientwrapper.go
  pkg/imageset/updateinstaller.go
  pkg/installmanager/installmanager.go
  pkg/operator/hive/hive_controller.go
  pkg/remoteclient/kubeconfig.go
  pkg/remoteclient/remoteclient.go
  pkg/resource/apply.go
  pkg/resource/helper.go
  pkg/resource/patch.go
Labels: lgtm, approved

#2415 Azure MachinePool: NetworkResourceGroupName, ComputSubnet, VirtualNetwork
  apis/hive/v1/azure/machinepool.go
  apis/hive/v1/machinepool_types.go
  config/crds/hive.openshift.io_machinepools.yaml
  hack/app-sre/saas-template.yaml
  pkg/controller/machinepool/azureactuator.go
  pkg/controller/machinepool/azureactuator_test.go
  vendor/github.com/openshift/hive/apis/hive/v1/azure/machinepool.go
  vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
Labels: lgtm, approved

#2400 Hive 2485/mce 2.4: Backport AssumeRole, credential_process, and kubeconfig exec fixes
  contrib/pkg/utils/aws/aws.go
  contrib/pkg/utils/azure/azure.go
  contrib/pkg/utils/gcp/gcp.go
  contrib/pkg/utils/generic.go
  contrib/pkg/utils/openstack/openstack.go
  contrib/pkg/utils/ovirt/ovirt.go
  contrib/pkg/utils/vsphere/vsphere.go
  docs/awsassumerolecreds.md
  pkg/awsclient/client.go
  pkg/controller/argocdregister/argocdregister_controller.go
  pkg/controller/awsprivatelink/awsprivatelink_controller.go
  pkg/controller/awsprivatelink/cleanup.go
  pkg/controller/clusterclaim/clusterclaim_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterinstalls.go
  pkg/controller/clusterdeployment/clusterprovisions.go
  pkg/controller/clusterdeprovision/awsactuator.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/hibernation/aws_actuator.go
  pkg/controller/machinepool/machinepool_controller.go
  pkg/controller/utils/secrets.go
  pkg/install/generate.go
  pkg/installmanager/aws_credentials.go
  pkg/installmanager/aws_credentials_test.go
  pkg/installmanager/installmanager.go
  pkg/remoteclient/kubeconfig.go
  pkg/remoteclient/remoteclient.go
Labels: lgtm, approved

#2420 MachinePool API: MachineLabels
  apis/hive/v1/machinepool_types.go
  apis/hive/v1/zz_generated.deepcopy.go
  config/crds/hive.openshift.io_machinepools.yaml
  hack/app-sre/saas-template.yaml
  pkg/controller/machinepool/machinepool_controller.go
  pkg/controller/machinepool/machinepool_controller_test.go
  pkg/test/machinepool/machinepool.go
  vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
Labels: lgtm, approved

#2432 Hive 2485/mce 2.3: Backport AssumeRole, credential_process, and kubeconfig exec fixes
  contrib/pkg/utils/aws/aws.go
  contrib/pkg/utils/azure/azure.go
  contrib/pkg/utils/gcp/gcp.go
  contrib/pkg/utils/generic.go
  contrib/pkg/utils/openstack/openstack.go
  contrib/pkg/utils/ovirt/ovirt.go
  contrib/pkg/utils/vsphere/vsphere.go
  docs/awsassumerolecreds.md
  pkg/awsclient/client.go
  pkg/controller/argocdregister/argocdregister_controller.go
  pkg/controller/awsprivatelink/awsprivatelink_controller.go
  pkg/controller/awsprivatelink/cleanup.go
  pkg/controller/clusterclaim/clusterclaim_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterinstalls.go
  pkg/controller/clusterdeployment/clusterprovisions.go
  pkg/controller/clusterdeprovision/awsactuator.go
  pkg/controller/clusterdeprovision/clusterdeprovision_controller.go
  pkg/controller/dnszone/dnszone_controller.go
  pkg/controller/hibernation/aws_actuator.go
  pkg/controller/machinepool/machinepool_controller.go
  pkg/controller/utils/secrets.go
  pkg/install/generate.go
  pkg/installmanager/aws_credentials.go
  pkg/installmanager/aws_credentials_test.go
  pkg/installmanager/installmanager.go
  pkg/remoteclient/kubeconfig.go
  pkg/remoteclient/remoteclient.go
Labels: lgtm, approved

#2434 GOCACHE dir may not exist
  Makefile
Labels: lgtm, approved
