Repository openshift/hive, pull requests merged in 2024-09, with the labels that each got.

#2437 Add e2e support for vsphere
  hack/e2e-common.sh
Labels: lgtm, approved

#2439 Snyk: Ignore azidentity
  .snyk
Labels: lgtm, approved

#2442 Document SyncSet ApplyBehavior
  docs/syncset.md
Labels: lgtm, approved

#2443 Update syncset doc for applyBehavior
  docs/syncset.md
Labels: lgtm, approved

#2444 OCPBUGS-41370: PrivateLink AWS hub actuator to select a vpc in the hub account.
  pkg/controller/privatelink/actuator/awsactuator/awshubactuator.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2446 Azure MachinePool: Add VMNetworkType
  apis/hive/v1/azure/machinepool.go
  config/crds/hive.openshift.io_machinepools.yaml
  hack/app-sre/saas-template.yaml
  pkg/controller/machinepool/azureactuator.go
  pkg/controller/machinepool/azureactuator_test.go
  vendor/github.com/openshift/hive/apis/hive/v1/azure/machinepool.go
Labels: lgtm, approved

#2447 MachinePool GCP: fix zone filter
  pkg/controller/machinepool/gcpactuator.go
  pkg/controller/machinepool/gcpactuator_test.go
Labels: lgtm, approved

#2449 Azure: make creds case-insensitive
  pkg/azureclient/client.go
Labels: lgtm, approved

#2454 OCPBUGS-41797: PrivateLink: GCP PSC to use global endpoints
  pkg/gcpclient/client.go
Labels: lgtm, approved, jira/valid-bug, jira/valid-reference

#2459 ACM-13064: ClusterInstall: Idempotence improvements
  pkg/controller/clusterdeployment/clusterinstalls.go
Labels: lgtm, approved, jira/valid-reference

#2460 MachinePool: GCP: Custom UserTags
  apis/go.mod
  apis/go.sum
  apis/hive/v1/gcp/machinepools.go
  apis/hive/v1/gcp/zz_generated.deepcopy.go
  apis/vendor/github.com/openshift/installer/LICENSE
  apis/vendor/github.com/openshift/installer/NOTICE
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/OWNERS
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/clouduid.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/doc.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/machinepools.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/metadata.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/platform.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/quota.go
  apis/vendor/modules.txt
  config/crds/hive.openshift.io_machinepools.yaml
  hack/app-sre/saas-template.yaml
  pkg/controller/machinepool/gcpactuator.go
  pkg/controller/machinepool/gcpactuator_test.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/machinepools.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/zz_generated.deepcopy.go
Labels: lgtm, approved

#2461 Add hive logs grafana dashboard
  hack/grafana-dashboards/grafana-dashboard-hive-logs.configmap.yaml
Labels: lgtm, approved

#2445 Hibernation controller documentation update
  docs/hibernating-clusters.md
  docs/hibernation_controller.png
Labels: lgtm, approved

#2465 Hive Logs: Make limit custom
  hack/grafana-dashboards/grafana-dashboard-hive-logs.configmap.yaml
Labels: lgtm, approved

#2463 MachinePool: GCP: Custom UserTags
  apis/go.mod
  apis/go.sum
  apis/hive/v1/gcp/machinepools.go
  apis/hive/v1/gcp/zz_generated.deepcopy.go
  apis/vendor/github.com/openshift/installer/LICENSE
  apis/vendor/github.com/openshift/installer/NOTICE
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/OWNERS
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/clouduid.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/doc.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/machinepools.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/metadata.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/platform.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/quota.go
  apis/vendor/modules.txt
  config/crds/hive.openshift.io_machinepools.yaml
  hack/app-sre/saas-template.yaml
  pkg/controller/machinepool/gcpactuator.go
  pkg/controller/machinepool/gcpactuator_test.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/machinepools.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/zz_generated.deepcopy.go
Labels: lgtm, approved

#2467 ClusterVersion: tunable poll interval
  apis/hive/v1/hiveconfig_types.go
  config/crds/hive.openshift.io_hiveconfigs.yaml
  hack/app-sre/saas-template.yaml
  pkg/constants/constants.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/operator/hive/hive.go
  vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
Labels: lgtm, approved

#2472 No-op revendor installer
  apis/go.mod
  apis/go.sum
  apis/vendor/modules.txt
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved

#2470 clusterversion controller: crash on unparseable poll interval
  pkg/controller/clusterversion/clusterversion_controller.go
Labels: lgtm, approved

#2469 MachinePool controller: use RequeueAfter for poll interval
  pkg/controller/machinepool/machinepool_controller.go
Labels: lgtm, approved

#2473 No-op revendor installer
  apis/go.mod
  apis/go.sum
  apis/vendor/modules.txt
  go.mod
  go.sum
  vendor/modules.txt
Labels: lgtm, approved

#2468 HIVE-2622: GCP PrivateLink to use pre-existing psc subnet.
  apis/hive/v1/gcp/platform.go
  apis/hive/v1/gcp/zz_generated.deepcopy.go
  config/crds/hive.openshift.io_clusterdeployments.yaml
  config/crds/hive.openshift.io_clusterpools.yaml
  hack/app-sre/saas-template.yaml
  pkg/controller/privatelink/actuator/gcpactuator/gcplinkactuator.go
  pkg/gcpclient/client.go
  pkg/gcpclient/mock/client_generated.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/platform.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/zz_generated.deepcopy.go
Labels: lgtm, approved, jira/valid-reference

#2475 Remove installer dep from apis/
  apis/go.mod
  apis/go.sum
  apis/hive/v1/gcp/machinepools.go
  apis/hive/v1/gcp/zz_generated.deepcopy.go
  apis/vendor/github.com/openshift/installer/LICENSE
  apis/vendor/github.com/openshift/installer/NOTICE
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/OWNERS
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/clouduid.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/doc.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/machinepools.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/metadata.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/platform.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/quota.go
  apis/vendor/modules.txt
  pkg/controller/machinepool/gcpactuator.go
  pkg/controller/machinepool/gcpactuator_test.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/machinepools.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/zz_generated.deepcopy.go
Labels: lgtm, approved
