Repository openshift/hive, pull requests merged in 2024-06, with the labels that each got.

#2299 Nil check for InstalledTimeStamp missing
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/hibernation/hibernation_controller_test.go
Labels: lgtm, approved

#2300 Fetch centos stream9 because stream8 is EOL
  Dockerfile
Labels: lgtm, approved

#2261 HIVE-2531: Add podman build target
  Makefile
Labels: lgtm, approved, jira/valid-reference

#2302 Sync branch with master
  .tekton/hive-pull-request.yaml
  .tekton/hive-push.yaml
  Dockerfile
  Makefile
  apis/hive/v1/aws/machinepool.go
  config/configmaps/install-log-regexes-configmap.yaml
  config/crds/hive.openshift.io_machinepools.yaml
  docs/clusterpools.md
  docs/enhancements/metricsConfig_redesign.md
  docs/using-hive.md
  hack/app-sre/saas-template.yaml
  hack/grafana-dashboards/grafana-dashboard-hive-slo.configmap.yaml
  pkg/controller/clusterprovision/installlogmonitor_test.go
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/hibernation/hibernation_controller_test.go
  pkg/controller/machinepool/awsactuator.go
  pkg/controller/machinepool/machinepool_controller.go
  pkg/operator/assets/bindata.go
  vendor/github.com/openshift/hive/apis/hive/v1/aws/machinepool.go
Labels: lgtm, approved

#2246 HIVE-2399: Reuse restConfigClientGetter when creating cmdutil.Factory
  apis/hiveinternal/v1alpha1/clustersync_types.go
  contrib/pkg/adm/managedns/enable.go
  contrib/pkg/testresource/command.go
  contrib/pkg/utils/generic.go
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/clustersync/clustersync_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/operator/hive/hive_controller.go
  pkg/remoteclient/fake.go
  pkg/remoteclient/kubeconfig.go
  pkg/remoteclient/mock/remoteclient_generated.go
  pkg/remoteclient/remoteclient.go
  pkg/resource/helper.go
  pkg/resource/restconfig_factory.go
  vendor/github.com/openshift/hive/apis/hiveinternal/v1alpha1/clustersync_types.go
Labels: lgtm, approved, jira/valid-reference

#2304 NOISSUE: Revert "Reuse restConfigClientGetter when creating cmdutil.Factory" (HIVE-2399)
  apis/hiveinternal/v1alpha1/clustersync_types.go
  contrib/pkg/adm/managedns/enable.go
  contrib/pkg/testresource/command.go
  contrib/pkg/utils/generic.go
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/clustersync/clustersync_controller_test.go
  pkg/controller/controlplanecerts/controlplanecerts_controller.go
  pkg/controller/remoteingress/remoteingress_controller.go
  pkg/operator/hive/hive_controller.go
  pkg/remoteclient/fake.go
  pkg/remoteclient/kubeconfig.go
  pkg/remoteclient/mock/remoteclient_generated.go
  pkg/remoteclient/remoteclient.go
  pkg/resource/helper.go
  pkg/resource/restconfig_factory.go
  vendor/github.com/openshift/hive/apis/hiveinternal/v1alpha1/clustersync_types.go
Labels: lgtm, approved

#2305 HIVE-2400: Bump build-image to rhel9
  build/build-image/Dockerfile
Labels: lgtm, approved, jira/valid-reference

#2307 Revert "HIVE-2400: Bump build-image to rhel9"
  build/build-image/Dockerfile
Labels: approved, jira/valid-reference

#2309 Plumb HiveConfig logLevel into controller manager
  cmd/manager/main.go
Labels: lgtm, approved

#2310 Make MachinePool poll interval tunable
  apis/hive/v1/hiveconfig_types.go
  config/crds/hive.openshift.io_hiveconfigs.yaml
  hack/app-sre/saas-template.yaml
  pkg/constants/constants.go
  pkg/controller/clustersync/clustersync_controller.go
  pkg/controller/machinepool/machinepool_controller.go
  pkg/operator/hive/clustersync.go
  pkg/operator/hive/hive.go
  vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
Labels: lgtm, approved

#2313 machinepool: sort ownedLabels, ownedTaints
  pkg/controller/machinepool/machinepool_controller.go
  pkg/controller/machinepool/machinepool_controller_test.go
Labels: lgtm, approved

#2311 HIVE-2400: fix obsolete python references
  Makefile
  hack/app-sre/generate-saas-template.py
  hack/bundle-gen.py
  hack/statuspatch
Labels: lgtm, approved, jira/valid-reference

#2318 HIVE-2400: fix obsolete python references
  Makefile
  hack/app-sre/generate-saas-template.py
  hack/bundle-gen.py
  hack/statuspatch
Labels: jira/valid-reference

#2320 HIVE-2400: Run installmanager binary in install container for fips compatibility
  .tekton/hive-pull-request.yaml
  .tekton/hive-push.yaml
  Dockerfile
  Dockerfile.ubi
  build/build-image/Dockerfile
  contrib/pkg/utils/generic.go
  hack/app_sre_build_deploy.sh
  hack/e2e-common.sh
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/imageset/updateinstaller.go
  pkg/imageset/updateinstaller_test.go
  pkg/install/generate.go
Labels: lgtm, approved, jira/valid-reference

#2260 HIVE-2548: Run installmanager binary in install container for fips compatibility
  .tekton/hive-pull-request.yaml
  .tekton/hive-push.yaml
  Dockerfile
  Dockerfile.ubi
  build/build-image/Dockerfile
  contrib/pkg/utils/generic.go
  hack/app_sre_build_deploy.sh
  hack/e2e-common.sh
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/imageset/updateinstaller.go
  pkg/imageset/updateinstaller_test.go
  pkg/install/generate.go
Labels: approved, do-not-merge/hold, jira/valid-reference

#2322 Fix AWS STS for RHEL8/9 transition
  pkg/install/generate.go
Labels: approved

#2335 HIVE-2518: Vendor cpms to incorporate clean of ResourcePool
  go.mod
  go.sum
  vendor/github.com/openshift/cluster-control-plane-machine-set-operator/pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/providerconfig.go
  vendor/github.com/openshift/cluster-control-plane-machine-set-operator/pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere.go
  vendor/modules.txt
Labels: approved, jira/valid-reference
