Repository openshift/hive, pull requests merged in 2024-10, with the labels that each got.

#2479 Remove installer dep from apis/
  apis/go.mod
  apis/go.sum
  apis/hive/v1/gcp/machinepools.go
  apis/hive/v1/gcp/zz_generated.deepcopy.go
  apis/vendor/github.com/openshift/installer/LICENSE
  apis/vendor/github.com/openshift/installer/NOTICE
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/OWNERS
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/clouduid.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/doc.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/machinepools.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/metadata.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/platform.go
  apis/vendor/github.com/openshift/installer/pkg/types/gcp/quota.go
  apis/vendor/modules.txt
  pkg/controller/machinepool/gcpactuator.go
  pkg/controller/machinepool/gcpactuator_test.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/machinepools.go
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/zz_generated.deepcopy.go
Labels: lgtm, approved

#2476 modcheck -f phase 1: fix `require`s
  hack/modcheck.go
Labels: lgtm, approved

#2481 controller-gen: use vendor/, not build-machinery-go
  Makefile
  config/crds/hive.openshift.io_checkpoints.yaml
  config/crds/hive.openshift.io_clusterclaims.yaml
  config/crds/hive.openshift.io_clusterdeploymentcustomizations.yaml
  config/crds/hive.openshift.io_clusterdeployments.yaml
  config/crds/hive.openshift.io_clusterdeprovisions.yaml
  config/crds/hive.openshift.io_clusterimagesets.yaml
  config/crds/hive.openshift.io_clusterpools.yaml
  config/crds/hive.openshift.io_clusterprovisions.yaml
  config/crds/hive.openshift.io_clusterrelocates.yaml
  config/crds/hive.openshift.io_clusterstates.yaml
  config/crds/hive.openshift.io_dnszones.yaml
  config/crds/hive.openshift.io_hiveconfigs.yaml
  config/crds/hive.openshift.io_machinepoolnameleases.yaml
  config/crds/hive.openshift.io_machinepools.yaml
  config/crds/hive.openshift.io_selectorsyncidentityproviders.yaml
  config/crds/hive.openshift.io_selectorsyncsets.yaml
  config/crds/hive.openshift.io_syncidentityproviders.yaml
  config/crds/hive.openshift.io_syncsets.yaml
  config/crds/hiveinternal.openshift.io_clustersyncleases.yaml
  config/crds/hiveinternal.openshift.io_clustersyncs.yaml
  config/crds/hiveinternal.openshift.io_fakeclusterinstalls.yaml
  hack/app-sre/saas-template.yaml
Labels: lgtm, approved

#2482 Revendor cluster-control-plane-machine-set-operator
  go.mod
  go.sum
  vendor/github.com/openshift/cluster-control-plane-machine-set-operator/pkg/machineproviders/providers/openshift/machine/v1beta1/providerconfig/vsphere.go
  vendor/modules.txt
Labels: lgtm, approved

#2483 OCPBUGS-42740: PrivateLink Actuators should return errors on failure.
  pkg/controller/privatelink/actuator/awsactuator/awshubactuator.go
  pkg/controller/privatelink/actuator/gcpactuator/gcplinkactuator.go
Labels: lgtm, approved, jira/severity-important, jira/valid-bug, jira/valid-reference

#2480 HIVE-2440: Add doc for PrivateLink Controller
  README.md
  docs/privatelink.md
Labels: lgtm, approved, jira/valid-reference

#2488 controller-gen: proper building and pathing
  Makefile
Labels: lgtm, approved

#2491 MachinePool poll interval for fake clusters
  pkg/controller/machinepool/machinepool_controller.go
Labels: lgtm, approved

#2492 MachinePool: Generated MachineLabels are not "owned"
  pkg/controller/machinepool/machinepool_controller.go
  pkg/controller/machinepool/machinepool_controller_test.go
Labels: lgtm, approved

#2495 Hibernation: Requeue without error when ClusterSync doesn't exist yet
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/hibernation/hibernation_controller_test.go
Labels: lgtm, approved

#2496 Use Duration Pattern for syncset, machinepool, clusterversion polls
  apis/hive/v1/hiveconfig_types.go
  config/crds/hive.openshift.io_hiveconfigs.yaml
  hack/app-sre/saas-template.yaml
  vendor/github.com/openshift/hive/apis/hive/v1/hiveconfig_types.go
Labels: lgtm, approved

#2498 HIVE-2397: Nix yaml-patch
  apis/hive/v1/clusterdeploymentcustomization_types.go
  apis/hive/v1/zz_generated.deepcopy.go
  config/crds/hive.openshift.io_clusterdeploymentcustomizations.yaml
  go.mod
  go.sum
  hack/app-sre/saas-template.yaml
  pkg/clusterresource/builder.go
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
  pkg/util/yaml/yaml.go
  pkg/validating-webhooks/hive/v1/clusterdeploymentcustomization_validating_admission_hook.go
  vendor/github.com/krishicks/yaml-patch/LICENSE
  vendor/github.com/krishicks/yaml-patch/Makefile
  vendor/github.com/krishicks/yaml-patch/README.md
  vendor/github.com/krishicks/yaml-patch/container.go
  vendor/github.com/krishicks/yaml-patch/node.go
  vendor/github.com/krishicks/yaml-patch/operation.go
  vendor/github.com/krishicks/yaml-patch/patch.go
  vendor/github.com/krishicks/yaml-patch/pathfinder.go
  vendor/github.com/krishicks/yaml-patch/placeholder_wrapper.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeploymentcustomization_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2500 Update scaling doc for clustersync/machinepool sharding
  docs/scaling-hive.md
Labels: lgtm, approved

#2501 Azure "disable infra" annotation
  pkg/constants/constants.go
  pkg/controller/hibernation/hibernation_controller.go
  pkg/controller/utils/clusterdeployment.go
Labels: lgtm, approved

#2494 Backport all the Dockerfile Makefile improvements
  Dockerfile
  Makefile
  config/crds/hive.openshift.io_checkpoints.yaml
  config/crds/hive.openshift.io_clusterclaims.yaml
  config/crds/hive.openshift.io_clusterdeploymentcustomizations.yaml
  config/crds/hive.openshift.io_clusterdeployments.yaml
  config/crds/hive.openshift.io_clusterdeprovisions.yaml
  config/crds/hive.openshift.io_clusterimagesets.yaml
  config/crds/hive.openshift.io_clusterpools.yaml
  config/crds/hive.openshift.io_clusterprovisions.yaml
  config/crds/hive.openshift.io_clusterrelocates.yaml
  config/crds/hive.openshift.io_clusterstates.yaml
  config/crds/hive.openshift.io_dnszones.yaml
  config/crds/hive.openshift.io_hiveconfigs.yaml
  config/crds/hive.openshift.io_machinepoolnameleases.yaml
  config/crds/hive.openshift.io_machinepools.yaml
  config/crds/hive.openshift.io_selectorsyncidentityproviders.yaml
  config/crds/hive.openshift.io_selectorsyncsets.yaml
  config/crds/hive.openshift.io_syncidentityproviders.yaml
  config/crds/hive.openshift.io_syncsets.yaml
  config/crds/hiveinternal.openshift.io_clustersyncleases.yaml
  config/crds/hiveinternal.openshift.io_clustersyncs.yaml
  config/crds/hiveinternal.openshift.io_fakeclusterinstalls.yaml
  go.mod
  go.sum
  hack/app-sre/saas-template.yaml
  vendor/modules.txt
Labels: lgtm, approved
