Repository openshift/hive, pull requests merged in 2025-02, with the labels that each got.

#2554 HIVE-2763: remove konflux config (YAGNI)
  .tekton/hive-mce-26-pull-request.yaml
  .tekton/hive-mce-26-push.yaml
Labels: lgtm, approved, jira/valid-reference

#2555 HIVE-2763: remove konflux config (YAGNI)
  .tekton/hive-mce-25-pull-request.yaml
  .tekton/hive-mce-25-push.yaml
Labels: lgtm, approved, jira/valid-reference

#2556 HIVE-2764: Upstream builds for operatorhub
  Dockerfile
  Makefile
  hack/ubi-build-deps.sh
Labels: lgtm, approved, jira/valid-reference

#2557 Document metrics FAQ
  docs/hive_metrics.md
Labels: lgtm, approved

#2569 fix(builds): Operatorhub golang bump to 1.23
  .tekton/hive-pull-request.yaml
  .tekton/hive-push.yaml
  hack/ubi-build-deps.sh
Labels: lgtm, approved

#2567 bundle-gen.py: build and push public images
  hack/bundle-gen.py
  hack/version2.py
Labels: lgtm, approved

#2568 Update hiveutil doc: make build-hiveutil
  docs/hiveutil.md
Labels: lgtm, approved

#2552 Eliminate openshift/custom-resource-status dependency
  apis/go.mod
  apis/go.sum
  apis/hive/v1/clusterdeploymentcustomization_types.go
  apis/hive/v1/zz_generated.deepcopy.go
  apis/vendor/github.com/openshift/custom-resource-status/LICENSE
  apis/vendor/github.com/openshift/custom-resource-status/conditions/v1/conditions.go
  apis/vendor/github.com/openshift/custom-resource-status/conditions/v1/doc.go
  apis/vendor/github.com/openshift/custom-resource-status/conditions/v1/types.go
  apis/vendor/github.com/openshift/custom-resource-status/conditions/v1/zz_generated.deepcopy.go
  apis/vendor/modules.txt
  config/crds/hive.openshift.io_clusterdeploymentcustomizations.yaml
  go.mod
  go.sum
  hack/app-sre/saas-template.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterpool/clusterpool_controller_test.go
  pkg/controller/clusterpool/collections.go
  pkg/test/assert/assertions.go
  pkg/test/clusterdeploymentcustomization/clusterdeploymentcustomization.go
  vendor/github.com/openshift/custom-resource-status/LICENSE
  vendor/github.com/openshift/custom-resource-status/conditions/v1/conditions.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/doc.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/types.go
  vendor/github.com/openshift/custom-resource-status/conditions/v1/zz_generated.deepcopy.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeploymentcustomization_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: lgtm, approved

#2582 HIVE-2781: nix terminateWhenFilesChange()
  contrib/pkg/deprovision/awstagdeprovision.go
  contrib/pkg/deprovision/deprovision.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/OWNERS
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer.go
  vendor/github.com/openshift/library-go/pkg/controller/fileobserver/observer_polling.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2577 konflux/mce-2.7: fix konflux configs
  .tekton/hive-mce-27-pull-request.yaml
  .tekton/hive-mce-27-push.yaml
  Dockerfile
Labels: approved

#2583 HIVE-2785: Remove obsolete version check
  pkg/controller/machinepool/gcpactuator.go
  pkg/controller/machinepool/gcpactuator_test.go
  pkg/controller/machinepool/machinepool_controller.go
Labels: lgtm, approved, jira/valid-reference

#2585 HIVE-2787: CVE-2025-22868 x/oauth2/jws 0.27.0
  go.mod
  go.sum
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/jws/jws.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/pkce.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2584 HIVE-2786: CVE-2025-22869: x/crypto/ssh 0.35.0
  apis/go.mod
  apis/go.sum
  apis/vendor/modules.txt
  go.mod
  go.sum
  vendor/golang.org/x/crypto/pkcs12/crypto.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2586 HIVE-2788: MachinePool/GCP: Remove DiskType enum
  apis/hive/v1/gcp/machinepools.go
  config/crds/hive.openshift.io_machinepools.yaml
  hack/app-sre/saas-template.yaml
  vendor/github.com/openshift/hive/apis/hive/v1/gcp/machinepools.go
Labels: lgtm, approved, jira/valid-reference

#2588 [mce-2.8] HIVE-2786: CVE-2025-22869: x/crypto/ssh 0.35.0
  apis/go.mod
  apis/go.sum
  apis/vendor/modules.txt
  go.mod
  go.sum
  vendor/golang.org/x/crypto/pkcs12/crypto.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: approved, jira/valid-reference
