Repository openshift/hive, pull requests merged in 2025-04, with the labels that each got.

#2650 HIVE-2819: Use annotation instead of label for upgradeable
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
Labels: lgtm, approved, jira/valid-reference

#2642 Correct len parameters of make() in some tests
  pkg/controller/dnsendpoint/dnsendpoint_controller_test.go
  pkg/controller/machinepool/gcpactuator_test.go
  pkg/controller/metrics/custom_collectors_test.go
Labels: lgtm, approved, ok-to-test

#2649 HIVE-2826: Limit konflux bot PRs to tekton
  renovate.json
Labels: lgtm, approved, jira/valid-reference

#2651 HIVE-2416: Fix copypasta error in MachinePool Reasons
  pkg/controller/machinepool/machinepool_controller.go
Labels: lgtm, approved, jira/valid-reference

#2652 HIVE-2827: Fix MachinePool thrashing on conditions
  pkg/controller/machinepool/machinepool_controller.go
Labels: lgtm, approved, jira/valid-reference

#2656 HIVE-2836: CVE-2025-22872: Bump x/net to v0.38.0
  apis/go.mod
  apis/go.sum
  apis/vendor/golang.org/x/net/http2/frame.go
  apis/vendor/golang.org/x/net/http2/server.go
  apis/vendor/golang.org/x/net/http2/transport.go
  apis/vendor/golang.org/x/net/internal/httpcommon/headermap.go
  apis/vendor/golang.org/x/net/internal/httpcommon/request.go
  apis/vendor/modules.txt
  go.mod
  go.sum
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/net/context/context.go
  vendor/golang.org/x/net/context/go17.go
  vendor/golang.org/x/net/context/go19.go
  vendor/golang.org/x/net/context/pre_go17.go
  vendor/golang.org/x/net/context/pre_go19.go
  vendor/golang.org/x/net/html/atom/table.go
  vendor/golang.org/x/net/html/parse.go
  vendor/golang.org/x/net/html/token.go
  vendor/golang.org/x/net/http2/frame.go
  vendor/golang.org/x/net/http2/server.go
  vendor/golang.org/x/net/http2/transport.go
  vendor/golang.org/x/net/internal/httpcommon/headermap.go
  vendor/golang.org/x/net/internal/httpcommon/request.go
  vendor/golang.org/x/net/proxy/per_host.go
  vendor/golang.org/x/net/websocket/websocket.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sync/errgroup/go120.go
  vendor/golang.org/x/sync/errgroup/pre_go120.go
  vendor/golang.org/x/text/internal/number/format.go
  vendor/golang.org/x/text/language/parse.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2659 HIVE-2807: SyncSet: Accept empty patchType
  pkg/validating-webhooks/hive/v1/syncset_validating_admission_hook.go
  pkg/validating-webhooks/hive/v1/syncset_validating_admission_hook_test.go
Labels: lgtm, approved, jira/valid-reference

#2661 fix(HIVE-2838): privatelink-controller: paginate retrieved vpc endpoints
  pkg/controller/awsprivatelink/awsprivatelink_controller.go
Labels: lgtm

#2668 HIVE-2837: Revert AWSPrivateLink cleanup code
  pkg/controller/awsprivatelink/awsprivatelink_controller.go
  pkg/controller/awsprivatelink/awsprivatelink_controller_test.go
  pkg/controller/awsprivatelink/cleanup.go
Labels: lgtm, approved, ok-to-test, jira/valid-reference

#2669 Migration fixups
  .tekton/hive-pull-request.yaml
  .tekton/hive-push.yaml
Labels: approved
