Repository openshift/hive, pull requests merged in 2025-03, with the labels that each got.

#2594 HIVE-2791: MachinePool/OpenStack: Remove obsolete version check
  pkg/controller/machinepool/machinepool_controller.go
Labels: lgtm, approved, jira/valid-reference

#2596 HIVE-2475: Add comment for machinepool override annotation
  pkg/constants/constants.go
Labels: lgtm, approved, jira/valid-reference

#2597 HIVE-2797: Forbid editing CD ClusterPoolRef CustomizationRef
  apis/hive/v1/clusterdeployment_types.go
  apis/hive/v1/clusterdeploymentcustomization_types.go
  apis/hive/v1/clusterpool_types.go
  apis/hive/v1/zz_generated.deepcopy.go
  config/crds/hive.openshift.io_clusterdeploymentcustomizations.yaml
  config/crds/hive.openshift.io_clusterdeployments.yaml
  config/crds/hive.openshift.io_clusterpools.yaml
  docs/enhancements/clusterpool-inventory.md
  hack/app-sre/saas-template.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/controller/clusterpool/clusterpool_controller_test.go
  pkg/controller/clusterpool/collections.go
  pkg/controller/utils/clusterdeployment.go
  pkg/controller/utils/sa.go
  pkg/installmanager/installmanager.go
  pkg/test/clusterdeploymentcustomization/clusterdeploymentcustomization.go
  pkg/test/clusterpool/clusterpool.go
  pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook.go
  pkg/validating-webhooks/hive/v1/clusterdeployment_validating_admission_hook_test.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeploymentcustomization_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
Labels: lgtm, approved, jira/valid-reference

#2499 Support patching installer manifests
  apis/hive/v1/clusterdeployment_types.go
  apis/hive/v1/clusterdeploymentcustomization_types.go
  apis/hive/v1/clusterpool_types.go
  apis/hive/v1/zz_generated.deepcopy.go
  config/crds/hive.openshift.io_clusterdeploymentcustomizations.yaml
  config/crds/hive.openshift.io_clusterdeployments.yaml
  config/crds/hive.openshift.io_clusterpools.yaml
  docs/enhancements/clusterpool-inventory.md
  hack/app-sre/saas-template.yaml
  pkg/controller/clusterdeployment/clusterdeployment_controller.go
  pkg/controller/clusterdeployment/clusterdeployment_controller_test.go
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/controller/clusterpool/clusterpool_controller_test.go
  pkg/controller/clusterpool/collections.go
  pkg/controller/utils/clusterdeployment.go
  pkg/controller/utils/sa.go
  pkg/installmanager/installmanager.go
  pkg/test/clusterdeploymentcustomization/clusterdeploymentcustomization.go
  pkg/test/clusterpool/clusterpool.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeployment_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterdeploymentcustomization_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/clusterpool_types.go
  vendor/github.com/openshift/hive/apis/hive/v1/zz_generated.deepcopy.go
Labels: approved

#2598 HIVE-1793: review followup
  pkg/controller/clusterpool/clusterpool_controller.go
  pkg/controller/utils/clusterdeployment.go
Labels: lgtm, approved, jira/valid-reference

#2599 [mce-2.7] HIVE-2786: CVE-2025-22869: x/crypto/ssh 0.35.0
  apis/go.mod
  apis/go.sum
  apis/vendor/modules.txt
  go.mod
  go.sum
  vendor/golang.org/x/crypto/pkcs12/crypto.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2602 [mce-2.6] HIVE-2786: CVE-2025-22869: x/crypto/ssh 0.35.0
  apis/go.mod
  apis/go.sum
  apis/vendor/modules.txt
  go.mod
  go.sum
  vendor/golang.org/x/crypto/pkcs12/crypto.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/sync/errgroup/errgroup.go
  vendor/golang.org/x/sys/cpu/cpu.go
  vendor/golang.org/x/sys/cpu/cpu_x86.go
  vendor/golang.org/x/sys/unix/auxv.go
  vendor/golang.org/x/sys/unix/auxv_unsupported.go
  vendor/golang.org/x/sys/unix/syscall_dragonfly.go
  vendor/golang.org/x/sys/unix/syscall_solaris.go
  vendor/golang.org/x/sys/unix/zerrors_linux.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_loong64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_solaris_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_386.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_amd64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_loong64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_s390x.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_sparc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux.go
  vendor/golang.org/x/sys/windows/dll_windows.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2601 [mce-2.5] HIVE-2787: CVE-2025-22868 x/oauth2/jws => 0.26.openshift.1
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/LICENSE
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/cloud.google.com/go/compute/metadata/CHANGES.md
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/cloud.google.com/go/compute/metadata/retry.go
  vendor/cloud.google.com/go/compute/metadata/tidyfix.go
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/google/appengine.go
  vendor/golang.org/x/oauth2/google/appengine_gen1.go
  vendor/golang.org/x/oauth2/google/appengine_gen2_flex.go
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/externalaccount/executablecredsource.go
  vendor/golang.org/x/oauth2/google/externalaccount/filecredsource.go
  vendor/golang.org/x/oauth2/google/externalaccount/header.go
  vendor/golang.org/x/oauth2/google/externalaccount/programmaticrefreshcredsource.go
  vendor/golang.org/x/oauth2/google/externalaccount/urlcredsource.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/err.go
  vendor/golang.org/x/oauth2/google/internal/impersonate/impersonate.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/jws/jws.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2497 RFE: Patch Installer Manifests
  docs/enhancements/patch-install-manifests.md
Labels: lgtm, approved

#2603 [mce-2.4] HIVE-2787: CVE-2025-22868 x/oauth2/jws => 0.26.openshift.1
  go.mod
  go.sum
  vendor/cloud.google.com/go/compute/LICENSE
  vendor/cloud.google.com/go/compute/internal/version.go
  vendor/cloud.google.com/go/compute/metadata/CHANGES.md
  vendor/cloud.google.com/go/compute/metadata/metadata.go
  vendor/cloud.google.com/go/compute/metadata/retry.go
  vendor/cloud.google.com/go/compute/metadata/tidyfix.go
  vendor/golang.org/x/oauth2/LICENSE
  vendor/golang.org/x/oauth2/README.md
  vendor/golang.org/x/oauth2/google/appengine.go
  vendor/golang.org/x/oauth2/google/appengine_gen1.go
  vendor/golang.org/x/oauth2/google/appengine_gen2_flex.go
  vendor/golang.org/x/oauth2/google/default.go
  vendor/golang.org/x/oauth2/google/doc.go
  vendor/golang.org/x/oauth2/google/externalaccount/aws.go
  vendor/golang.org/x/oauth2/google/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/externalaccount/executablecredsource.go
  vendor/golang.org/x/oauth2/google/externalaccount/filecredsource.go
  vendor/golang.org/x/oauth2/google/externalaccount/header.go
  vendor/golang.org/x/oauth2/google/externalaccount/programmaticrefreshcredsource.go
  vendor/golang.org/x/oauth2/google/externalaccount/urlcredsource.go
  vendor/golang.org/x/oauth2/google/google.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/basecredentials.go
  vendor/golang.org/x/oauth2/google/internal/externalaccount/err.go
  vendor/golang.org/x/oauth2/google/internal/impersonate/impersonate.go
  vendor/golang.org/x/oauth2/internal/client_appengine.go
  vendor/golang.org/x/oauth2/internal/transport.go
  vendor/golang.org/x/oauth2/jws/jws.go
  vendor/golang.org/x/oauth2/oauth2.go
  vendor/golang.org/x/oauth2/token.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2604 [mce-2.5] HIVE-2786: CVE-2025-22869: x/crypto/ssh v0.33.openshift.1
  go.mod
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2612 HIVE-2804: Scrub username and password fields on metadata.json
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: lgtm, approved, jira/valid-reference

#2613 HIVE-2805: Ignore a couple of snyk vulns
  .snyk
Labels: approved, jira/valid-reference

#2619 ACM-18777: Cleanse metadata.json on the ClusterProvision object
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: lgtm, approved, jira/valid-reference

#2618 ACM-18776: Cleanse metadata.json on the ClusterProvision object
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: lgtm, approved, jira/valid-reference

#2616 ACM-18784: Cleanse metadata.json on the ClusterProvision object
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: lgtm, approved, jira/valid-reference

#2615 ACM-18780: Cleanse metadata.json on the ClusterProvision object
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: lgtm, approved, jira/valid-reference

#2620 ACM-18787: Cleanse metadata.json on the ClusterProvision object
  pkg/installmanager/installmanager.go
  pkg/installmanager/installmanager_test.go
Labels: lgtm, approved, jira/valid-reference

#2621 HIVE-2769: bundle-gen: skip konflux branches
  hack/version2.py
Labels: lgtm, approved, jira/valid-reference

#2629 HIVE-2812: e2e: MachinePool tests retry on 409
  test/e2e/common/machinepool.go
  test/e2e/postinstall/machinesets/infra_test.go
Labels: lgtm, approved, jira/valid-reference

#2630 HIVE-2813: Bump jwt/v4 and v5
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2632 [mce-2.8] HIVE-2813: Bump jwt/v4 and v5
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2635 [mce-2.5] HIVE-2813: Bump jwt/v4
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2633 [mce-2.7] HIVE-2813: Bump jwt/v4 and v5
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2634 [mce-2.6] HIVE-2813: Bump jwt/v4 and v5
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/github.com/golang-jwt/jwt/v5/README.md
  vendor/github.com/golang-jwt/jwt/v5/SECURITY.md
  vendor/github.com/golang-jwt/jwt/v5/parser.go
  vendor/github.com/golang-jwt/jwt/v5/token.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2636 [mce-2.4] HIVE-2813: Bump jwt/v4
  go.mod
  go.sum
  vendor/github.com/golang-jwt/jwt/v4/parser.go
  vendor/modules.txt
Labels: lgtm, approved, jira/valid-reference

#2639 HIVE-2819: Lift upgradeable condition from CVO to cluster deployment label
  pkg/constants/constants.go
  pkg/controller/clusterversion/clusterversion_controller.go
  pkg/controller/clusterversion/clusterversion_controller_test.go
Labels: lgtm, approved, jira/valid-reference

#2628 HIVE-2416: MachinePool errors in status conditions
  apis/hive/v1/machinepool_types.go
  pkg/client/fake/overrideable_client.go
  pkg/controller/machinepool/machinepool_controller.go
  pkg/controller/machinepool/machinepool_controller_test.go
  pkg/test/machinepool/machinepool.go
  vendor/github.com/openshift/hive/apis/hive/v1/machinepool_types.go
Labels: lgtm, approved, jira/valid-reference
